### ISSUE TITLE
Lots of mistakes in COE pyret solutions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1014]
![Screen Shot 2022-06-29 at 4 14 41 PM](https://user-images.githubusercontent.com/66691020/176546068-3095f783-83cc-41c0-9d24-41575d1d0b3d.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 15 03 PM](https://user-images.githubusercontent.com/66691020/176546169-3401c065-d385-4cc6-a953-5b781ac79b38.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 15 11 PM](https://user-images.githubusercontent.com/66691020/176546190-5270bde4-ecdf-4731-bd58-54e0038e0408.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 15 18 PM](https://user-images.githubusercontent.com/66691020/176546206-c665453e-37e6-472f-821e-e1e7496f89da.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 15 52 PM](https://user-images.githubusercontent.com/66691020/176546397-a2f40dd3-3fea-415f-a91a-5a1a899e2957.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 16 05 PM](https://user-images.githubusercontent.com/66691020/176546411-bd9767b6-3422-4284-bd76-12ed00402e7c.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme
![Screen Shot 2022-06-29 at 4 16 15 PM](https://user-images.githubusercontent.com/66691020/176546426-de33582c-055d-4778-b5ad-2933f7c2d628.png)
- [x]  building correctly in pyret
- [x]  building correctly in wescheme

**Comment by flannery-denny** [comment]
@ds26gte All of these images are from pages where the first column is what's provided and the other columns are autogenerated.  I am hopeful that you will be able to see what's not correct from looking at the images, but I'm happy to talk through these pages tomorrow afternoon if you have questions.

All but the last image are from the order of operations lesson. I'm honestly not sure where the last one comes from... maybe one of the inequalities lessons?

**Comment by ds26gte** [comment]
Fix pushed. In general, the CoEs are all correct (based on the Scheme original). However, there were two bugs, one related to the math conversion, the other to the Pyret conversion:

1. The math conversion wasn't wrapping parens around the args in a division expression. It also wasn't wrapping parens around a division within a times operation (technically not needed but I agree it looks nicer with explicit parens).
2. The code conversion was losing parens in odd places because of an AsciiDoc kludge. I was using `{empty}` to prevent parens from sticking but that wasn't enough. I had changed it to `{zwsp}` while fixing issue #985, but the pages you adduced as examples predated that fix.

**Comment by schanzer** [comment]
@ds26gte nice! @flannery-denny close if this resolves the issues?

**Comment by flannery-denny** [comment]
@ds26gte In my first read, some of these pages now build as I would expect them to, and while some of the others are now technically correct, they are not true to the original problem (there are parentheses appearing in the expressions in the first column that were not appearing in the original versions of these expressions). I will investigate more deeply tomorrow.
