### ISSUE TITLE
live on web - hyperlinks to workbook pages for "Table Methods" do not work

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1019]
https://bootstrapworld.org/materials/fall2022/en-us/lessons/table-methods/index.shtml?pathway=data-science

All worksheet links in this lesson go to "this page is missing".

**Comment by schanzer** [comment]
@ds26gte this is **really** concerning. Somehow the build script is failing to copy adoc pages over.

**Comment by ds26gte** [comment]
The `lessons/table-methods` directory on the web host is indeed empty. However it is not empty when I build locally. It looks like there may have been an interruption during the deployment that cut short the copying of the requisite files. (Especially since the other `lessons/*` directories seem correctly populated.
