### ISSUE TITLE
CODAP pathway feedback

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1043]
I've pushed a commit that addresses some of the smaller issues below, and checked the boxes so you know they're done. As a meta-comment, I wonder if it this pathway shouldn't use some form of the "Dataset Exploration" paper as a scaffold, encouraging students to generate a finished product based on the work they do in CODAP. I found myself wishing I had some place to _put_ all the results from my transformer work!

**DS-Intro**

- [x] link to spreadsheet uses the pyret version, but should use codap instead

**Exploring CODAP**

- [x] I really like how this lesson has evolved, but the title doesn't fit the new form. Basically this is "exploring CODAP", which includes numbers and strings but also a lot of the UI. Can we rename this lesson exploring-codap?
- [x] Should we hide the language table link? It doesn't make a ton of sense in the context of CODAP (see #1061)
- [x] question 6 in "CODAP Exploration" feels almost too hard. Can you change the prompt so that it tells them to click the "+" sign? There's no way we could expect them to know this in advance.  _Some_ kids will figure it out, but others may feel like they're "behind" and get unnecessarily stressed.
- [x] In "Numbers and Strings", what should a teacher do with a kid who asks why 1/3 evaluates to 0.33 (non-repeating)?
- [x] In "Numbers and Strings", the solutions for question 11 need to address another CODAP inconsistency. 
- [x] The language in the "Expressions" part of the lesson is a little off. Arguments are passed into _functions_, not expressions. The current wording is particularly jarring because it starts out using "expressions" but then the very next sentence talks about functions!
- [x] The wbPage "Expressions in CODAP" exclusively talks about expressions in which functions are applied. Maybe re-title it "Applying Functions in CODAP"?

**CODAP Bar Charts**

- [ ] The first instruction box asks me to click on a dot in the scatter plot, then a row in the table. Right now nothing happens. Should it? Wondering if this is a codap bug.
- [x] The lesson plan does a nice job dealing with CODAP's weird vocab (e.g. - "Quantitative (or numeric) data must..."). Can the "Data Displays" wbpage reflect that as well, so kids see both terms everywhere?
- [x] Practice-plotting-2 has two exercises, but practice-plotting only has one. Can we have them both use 2, and maximize the printed page?
- [x] Additional Exercises is empty. Should it be? If so, we can remove the heading altogether.

**Data Cycle**

- [x] The "Data Cycle: Analyzing with Displays" wbpage needs a codap version

**Introduction to Transformers: Sort**

- [x] The second Investigate section has students complete a worksheet, but does not use [.lesson-instruction]

**More Transformers: Filter, Transform, Build**

- [x] The first Investigate section has students complete a worksheet, but does not use [.lesson-instruction]
- [x] In the filter worksheet, when typing `Fixed = true`, it's important to pay attention to case! Can the worksheet add a 6th question that asks students to try` fixed = true`. `FIXED = true`, and `fixed = TRUE`?
- [x] In the filter worksheet, can we make the "more filtering" bullets into numbered questions that include some written output? For example, "how many rows does the resulting table have?"
- [x] I don't see anything in the lesson plan or workbook pages that tells me I need to use backticks for dealing with a column called `Age (years)`. Given that the Transform wbpage can't be completed without it, this information should be written into the lesson plan and probably the wbpage as well.
- [x] In the transform worksheet, can we make the "more transfoming" bullet into a numbered questions that includes some written ouput? For example, "how many kilograms is the heaviest animal in the shelter?"
- [x] In the Build worksheet, why isn't there any "more building" section? All the others have it, and I found myself expecting one. :-)
- [x] In "which table do we get?", the line spacing is too big and it's hard to tell when one transformer ends and the other begins. We should make the line height smaller here.

**Probability, Inference, and Sample Size**
- [x] The "Sampling and Inference" page should have screenshots centered.
- [ ] I propose adding a pedagogy box that connects the discussion of replacement to the math standards around combinations and permutations -- both of them involve parallel discussions of replacement, and this further ties the discussion of probability to sampling and inference.
- [x] Is the predictions-from-samples page no longer used? I don't see it referenced here.

**Grouped Samples**

- [ ] I wonder if this wouldn't be a good place to bring back expression cards, and remind students that they can "play the cards" to compose operations? Might be a good lesson note to add to Pyret, as well.

**Comment by retabak** [comment]
Still working my way through these (have checked off items I was able to take care of) but have a few questions that I wanted to put on your radar, @schanzer .

Simple Data Types
- [ ] Should we hide the language table link? It doesn't make a ton of sense in the context of CODAP. **Yes. How do we do that?**
- [ ] The language in the "Expressions" part of the lesson is a little off. Arguments are passed into functions, not expressions. The current wording is particularly jarring because it starts out using "expressions" but then the very next sentence talks about functions! **We had a conversation about this but I think it was in real time because I can't find any trace of it on Slack. We agreed to title this section EXPRESSIONS (and not functions) because of how the Transformers work, and how they smush together methods, functions, and expressions. That said, I'm not sure how to tweak the language in this section of the lesson so that it makes sense and might need some guidance there. Any thoughts? Maybe we should discuss in real-time.**  
- [ ] The wbPage "Expressions in CODAP" exclusively talks about expressions in which functions are applied. Maybe re-title it "Applying Functions in CODAP"? **Again, we agreed to avoid the F-word. If this is confusing, we need to discuss / rethink. I'm not sure of the best path forward.**

Bar Charts
- [ ] The first instruction box asks me to click on a dot in the scatter plot, then a row in the table. Right now nothing happens. Should it? Wondering if this is a codap bug. **Oh weird. If I import the dataset with the importer and click on a dot or a row, stuff happens. But if I click on a dot or a row in the saved+shared file, nothing happens. This does appear to be a CODAP bug. I guess I should report it?**

Data Cycle
- [ ] - The "Data Cycle: Analyzing with Displays" wbpage needs a codap version -- **I think the only change to this worksheet is that the "Analyze Data" step needs to prompt _not_ for code to be provided, but instead the configuration / measure? Do you think other changes are needed?**

**Comment by schanzer** [comment]
@retabak left you some comments above. Agreed that we should meet to discuss the other issues.

**Comment by retabak** [comment]
I've obsessed over these lessons a lot and am feeling good about where they are. @flannery-denny - want to take a look? (Slides are not finalized yet, so don't worry about those--but everything else should be in decent shape.) @schanzer has already reviewed. Ready for a fine-tooth comb!

ds-intro
codap-exploring
codap-bar-charts
data-cycle
codap-transformers-1
codap-transformers-2
method-chaining
random-samples
grouped-samples

**Comment by flannery-denny** [comment]
@retabak Exciting! Building now.

**Comment by flannery-denny** [comment]
@schanzer @retabak I get these two warnings when I build the CODAP pathway, but I don't see any lesson named `codap-apply-functions`. Any idea where they're coming from?

> asciidoctor: WARNING: .codap-apply-functions.asc: line 21: unterminated table block
> asciidoctor: WARNING: .codap-apply-functions.asc: line 26: unterminated table block

**Comment by retabak** [comment]
Hey! It's a worksheet in codap-exploring. I can try to figure out what's
going on. I had some struggles with a table on that page and think I
decided to try to figure out the problem later (and then forgot to return
to it later). If you can identify the issue easily and fix it, I'd be
grateful!

**Comment by flannery-denny** [comment]
@retabak 
I'll check it out.

**Comment by flannery-denny** [comment]
DS - Intro
![Screen Shot 2022-08-03 at 9 48 44 AM](https://user-images.githubusercontent.com/66691020/182639625-8965a0ca-0dc6-44d1-99fe-79972a833b5f.png)
I don't think these instructions are CODAP compatible.

**Comment by flannery-denny** [comment]
Exploring CODAP
- [ ] Lesson Goals need codapifying
![Screen Shot 2022-08-03 at 10 08 12 AM](https://user-images.githubusercontent.com/66691020/182643180-2076eb52-051e-42b1-a19f-f4dee69a8a8e.png)
- [ ] Do these all apply to CODAP?
![Screen Shot 2022-08-03 at 10 09 30 AM](https://user-images.githubusercontent.com/66691020/182643403-0a307d19-61d8-42f5-9323-8a5d8dbc5491.png)
- [ ] there is no plus sign in the top right when I open animals in codap until after I click on a cell in the table... suggest adding that to directions... took me a while to figure out what I was doing wrong.
![Screen Shot 2022-08-03 at 10 13 10 AM](https://user-images.githubusercontent.com/66691020/182644436-7c70c13c-019c-445c-b16f-81a0a5fe4da6.png)
- [ ] Numbers and Strings - as far as I can tell "42" is the same as `42` in CODAP, in which case I don't think it's really helping students understand what a string is to ask them to experiment with that example. Unless you're seeing something that I am not, this also means we need to cut the statement **Anything in quotes is a String, even something like "42".**
- [ ] Booleans. I get a syntax error when I type `3 !> 3` or `3!3`

**Comment by flannery-denny** [comment]
BAR CHARTS

**Concern** - This lesson has student play around with histograms in a pretty free form way and then provides no scaffolding for making sense of the complexity of what they've just engaged with... bin width, etc. Histograms are not a super intuitive concept. In the main data science pathway we have a lot of materials (1-2 entire lessons!) to making sense of this concept. I don't feel comfortable with leaving this section where it's at and it doesn't feel necessary to include it in order to get at Bar Charts. I suggest removing it (and the discussion of the misconception about bar charts and histograms) and making a separate lesson dedicated to histograms... even though I see that making them starts the same way in CODAP.
If @retabak and @schanzer are both in agreement that histograms belong in this lesson, then both the exploration page and the discussion that follow need much more directed scaffolding.

- [ ] Do you want to call this lesson Bar Charts or Bar Graphs? Both appear at the top of the lesson
![Screen Shot 2022-08-03 at 1 18 55 PM](https://user-images.githubusercontent.com/66691020/182839250-358225f8-a68b-4f80-b560-607948ac25a1.png)
- [ ] When I click graph and then click on a dot or a row, nothing happens. If I click graph again, I get a new scatterplot that I still can't interact with. Feels like there's a direction missing. (FYI - I can interact once I select a label for the axes)
- [ ] Data Displays in CODAP 
- This page could use more lines for students to answer some of your big explanation questions.
- Numerical vs Categorical - the CODAP language is **Numeric** v Categorical
- [ ] Practice Plotting - I recommend reconfiguring this so that "sketch" and "what do you think" are side by side. This would make the shape of the "sketch" section more square, which would allow for bigger sketches.

**Comment by flannery-denny** [comment]
**DATA CYCLE**
- [ ] Questions and Column Descriptions 
- @schanzer This isn't a CODAP specific thing, but every time I look at this page I want the distinction between notice and wonder to be more exaggerated since "answered by this dataset" only goes with wonders... Ideas on how to achieve that. 
- This workbook page use the word Quantitative. CODAP uses the word Numeric. Do we want to be consistent with CODAP? Do we want students to be fluent in both? If the latter, we should introduce both words when we introduce them to the word Numeric.
- [ ] I recommend being explicit that we sometimes need all row and sometimes only need a subset.
![Screen Shot 2022-08-04 at 7 18 48 AM](https://user-images.githubusercontent.com/66691020/182845215-1224e04c-bb84-405b-92aa-9658c6eefc8a.png)
We have this built into the Data Cycle template...
![Screen Shot 2022-08-04 at 7 23 30 AM](https://user-images.githubusercontent.com/66691020/182846189-f42b781a-b950-4adc-a599-c968240c1122.png)

- [ ] There are questions in the Analyze Data cycle section that include skill we haven't introduced yet. We don't know how to filter. We don't know when to use a histogram...
![Screen Shot 2022-08-04 at 7 22 06 AM](https://user-images.githubusercontent.com/66691020/182845938-769ac251-fbfa-4dc4-ba67-37a468747e68.png)

- [ ] 
.

**Comment by flannery-denny** [comment]
**INTRO TO TRANSFORMERS**
- [ ] Sort Tranformer - 
- Do all file names need hyphens? If so, make it explicit that names can't have spaces in the directions.
- It's not totally obvious to me what the answer to this question should be. _7 How is saving a Transformer different from saving a dataset?_ Is there somewhere specific that I should be looking? How is the answer supposed to be different from _4 Apply the Transformer. What happens?_ My guess is that you want me to notice that there's a new dataset listed in the dropdown menu, but it's intuitive that I should bother to look there from what's being asked of me...
-

**Comment by flannery-denny** [comment]
**MORE TRANSFORMERS**
- [ ] The directions for the activity tell the student to keep the information a secret. The example is of a question that they have to ask out loud of every student. These things seem to conflict?
- [ ] Filter - If you're going to put these directions at the top, _Make sure you’re logged into CODAP with the Animals Dataset open._, why not hotlink them?
- When I apply the transformer `Fixed = true` I get an empty dataset (the other two version of typing yield errors and I can see that there are plenty of fixed animals... seems like maybe there's a bug with CODAP?
- [ ] Transform
- `Age <5` doesn't work. They need to type `Age (years)`<5 _Why is this true if `Weight > 40` works?_
- More Transforming - There are a lot of steps to this task. Are you sure you don't want them to record more of them? you might consider something in the direction of the scaffolds on the plotting practice page. or a data cycle page. 
- [ ] I have the same question for More Building as I did for More Transforming

**Comment by flannery-denny** [comment]
**METHOD CHAINING**
- [ ] Design Recipe 1
- The directions suggest that students will be `adding relevant columns`. I don't see any examples of them getting to do that.
- Why not have two problems on this page?
- [ ] Design Recipe 2
- Why does the first transformed table have an age (years) column?
- Why is there a species column for the second problems

**Comment by flannery-denny** [comment]
**GROUPED SAMPLES**

- [ ] I'm seeing these directions
>  A “kitten” is an animal who is a cat and who is young. How would you define a table of just kittens?
> 
> Turn to [Grouped Samples from the Animals Dataset](https://github.com/bootstrapworld/lessons/grouped-samples-codap/pages/samples-from-animals-dataset.html), and see what sequence of Transformers will compute whether or not an animal is a kitten.
> 
> Can you fill in the function notation for the other grouped samples?
> 
> **Make a bar chart showing the distribution of sex in the kittens subset .**

As far as I can tell, in order to make the bar chart in question I would need to build the columns `is-young` and `is-cat` before I can filter for `filter-is-young(filter-is-cat(animals-table))`

Maybe I'm missing something, but that feels like a lot of steps without scaffolding. I'm pretty sure that in the regular data science lesson we give them a starter file that predefines `is-cat` and `is-young`?

- [ ] Does CODAP make box plots? I haven't been introduced to them through these lessons, but I'm seeing a question about them on Displaying Data.
- [ ] Noting that I'm pretty sure this is the first time since the Data Cycle lesson that the CODAP lessons have referenced it.

**Comment by flannery-denny** [comment]
@schanzer @retabak Done reading through these materials. Lmk if you have questions or need another read.

**Comment by retabak** [comment]
@schanzer - re: "I wonder if it this pathway shouldn't use some form of the "Dataset Exploration" paper as a scaffold, encouraging students to generate a finished product based on the work they do in CODAP. I found myself wishing I had some place to put all the results from my transformer work!"

I like this idea too! But taking it on felt a bit ambitious. Happy to play around with this idea but would like to chat with you about it first. Or maybe it's something that feels more appropriate to integrate down the road? Let's discuss.

**Comment by retabak** [comment]
updating this to note to myself:
- the exploration paper will be a "stub"
- the exploration paper will just use the animals dataset
