### ISSUE TITLE
Plan for citing image sources

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1058]
Boostrap materials have historically not included many images. 

We have protocol for citing sources for:
- images used for posters in a box to the right of the image
- dataset sources in the README tabe of the googlesheet

The social studies materials are moving us into new territory as they include many images of maps, artifacts, etc. 

- [x] It seems we should be citing them. I am not sure what the best way to do that is. Should we have another optional descriptor in the @image directive for "source:" that would get listed beneath or to the right of an image?
- [x] I am also not sure how to find the sources for Nancy's images.

As an example, we are using a map from page 2 of [this document](https://drive.google.com/file/d/1DESkogOiC5vS-7Y0gd-uxTdms117siaf/view?usp=sharing).  Its source is probably attributed in the bibliography referenced on page 30, but the link doesn't work, however, so I can't see where it actually comes from.

**Comment by schanzer** [comment]
@ds26gte Adding an optional argument to the @image directive makes a lot of sense here.
@kfisler as for the sources of the existing images - do you think we could just ask Nancy directly?

**Comment by ds26gte** [comment]
Pushed a solution. Note: @image already takes four arguments, only the first of which -- the image file -- is mandatory. The second argument is the alt text; the third is the width; and the fourth is the height. When the new fifth argument is given, it is considered to be the image source credit text. I've rendered it as
```
<span class="image-with-source">
   image
  <span class="image-source"> image source credit text </span>
</span>
```
Please set up appropriate CSS in shared.css for the classes `.image-with-source` and `.image-source` so that the text is glued on to the image the way you want.

**Comment by kfisler** [comment]
I tried emailing a followup on this thread, but it appears to not have gone through. I emailed Nancy to ask about the image sources.  She is wrapping up several weeks in Germany this week, flying back to the US around Thursday, so she might reply slower than usual.

I agree we should be citing the sources.

**Comment by schanzer** [comment]
@ds26gte that HTML doesn't quite give us what we want (difficult to style), and there are semantic elements we should be using instead. Can you implement the following?

```
<figure class="image-with-source">
    <span class="image">
        <img src="URL" alt="AltText" width="w" height="w">
    </span>
    <a href="URL" class="gdrive-only"><span class="big">🖼</span>Show image</a>
    <figcaption>Caption text</figcaption>
</figure>
```

We can use most of this markup _all the time_, and hide the `figcaption` with CSS if the caption is empty. OR, you can have the build script create the `figcaption` only if there's a source.

Relatedly: do we really need the span around the `img` tag?

**Comment by ds26gte** [comment]
That's not our span (if you mean the `<span class="image">`.  It's from Asciidoctor.

**Comment by schanzer** [comment]
@ds26gte no worries. In that case, can we use the markup I wrote in the comment?

**Comment by ds26gte** [comment]
In my recent push, I elected to leave out the `<figure>` if there is no caption supplied.

**Comment by schanzer** [comment]
@ds26gte 
Can you leave out the caption element instead? I'd like to keep the HTML as consistent as possible, so that the CSS stays clean as well

**Comment by ds26gte** [comment]
The browser doesn't like `<figure>` enclosed in a `<span class="right">`, which is why it's taking bogus correction measures to close off the `<span>` before the `<figure>` and thereby ruining the intended alignment. I've added some postprocessing in the build script to discard the `<span>` and include the alignment info in a `style` attribute of the `<figure>`.

**Comment by schanzer** [comment]
@ds26gte that doesn't sound right at all. There's nothing to suggest that this a `figure` can't be enclosed in a `span`. I think something broke when you added the figure tag, which caused invalid HTML to be generated.

**Comment by ds26gte** [comment]
`figure` is an instance of _flow content_, like `div`, `p`.  

`span` is used to surround _phrasing content_, not _flow content_. (In proglang terms, flow content is roughly analogous to statements, and phrasing content to expressions.)

I too wish everything were expression-oriented as in Scheme, so that everything can surround everything, but that's not the HTML way.

If you violate this principle, browsers will show _something_ (since they are designed to tolerate all kinds of invalid HTML), but it won't be what's intended.

**Comment by schanzer** [comment]
@ds26gte Spans _can_ contain figures. See [this jsfiddle](https://jsfiddle.net/gn1uke8b/), which mimics the issue and has no problems.

The issue here is the enclosing `p` tag. We have a number of CSS headaches related to asciidoc mandating these tags inside every `<div class="paragraph">`. This isn't fixable without post-processing, is it?

**Comment by kfisler** [comment]
We'll have to ask Nancy about the image sources. I checked her master
slidedeck, and don't see them. Will email her now with CC to Flannery and
Emmanuel.
