### ISSUE TITLE
suggest that alignments page not list all language versions of a lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1068]
[https://www.bootstrapworld.org/materials/fall2022/en-us/Alignments.shtml](https://www.bootstrapworld.org/materials/fall2022/en-us/Alignments.shtml)

Currently if a lesson exists in 3 languages it gets listed 3 times as being aligned with a standard. That makes for a lot of visual clutter and is particularly confusing when the lesson links don't have a language specified. I suggest only linking to one version of the lesson, priority pyret, but reactive lessons won't get caught in this so it'll have to be flexible. When a lesson exists in more than one language, teachers can click to wescheme or codap from the top of those lesson plans.

![Screen Shot 2022-07-29 at 8 33 33 AM](https://user-images.githubusercontent.com/66691020/181772514-ebc19566-40fb-42c2-af2a-d8c3e172d2c4.png)

![Screen Shot 2022-07-29 at 8 42 19 AM](https://user-images.githubusercontent.com/66691020/181773062-2c41348c-7e00-43d6-a87d-498af13291bd.png)

**Comment by schanzer** [comment]
@ds26gte I'm inclined to agree with Flannery here, especially as we are now about to add "spreadsheets" to the mix as essentially a proglang. Either we need to do some serious re-thinking of how we tag lessons with `proglang` (I could see something less static being valuable, allowing us to have only ONE copy of a lesson if it's totally unplugged), or we need a bandaid for now. I think the bandaid makes the most sense, since the architecting of a major re-tagging requires more information than we have right now.

I propose a simple JS popup, so that clicking any lesson brings up a modal that asks the user to select which tool they'd like to use `lessonN` with. We could show tool logos on the modal, and eventually add a link to a page that dissects each tool and explains the pros and cons.

On your end, implementing this would be mean removing language-doubles from this list, then calling out to a stub function which I will then write.
