### ISSUE TITLE
bug: code for DS expanded pyret contracts showing up wonky in lesson plans on web

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1071]
In the box plot lesson, the code in this strategy box
```
[.strategy-box, cols="1", grid="none", stripes="none"]
|===
a|
@span{.title}{Modified Box Plots}
More Statistics- or Math-oriented classes will also be familiar with __modified box plots__ (@link{https://www.youtube.com/watch?v=Cm_852R8JPw, video explanation}), which remove outliers from the box-and-whisker and draw them as asterisks outside of the plot. Modified box plots are also available in Bootstrap:Data Science, using the following contract:

`modified-box-plot :: (t::Table, col::String) -> Image`
|===
```
looks like this on the web

![Screen Shot 2022-07-30 at 8 10 43 PM](https://user-images.githubusercontent.com/66691020/182005402-f06ddab9-e928-492e-9b7f-897210b19484.png)

Here's another instance from the scatterplot lesson of code:

`scatter-plot :: (t::Table, ls::String, xs::String, ys::String)`

showing up wonky on the web
![Screen Shot 2022-07-30 at 8 47 17 PM](https://user-images.githubusercontent.com/66691020/182006192-b4bb068f-28e1-404a-80ee-0dfb87a64b73.png)

and another from the same lesson plan
![Screen Shot 2022-07-30 at 8 50 24 PM](https://user-images.githubusercontent.com/66691020/182006247-28fc5e81-51c4-4234-b6cf-e98b2eae1828.png)

**Comment by schanzer** [comment]
@ds26gte I've tried every trick I know to specify that this table is a nested asciidoc, including `cols="1a"` and `a|` for the cell itself. Is there something else I'm missing here?

**Comment by ds26gte** [comment]
Unfortunately, this is a place where Asciidoctor is really greedily squeezing on how much it can interpret every last bit of ascii substring in the text. It's viewing the `::` in mid-line as identifying a definition list.

I've replaced the `::` in the offending lesson plans with `{two-colons}`.  I'll keep my eyes peeled for more. It's a very rare situation, but you managed to trip it because I guess you are power users.

**Comment by ds26gte** [comment]
BTW, in many other places, you were using `@show{(contact ...)}`. This doesn't have the problem, because not only does it modify the contract to suit the prevailing proglang, it also ensures there are no troublesome raw `::`s floating around. I guess you were using raw AsciiDoc here because these are single-proglang (only Pyret) lessons?

**Comment by schanzer** [comment]
Yes, that's exactly right. Thanks for the reminder about two-colons!

**Comment by schanzer** [comment]
@ds26gte does the contract directive support expanded contracts, like this one?

**Comment by ds26gte** [comment]
What is the expanded part? If it doesn't already support, we can fix it

**Comment by ds26gte** [comment]
Ah, the dummy variables before some arg types. Do we also need to accommodate function types for the arguments?
