### ISSUE TITLE
solutions for rocket-height challenges

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1084]
As I work through the instruction box audit, I've been providing solutions to questions posed. I _could_ figure out all of the solutions to the rocket height challenges, but it would most definitely take me quite a bit of time. @flannery-denny or @schanzer - can you take this on? I think it would be useful to teachers to have these solutions provided. (If they happen to be provided elsewhere, we ought to indicate that.... but I don't think they are?)

https://bootstrapworld.org/materials/fall2022/en-us/lessons/functions-dr/index.shtml?pathway=algebra-pyret

<img width="316" alt="image" src="https://user-images.githubusercontent.com/87144723/182937876-1f7be898-3b62-425a-b72e-fb2a2619ee3e.png">

**Comment by schanzer** [comment]
@retabak given that these lesson plans are public, are you sure it's a good idea to provide every solution to every question in the lesson plans?

In this instance, I would say no. I suspect there are others.

**Comment by flannery-denny** [comment]
turn this into an @opt-printable so that teachers can see @ifsoln

**Comment by retabak** [comment]
Agreed with this solution! 
I think solutions are needed.

**Comment by flannery-denny** [comment]
@schanzer I pushed a draft. You may have more elegant solutions to some. The missing solution I only know how to do in wescheme and assume will take you less time to sort out in pyret. Once it's polished, please add an @opt-printable-exercise link to it from the challenge box in the lesson plan.

**Comment by flannery-denny** [comment]
try num-exp

**Comment by schanzer** [comment]
@flannery-denny pushed!

**Comment by flannery-denny** [comment]
@schanzer 
I’m looking at your rocket-height solutions. 

- I was using _seconds_ because that's what the starter file uses. 
- Your solutions all use _s_.  

Please decide whether you'd rather use seconds or s and align the files.

There are also a few solutions that don't match the prompt.

5.  Can you make the rocket blast off and then land again?

This is a parabola with a negative coefficient:  ℎ𝑒𝑖𝑔ℎ𝑡(𝑠)=−7𝑠2. Adding a constant pushes the graph up above y = 0.

The provided functions gives us this:
![Screen Shot 2022-08-22 at 1 39 16 PM](https://user-images.githubusercontent.com/66691020/185995151-37c7c8a9-3f81-4981-95d7-a97b9c24c8dc.png)

Adding a constant? ℎ𝑒𝑖𝑔ℎ𝑡(𝑠)=−7𝑠2 + 10?
![Screen Shot 2022-08-22 at 1 51 20 PM](https://user-images.githubusercontent.com/66691020/185996824-f2861157-4323-4db4-8a8b-34d5aca03efe.png)

**Side note: why use the 7?**

I would expect a graph that looks like this from the prompt
![Screen Shot 2022-08-22 at 1 40 01 PM](https://user-images.githubusercontent.com/66691020/185995323-118907e3-2ca3-4998-ab99-f2b673ba46bc.png)

which I generated using `rocket-height(seconds): seconds * (50 -seconds)`

6. Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land?

See previous solution, with a constant of 1000: ℎ𝑒𝑖𝑔ℎ𝑡(𝑠)=1000+−7𝑠2
![Screen Shot 2022-08-22 at 1 33 48 PM](https://user-images.githubusercontent.com/66691020/185994098-8d8c736c-265e-4163-b8b2-d492d837ab3d.png)
The graph that results from this function starts at 1000. It doesn't blast off and reach a height of 1000.

**Comment by retabak** [comment]
Just chiming in to say I'm really happy we're offering solutions! Definitely something that is needed.

**Comment by schanzer** [comment]
@flannery-denny thanks for catching those -- I've uploaded a fix, which includes slightly-better formatting. Close if you're happy?

**Comment by flannery-denny** [comment]
@schanzer I'm not seeing any new commits here. push?

**Comment by flannery-denny** [comment]
Would it be possible to have these numbers show up as decimals. Fractions like 4418/5 are kind of ridiculous
![Screen Shot 2022-08-31 at 10 26 06 AM](https://user-images.githubusercontent.com/66691020/187703270-313c626d-0c5b-48b4-beec-06fe8eeadeef.png)

**Comment by schanzer** [comment]
@flannery-denny ooooh, this exposed a number of assumptions in our rocket teachpack that break down in the presence of roughnums. Thanks for catching this!

I've just published an updated Algebra-Library. Shift-refresh and try them out?

**Comment by flannery-denny** [comment]
@schanzer That got rid of the errors. Now the axis label at the top is off the screen.
![Screen Shot 2022-08-31 at 11 22 13 AM](https://user-images.githubusercontent.com/66691020/187716527-74413574-c93a-4cbf-b48c-dc627676b225.png)

**Comment by schanzer** [comment]
@flannery-denny try now?
