### ISSUE TITLE
grouped samples - need more scaffolding?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1096]
8/30 - fixed for Pyret. Needs to be fixed for CODAP as well
----------------------------------
Another concern from @flannery-denny that pertains to the Pyret pathway, not just CODAP:

---
Below is from the "Investigate" section of Grouped Samples in the grouped-samples (CODAP) lesson.
_A “kitten” is an animal who is a cat and who is young. How would you define a table of just kittens?

Turn to [Grouped Samples from the Animals Dataset](https://github.com/bootstrapworld/lessons/grouped-samples-codap/pages/samples-from-animals-dataset.html), and see what sequence of Transformers will compute whether or not an animal is a kitten.

Can you fill in the function notation for the other grouped samples?

Make a bar chart showing the distribution of sex in the kittens subset ._

As far as I can tell, in order to make the bar chart in question I would need to build the columns is-young and is-cat before I can filter for filter-is-young(filter-is-cat(animals-table))

Maybe I'm missing something, but that feels like a lot of steps without scaffolding. I'm pretty sure that in the regular data science lesson we give them a starter file that predefines is-cat and is-young?

---

There is no starter file in the Pyret lesson. Wondering if we should add something (in CODAP and Pyret)? It does seem like a lot of directions for kids to follow without guidance / structure.

**Comment by flannery-denny** [comment]
@schanzer I think in pyret the simplest scaffolding for this lesson would be to have a starter file with the functions used on the workbook page predefined. Feel like we used to have one… but it currently links to the generic animals starter file…

**Comment by schanzer** [comment]
@retabak let's use our pedagogy to answer this question:
**1) Which rows do we care about?** We need rows for cats that are young, so let's assume under the age of 2
**2) Which columns do we need?** sex. That's all. _Nobody needs to make new columns for anything._ Before reading on, please think about this and write back if you disagree.

So we'd make a filter function/transformer for cats, and another for animals under 2. OR we could make one that checks for both, but we generally try to steer kids away from that. Applying those filters gives us a new table, and we just make a bar chart from that table.

@flannery-denny I don't think we had a file that included all of these. The closest we had was the [Row Functions Starter File](https://code.pyret.org/editor#share=1-YuAea2oTVZcEyUNvEb-cg5qIB6n5V7n). We have two options:

- Make a starter file just for this lesson
- Make the "type it in and try it out" part optional, since it would also require students to define those functions.

I'm leaning towards the first. Agreed?

**Comment by retabak** [comment]
@schanzer - I agree with this! 

I guess the issue then would be, do kids need more scaffolding in creating these two particular Transformers? I'm leaning toward no.

**Comment by schanzer** [comment]
@retabak  To make filter transformers? No.

**Comment by flannery-denny** [comment]
@schanzer I vote for a new starter file

**Comment by schanzer** [comment]
@flannery-denny and @retabak I've just pushed a commit to address this. Let me know what you think, or close if you're satisfied

**Comment by flannery-denny** [comment]
@schanzer I think that the starter file will be helpful... and it's super long! I know that you have often pushed back on me about including the full contract and examples in my starter files because they aren't always serving the lesson goals. I wonder if this starter file could be pared back to just the definitions?

**Comment by schanzer** [comment]
@flannery-denny thanks for the reminder. Fixed. If you're happy with the lesson edits as well, feel free to close.

**Comment by retabak** [comment]
Just took a peek. This looks great! Sort of can't believe it wasn't there before now that I'm seeing it.

**Comment by flannery-denny** [comment]
@schanzer looks much better! Now for you and @retabak to figure out how to address the issue in CODAP...

**Comment by retabak** [comment]
I think this is a non-issue in CODAP, as highlighted by @schanzer above? Gonna close this.
