### ISSUE TITLE
BSA:DefiningValues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#11]
- [x] Lesson summary isn't formatted
- [x] No `put-image`? Without it, how can students be expected to make flags?

**Comment by BootstrapJen** [comment]
re: `put-image`: The flags document I made (which I now realize is not linked) groups flags into categories based on what functions are needed.  Since many flags can be made without put-image, it isn't introduced in the game pathway, as the game can be completed without any knowledge of put-image.  (There could and may be an extension activity added for this, however.)
