### ISSUE TITLE
Pathway Narrative section directives

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1113]
= Bootstrap:XYZ

[.logo]
@image{images/Logo.png, Bootstrap:XYZ}

Some text

@pathway-lessons
-- title and list of all the lesson for this pathway

@workbooks
-- title, boilerplate text, and link to workbook purchase

@other-resources
-- title and boilerplate for Teacher Resources page, glossary links

**Comment by flannery-denny** [comment]
@ds26gte I've already entered into the world where I have more uses for the `@pathway-lesson` directive. Lmk when it's ready, please.

**Comment by flannery-denny** [comment]
@ds26gte `[.logo]` and `@pathway-lessons` work exactly as I would expect them to in the pathway `Maya`. This is all that I actually want to have work for this pathway.

But, for the sake of giving feedback, I added `@workbooks` and `@other-resources`.

`other-resources` should include the following title and text, just like it appears on the Algebra and DS pathway narratives

> Other Resources
> Of course, there’s more to a curriculum than software and lesson plans! We also provide a number of resources to educators, including standards alignment, a complete student workbook, an answer key for the programming exercises and a forum where they can ask questions and share ideas.

I'm also getting a lot of broken links.  Not sure if it's because I'm still in progress here or because there are bugs.
- the workbook link is broken
- `glossary` comes up totally blank with no heading at all
- `bilingual-glossary` loads with all words, even though they have nothing to do with this pathway
- `standards alignment` (there aren't any) and `workbook` (there should be one?) say _your file couldn't be accessed_ 
- `teacher only resources` loads with no content other than the google drive symbol.

**Comment by ds26gte** [comment]
Workbook link is broken only because there is no entry for it yet (for this course) in `course-specifics.rkt`.

**Comment by flannery-denny** [comment]
@schanzer did a new test on my `curriculum-review` folder and the teacher resources page comes up normal size over there. one weird thing (not related to Dorai's work) is that with the collapsible headers the printables for classroom walls section looks empty unless you mouse over it because it doesn't prereveal bulleted content...

**Comment by flannery-denny** [comment]
@ds26gte Every time I `./build-pathway maya --proglang spreadsheets` the landing page builds with all of the components I don't want, unless I `./build-pathway maya --proglang spreadsheets -F`, in which case it uses the custom pathway narrative.

**Comment by flannery-denny** [comment]
@schanzer On the `maya` branch I am still getting builds where some pages appear standard size
![Screen Shot 2022-09-08 at 3 28 05 PM](https://user-images.githubusercontent.com/66691020/189209434-975d201b-b8e8-4be5-81ef-994aba1eadae.png)

and some pages appear miniature
![Screen Shot 2022-09-08 at 3 27 38 PM](https://user-images.githubusercontent.com/66691020/189209512-ffc459a0-f603-43ae-8f5b-e61263de298d.png)

**Comment by schanzer** [comment]
@flannery-denny I know this is a dumb question, but just in case: have you checked your zoom level? Browsers often cache that, so if you've ever zoomed out or in on a page, that could be the culprit

**Comment by flannery-denny** [comment]
@ds26gte I’ve updated the `__sample` pathway lesson order on my machine to include the following lessons:
```
bar-and-pie-charts
custom-scatter-plots
ds-intro
flags
functions-dr
```
and I've updated the custom narrative for the sample pathway so that it makes use of the directives. Looks to me like they're all working.
