### ISSUE TITLE
live on web - no room to draw circles!

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1127]
The worksheets in the order of ops lesson aren't showing as much space for COEs as they ought to / used to:

https://bootstrapworld.org/materials/fall2022/en-us/lessons/order-of-operations/pages/arith-to-coe.html

<img width="699" alt="image" src="https://user-images.githubusercontent.com/87144723/189204146-cf539cc2-5675-40a1-920e-68081e5868c7.png">

**Comment by schanzer** [comment]
@retabak this is seriously disturbing. This is now the _second_ time that a CSS fix that worked at one point in time has magically stopped working. @ds26gte has the overall DOM structure of wb pages changed in any meaningful way since June? That's the last time I fixed this, in order to reprint workbooks.

**Comment by schanzer** [comment]
Closing because this specific issue is "fixed", but I'm certain there are other places where tables have suddenly shrunk. For now I'm going to keep playing whack-a-mole, until we find the real source of the issue.
