### ISSUE TITLE
live on web - buggy link

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1133]
https://bootstrapworld.org/materials/fall2022/en-us/lessons/data-collection/pages/survey-design.html
I vaguely remember this happened once before?

![image](https://user-images.githubusercontent.com/87144723/190540444-4d608d27-d0a8-497e-9928-48dd7e820ade.png)

**Comment by schanzer** [comment]
@ds26gte I can't figure out why one of the links on this page works, but the other doesn't. Can you take a look?

**Comment by ds26gte** [comment]
Artifact of optional pages being necessarily processed in alphabetical order (no other natural order suggests itself for optionals). survey-design.adoc was referring to survey-brainstorm.adoc and survey-hacking.adoc. It got the title for the former because b < d, but not the latter because h > d. (The same survey-design.adoc in solution-pages/ got everything correct, because solution-pages/* are processed after all the pages/* are.)

Pushed fix whereby the title text is calculated via ad-hoc grep beforehand (and it can be updated when the file is processed by Racket, in case that produces a better title).

**Comment by ds26gte** [comment]
If you mean the `@lesson-link{project-research-paper}`, that lesson is not part of the `data-science` (or _any_!) pathway, so it is not part of the distribution and there is nothing to link to.  Is this the sort of page you want in `shared/langs/en-us/docroot/...` somewhere?

**Comment by schanzer** [comment]
No - it's definitely a lesson. Why is there a restriction that lessons used with this directive be part of a pathway? Doesn't this reduce the value of your other proposed solution, that all projects actually be lessons-that-aren't-really-lessons?

`@lesson-link` should allow for links to lesson plans, regardless of whether they are in a pathway or not.

**Comment by ds26gte** [comment]
I used to copy all the lessons over to the distribution and "make" them. @flannery-denny said it was taking too much time when all she wanted was to make was one course. So I made it be "on demand".

**Comment by schanzer** [comment]
@ds26gte got it. Thanks!

**Comment by retabak** [comment]
Still seeing the same behavior!? Check it out here: https://bootstrapworld.org/materials/fall2022/en-us/lessons/data-collection/pages/survey-design.html

![image](https://user-images.githubusercontent.com/87144723/191786511-060619f0-b4bc-4e17-b285-0568107938c3.png)

**Comment by schanzer** [comment]
@retabak have you tried reloading with the shift key down?

**Comment by retabak** [comment]
okay, I legit thought I tried that.... but I just tried it again and now it looks good!
