### ISSUE TITLE
early math lessons and worksheets!

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1170]
translating-words-math
- [x] lesson asciidoc
- [x] worksheets

computation-transformations
- [x] lesson asciidoc
- [x] worksheets

commutative-property
- [x] lesson asciidoc
- [x] worksheets

associative-property
- [x] lesson asciidoc
- [x] worksheets

equivalence-and-laws
- [x] lesson asciidoc
- [x] worksheets

applying-properties **[I NEED TO FIGURE OUT WHAT'S GOING ON IN THIS LESSON]**
- [x] lesson asciidoc
- [x] worksheets

identity-property
- [x] lesson asciidoc
- [x] worksheets

distributive-property **[I NEED TO FIGURE OUT WHAT'S GOING ON IN THIS LESSON]**
- [x] lesson asciidoc
- [x] worksheets

absolute-value-and-opposites
- [x] lesson asciidoc
- [x] worksheets

absolute-value-and-opposites-more
- [x] lesson asciidoc
- [x] worksheets

evaluating-exponents
- [x] lesson asciidoc
- [x] worksheets

evaluating-expressions-1
- [x] lesson asciidoc
- [x] worksheets

evaluating-expressions-2
- [x] lesson asciidoc
- [x] worksheets

**Comment by retabak** [comment]
@schanzer - five lessons now exist as asciidocs! Think you could give them a look to see how they've evolved? I'm thinking that if you can offer me little bits of feedback periodically, that it will help me identify threads to pull through as I write the remaining lessons. 

I'm also hoping we can maybe meet sometime this week to discuss? I'm thinking about possibly adding in some fractions content and would like to chat about that.

**Comment by schanzer** [comment]
@retabak 

**translating-words-math**

- The prose a little wordy and overly informal. We can tighten that up later though, so don't worry.
- Why do the circles _need_ to have math symbols for coding? It's fine if teachers would rather use normal symbols. I would walk back the language a bit, and explain why _we_ chose to use one set of symbols but not mandate that _they_ use them too
- I really like these activities! Adding the C cards is beautiful
- I _love_ the idea of having cards for both 5+8 and 8+5!! Students will naturally pair them up correctly, and justifying that decision will reveal that they intuitively know they're not the same
- "Here are some common challenges..." --> why not put this under a "Common Misconceptions" header?
- Is it important that students know the word "ambiguity", and its definition?

**computation-transformations**

- You can't have a circle of evaluation with no function! 
![image](https://user-images.githubusercontent.com/77126/196822864-8f4680c7-437d-417c-8587-a83fbea30e04.png)
- This feels nicely straightforward. No real notes. :)
- oooooh, I LOVE the way you're building on the categories kids create here in the next lesson. Very clever. But there's a risk -- what if the categories kids come up with aren't useful? How can you structure this activity so that kids come to some of the categories you want?

**commutative-property**

- I like the debate between Claire and Walker. But I wonder: why do we need to tell them how the story ends (with the teacher giving Walker full credit?)
- I don't love the overview text "...to see if they have been manipulated in a valid way". It's way more complicated than necessary, and obscures the bigger truth here. When you say "valid", you mean _equivalent!_ It's about shifting from one equivalent representation to another, until you find the answer. _The truth is there -- they just need to shave away all the junk to find it_

**associative-property**

- I like where you're going here, but the example you used in "mental math" isn't working. You need something where reshuffling makes things _radically_ easier.

**equivalence-and-laws**

- This is cool! I like how this is shaping up. I wonder if there's room here to do some kind of sorting activity with examples that are always true, sometimes true, or never true....?
