### ISSUE TITLE
nitpicky dataset issues

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1174]
For a grad school project, I'm looking a lot at our datasets! 
Wow! They're awesome! Not seeing issues at all. I'm sure SO much time went into compiling these.

One question: a few of the READMEs say "report any issues to jen@bootstrapworld.org"; Want me to change those to schanzer@bootstrapworld.org as I notice them?  Or flannery@bootstrapworld.org? @flannery-denny @schanzer 

And, the ["music" spreadsheet](https://docs.google.com/spreadsheets/d/13OFoNwVJZiKr1fWjKO912lr2RXxUiCakNJmeZT4JzHE/edit#gid=1940004783) has some weirdness. The name on the tab with the pertinent spreadsheet says "2019." The README says "published in 2011," but "current as of December 13, 2018." The title of the file is "Music - fall 2021." So many dates! What's going on? 

If I see anything else, I'll make a note here.

**Comment by schanzer** [comment]
@retabak thanks for digging into these!

Yeah, change them to my address. As for the dates - the dataset was originally published to the web (not by us!) in 2011. Jen copied it and cleaned it up in December 2018, and _we_ released it in 2019. Flannery made some additional improvements in 2021, but we didn't update the tab name because those improvements did not use data newer than Dec 2018. 

I've updated the README to make this more clear. We _really_ need to develop some datasheets for these datasets!

What's your grad school project all about?
