### ISSUE TITLE
Fall 2023 Data Science restructuring

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1192]
Make `fall2023` branch. From there make a `ds-restructure` branch from within it. So that pull requests will for `ds-restructure` will go to `fall2023`
- [x] #1206
- [x] #1205
- [x] #1209
- [x] find the quickest pathway to scatterplots (simpledatatypes, contracts, scatterplots?) _In 2022 the prereqs are as follows and the lesson definitely refers to the other two lessons._
![Screen Shot 2022-11-11 at 9 45 53 AM](https://user-images.githubusercontent.com/66691020/201375693-59152172-9a84-4df1-9d76-655b95ad5818.png) 
**Proposal: Intro to DS, Simple Datatypes, New DS contracts lesson, Scatterplots**
- [x] strip down scatterplot lesson to have no reliance on DR **FD - This already happened! Scatterplots come before the DR in 2022**
- [x] same with correlations **FD - DR is listed as a prereq for correlations, but the lesson plan itself doesn't refer to the DR at all**
![Screen Shot 2022-11-11 at 10 55 02 AM](https://user-images.githubusercontent.com/66691020/201390628-3318c3a4-1d78-4fb7-8c1a-1b794516dd25.png)
- [x] same with linear regression **FD - As far as I can tell, this lesson would benefit from prior engagement with linearity, but really only depends on scatterplots, correlations and a cursory understanding of the pyret editor. I have no idea how it ended up with the list of prerequisites in the table.**

**Comment by flannery-denny** [comment]
Notes:
- somehow this lesson no longer uses the words dependent or independent variable at all. Nor are they included anywhere in our glossary. I remember us having a huge discussion about this... and the importance of helping teachers connect to what they know. At the very least, we need to make a note for math teachers about why we are choosing not to use these words!
-

**Comment by flannery-denny** [comment]
@schanzer Here are my preliminary notes and questions about the current version of the scatterplot lesson. Any thoughts would be useful as I turn my attention to thinking about which lessons have to come before it. Thanks!
- somehow this lesson no longer uses the words dependent or independent variable at all. Nor are they included anywhere in our glossary. I remember us having a huge discussion about this... and the importance of helping teachers connect to what they know. At the very least, we need to make a note for math teachers about why we are choosing not to use these words!
- Is this necessary backward reference necessary? 

> Think back to our discussion of random sampling and statistical inference. In this case, the null hypothesis is that there is no relationship between these two columns. The image on the right shows a collection of points, with no pattern.

- Let's make it clearer which scatterplot this is referring to. If it's referring to the scatterplot that they just generated in pyret, we ought to be providing scaffolding for teachers on what responses to expect. 

> "What pattern do you see in your scatter plot? Are there any points that seem unusual? Why?

- Do we want to expect that everyone has learned about all of these displays on their way to the scatterplots lesson?

> Synthesize
> We’ve got a lot of tools in our toolkit that help us think about an entire column of a dataset:
> 
> We have ways to find measures of center and spread for a given quantitative column.
> 
> We have visualizations that let us see the shape of values in a quantitative column.
> 
> We have visualizations that let us see frequencies or percentages in a categorical column.
> 
> Now we also have a tool that lets us think about two columns at the same time!

- suggest we swap the order of this text

> These numbers and scatter plot both come from the same datasets (you’ll learn more about those numbers in later lessons!). The patterns in the scatter plot vary wildly, but the numbers that summarize the dataset barely change at all!
> 
> It’s not just about the numbers!
> 
> An animation, showing random point clouds shifting into circular patterns, all with means and standard deviations that are identical to the second decimal
> 
> Data Scientists and Statisticians use their eyes all the time. Sometimes there’s a pattern hiding in the data, which can’t be seen just by focusing on numbers and measures. Until we really look at the shape of the data, we aren’t seeing the whole picture. (Optional: this animation is from Autodesk, which has an amazing page showing off how similar numbers can be generated from radically different scatterplots. If time allows, have students explore some of the visualizations on the [Autodesk website (Autodesk)](https://www.autodesk.com/research/publications/same-stats-different-graphs)!)

- I know that the point of the work we're doing for Massachusetts is ultimately to work with real world datasets... but are you sure we can keep this section of the scatterplot lesson plan?

> Your Own Analysis
> Students apply what they’ve learned to their own dataset.

Also, this is a spot where I would have assumed the second teaching dataset would be referenced. Curious why it isn't...

**Comment by schanzer** [comment]
@flannery-denny 

1. Yes, we talked about the importance of using "explanatory" and "response". This deserves a pedagogy box, which explains that "dependent" and "independent" are inherently misleading _because they imply correlation_. In many cases, there's no correlation and at all and **both** are independent! And even where there is a correlation, the y-axis always has some degree of independence.
2. Definitely ok to remove the backwards reference, but I wouldn't take out the paragraph entirely. Maybe just "If we pick 10 points at random from a scatterplot with no correlation the chances of them clustering around a line are very unlikely - but not impossible! If we pick 100 points the chances are even _less_  likely, and they keep dropping the more points we choose.  If there's a 1-in-a-million chance of picking 100 points that cluster around a line from a sample with **no correlation**, then we can be pretty confidence that there must be a correlation after all!"
3. Agreed - providing guidance around responses is an excellent idea.
4. Great question - I think we can remove the sequential wording (e.g. - "we've got a lot of tools", "now we...") and just state that there are many ways to visualize or reason about single columns of data, but that scatter plots are special because they let us see _relationships between two columns_. And I'm happy with your swap.
5. I think Rachel added this wording, because I rarely make forward references in my prose. I think you should remove it entirely.
6. I think it's safe to keep the reference to students' own datasets. There's a reasonable chance students will be able to choose their own datasets in MA
7. I believe you added all of the references to the teaching dataset in your work on https://github.com/bootstrapworld/curriculum/issues/889. You may have had a good reason for leaving this lesson out at the time, but I agree that it would be better to refer to it here.
8. Not sure I understand. What does it mean to resolve a box?

**Comment by flannery-denny** [comment]
@schanzer how do I search the repository for how we used independent and dependent variable in the fall 2021 release? Also, noting that those vocabulary words appear in the following standards and reactive lessons.
![Screen Shot 2022-11-14 at 1 59 13 PM](https://user-images.githubusercontent.com/66691020/201754272-7562bede-0105-4ed5-8bf1-369e6d39aa5a.png)

**Comment by flannery-denny** [comment]
The same question is asked twice in the lesson plan. Wondering if there should be a workbook page for engaging students with the starter file and the scatterplot they made during the investigate section and then have them circle back to it in the synthesize?

![Screen Shot 2022-11-14 at 3 04 53 PM](https://user-images.githubusercontent.com/66691020/201765264-c84db928-4770-4947-88de-30abf86fd921.png)

**Comment by flannery-denny** [comment]
Should we change every instance of this kind of reference

> Students apply what they’ve learned to their own dataset.

to say

> Students apply what they’ve learned to their own dataset or the @starter-file{food}

?

**Comment by flannery-denny** [comment]
**Things that jump out at me in the linear regression lesson:**
- "Let’s learn how to determine the strength of **data relationships**."?
- "predictor function a function which, given a value from one dataset, makes an educated guess at a related value in **a different dataset**"?
- Do we expect that Alg 2 will want to teach the algorithm behind linear regression?
- What do we want to do with references to the research paper?

> Fill in the Correlations portion of your [Research Paper](https://docs.google.com/document/d/1rSaR8dGEDtZz3NRVsvAjw_W50BiCNrM6zxID5hgkBY8/copy), using the scatter plots and linear regression plots they’ve constructed for their dataset and explaining what they show.


- This lesson feels all over the place! It's due for a major overhaul. I can't find the logic between which questions are in lesson instruction boxes and which aren't. My guess is that means it either needs more workbook pages or more lesson sections... and some of it should be cut.
