### ISSUE TITLE
Restructure Alignment Dictionaries

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1193]
**ES revised this to reflection changes from the 11/8 curriculum meeting**

- [x] Modify the structure of each alignment dictionary, shifting from `id -> description` to `id -> {description, lessons[]}`
- [x] Migrate all lesson alignments from standards-and-lessons.rkt into these dictionaries
- [x] Modify dependency-graph calculation and pathway-alignments generation to work with the new dictionaries
- [x] Move dictionaries from Racket lists to JSON objects
- [x] Merge and copy JSON dictionaries to `distribution/lib/` as part of the normal build process

-----------Original Comment---------
I cannot find a logic to the organization of the csta standards in this file and expect that lack of organization will lead to mistakes and duplicates if it hasn't already.

**Comment by flannery-denny** [comment]
@schanzer is this issue moot given today's conversation?

**Comment by ds26gte** [comment]
I'm reopening this issue as a placeholder for the suggestion we consensused on.

Instead of having a separate standards-and-lessons.rkt file that maps (groups of) standards to the the lessons implementing them, let's associate the lessons in the dictionaries themselves, so authors can see standard label, standard description, and the implementing lessons together and thereby maintain them easier.

Similarly, for textbooks and practices.

**Comment by schanzer** [comment]
...and in JSON 😉

**Comment by schanzer** [comment]
This is now completed on the js-alignment branch
