### ISSUE TITLE
CSS Glitches on functions-for-tables-and-displays

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1224]
- [x] If you want us to use second level headers on workbook pages, we need to fix the huge amount of vertical space that gets inserted above them in pdfs.
![Screen Shot 2022-12-09 at 9 23 18 AM](https://user-images.githubusercontent.com/66691020/206735473-ce925cd8-7c9e-4ece-a3aa-c40da694218d.png)

- [x] I also have no good explanation for why the font changes / gets squished for order on the last row of this screenshot. It's just like the other bullets in the asciidoc.

```
*Suppose we wanted to see the names of the animals in alphabetical order...*

The `sort` function takes in three pieces of information (the Domain):

* A table
* A column we want to sort the table by
* The order in which we want the column sorted

** Type `sort(animals-table, "Name", true)` in the Interactions Area and hit "Enter"

```

- [ ] #1226
![Screen Shot 2022-12-09 at 10 02 58 AM](https://user-images.githubusercontent.com/66691020/206742924-34f6dc1d-196f-4f27-ba99-5f3bc82b6170.png)

- [ ] When an author uses @fitbruby as an example (ie. all arguments are filled in), it does not need extra padding for students to be able to write on it.  (Pivoting to another format for the page where it didn't work.)

- [x] Here's another spacing inconsistency when I use second level headers (also not urgent - pivoting to another format)
![Screen Shot 2022-12-09 at 9 07 44 AM](https://user-images.githubusercontent.com/66691020/206732580-5cc53dd2-cb95-4b12-97f8-b1c0c3f7f7a5.png)
![Screen Shot 2022-12-09 at 9 07 57 AM](https://user-images.githubusercontent.com/66691020/206732585-f15749d7-fdc8-4516-a7f7-30bb61d19208.png)

**Comment by schanzer** [comment]
@flannery-denny thanks for tracking these!

By default, the second-level heads spread out to fill up the available vertical space. In most pages this is the right thing, but as you've pointed out sometimes it just leaves a yawning chasm of space! If you want to break the default behavior, there's a CSS rule to use. Easier to explain it in our next zoom meeting.

No idea why that line is squished. Does that happen reliably, even if you force build?

@ds26gte adding an `@star` directive makes a lot of sense, as long as it has the same  `class="autonum"`.

I disagree about making `@fitbruby` work differently depending on who's writing in the answer. We've worked for years to standardize the behavior of these elements -- I don't want to go in the opposite direction. If a page will break unless we use a different format, I think that means that page is either fundamentally broken or it shouldn't be trying to use `fitbruby` in the first place.

I'm not able to look into some of the examples here, since I can't find them in the repository. Where can I find the text behind these screenshots?

**Comment by flannery-denny** [comment]
@schanzer see above commit on the `functions-for-tables-and-displays` branch

**Comment by schanzer** [comment]
@flannery-denny I'm unable to reproduce either of the spacing issues you reported. Checking these off as glitches, but please feel free to make a separate issue about them if they persist across clean builds for you. I'm also retitling the issue, as there is no specific rule being proposed.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/77126/206859021-7675d807-b34f-41f7-b94b-61f4f17303f4.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/77126/206859041-42afb991-7e5c-4ece-8c55-c8601a7a33e5.png">
