### ISSUE TITLE
Implement better solution for evenly-spaced FillVerticalSpace table rows

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1238]
Fix pushed on 1/3 for single instance of problem (props-make-comp-easier in associative-property)

[a15b079](https://github.com/bootstrapworld/curriculum/commit/a15b0796689a59491b8193dfadfb075bf7fdddcf) CSS fix for evenly-spaced grid table rows. We might need to make this global

![image](https://user-images.githubusercontent.com/87144723/210417175-43d4010d-5bdf-4899-a911-f0f73d53e39f.png)

@retabak will log additional instances in this issue.

**Comment by schanzer** [comment]
@retabak I put a few hours into reading the CSS documentation and experimenting. It looks like we really have two distinct table modes:

1. "Size the rows proportionally to their contents"
2. "Make all the rows equal[*] height

There are CSS rules that accomplish one or the other, but they cannot be used together. If it turns out that we need both modes with high frequency, I could someday create a totally separate CSS class for the second one. But until then, you should just use the per-page rule that I used in the referenced commit.
