### ISSUE TITLE
Proposing new warning when coe run out of room

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1253]
<img width="781" alt="Screen Shot 2023-01-13 at 2 45 01 PM" src="https://user-images.githubusercontent.com/66691020/212777646-6e79535b-ba45-48ea-b69f-3c62be7c552c.png">
We introduce coe as being read from left to right. I don't think it serves students to end up with a number on the bottom of the circle. Suggest some sort of message that encourages authors to change layout (fewer columns / landscape orientation, etc.) when this happens.

**Comment by schanzer** [comment]
Because of the way, the web works, this is going to be incredibly difficult. I'm not 100% sure it's even possible.

I have to say, I think this will also generate a lot of false warnings. We got many circles evaluation, where it's important to have one in pot above the other (some of the more complex flags or function, composition examples).

I completely agree that there are many times where we don't want it to flow onto more than one line, but an automated warning system - if such a thing is even possible - may not be in our interests.

**Comment by retabak** [comment]
Also noting that when the font size issue (#1223) is resolved, I think most of these issues will go away? (In Early Math, I've confirmed that the Circles lay out correctly / horizontally in the printed version).

**Comment by schanzer** [comment]
We discussed the issue on 1/17, and decided to close because:

- As @retabak points out, this is MUCH less of an issue for printed books
- #1223 will improve matters substantially
- Getting console warnings is actually impossible. The only thing we can do is use some clever CSS to force circles that overflow to be as ugly and noticeable as possible, which would create _other_ problems for circles that we want to overflow.
