### ISSUE TITLE
Add a context for the playdough lesson that will justify ordering the bars in the histogram

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1357]

**Comment by schanzer** [comment]
@flannery-denny I'm not sure I understand this issue. We already provide context in the lesson for why histogram bars must be ordered. The playdough activity is about making a histogram, so that context still applies. Are you saying we need playdough-specific context?

**Comment by flannery-denny** [comment]
@schanzer I am saying that this playdough activity doesn't hit home for me. It feels like it was added because we were looking for more kinesthetic activities and playdough worked really well for another lesson, so the thought was we could use it here, too... but it feels disconnected and arbitrary. What do you think students will get out of this playdough activity that is richer than what they'd get out of the lesson without that? I am concerned that the answer is "nothing"... and, worse, that it might undermine the important point that we are trying to drive home about the fact that order matters. I am asking you to modify the directions in a way that convinces me that this kinesthetic activity is awesome and should stay in the lesson.

**Comment by schanzer** [comment]
@flannery-denny This kinesthetic activity **isn't** awesome, so convincing you isn't going to happen.

But what it _does_ is build up valuable kinesthetic experience that pays off when students get to box-plots. If we remove this activity entirely, it cuts the legs out from under the sibling activity later. I have to proposals to address this:

1. Move this activity into the box-plot lesson, so students FIRST make a histogram and THEN change it to a box plot. We can set up the numbers and ruler markings so that they are truly representing the same data in two ways.
2. We remove both activities.

I'm strongly in favor of the first, for obvious reasons. What do you think?

**Comment by flannery-denny** [comment]
@schanzer I love the second activity, so definitely wouldn't want to see it cut. While I'm not sure that this activity is necessary in order to do the other, I would agree that it probably would make a lot more sense back to back with the box plot activity... and perhaps enrich the second activity. For teachers, it would also mean only one day of playdough mess. Go for it!
