### ISSUE TITLE
Grade-level pathways

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1374]
- [x] 5th grade math @retabak
- [x] 6th grade math @retabak 
- [x] 7th grade math @flannery-denny 
- [x] 8th grade math @flannery-denny 
- [x] Algebra
- [x] Algebra 2
- [x] need to add new logos for these pathways to look right
- [x] audit prerequisities for these pathways and the lessons inside of them
- [x] DS prereqs for `measures-of-center`, `box-plots`, `histograms`, `histograms2` would require us to include things in the 7th grade pathway that we don't think belong. @schanzer Are these dependencies real?
- [ ] decide whether it makes sense to start 7th grade with DS or early math. FD leans toward DS.
- [x] decide about #1441

**Comment by flannery-denny** [comment]
@schanzer Assuming we're making delineations about what fits within a grade based on common core?

**Comment by schanzer** [comment]
@flannery-denny correct

**Comment by schanzer** [comment]
@flannery-denny and @retabak are these pathways done, modulo the graphics?

**Comment by flannery-denny** [comment]
theoretically. we put it on our next curriculum meeting agenda to discuss
them.

**Comment by flannery-denny** [comment]
5th grade thoughts:
- simple datatypes could be slightly modified to be more enticing for 5th grade teachers
- once we modify simple datatypes, let's add contracts and image functions to this pathway
- order of operations should have a fifth grade lesson

**Comment by flannery-denny** [comment]
@schanzer 
5th grade thoughts:
- we updated the simple datatypes lesson description to be more enticing for 5th grade teachers. please take a look at the wording.
- we think we should make a fifth grade friendly version of contracts and image functions to this pathway #574 
- order of operations should have a fifth grade lesson #574

**Comment by flannery-denny** [comment]
@schanzer 
6th grade thoughts:
- We should make a simplified version of contracts for tables and displays for 6th grade that just focuses on the displays - not functions like sort
- Measures of center and boxplots both use *summarizing columns in the animals table* and we should make versions of this that give code.

**Comment by flannery-denny** [comment]
@schanzer 7th grade thoughts:

- Thinking the same simplified versions of contracts, measures of center and box plots could be used for 6th & 7th grade.
- Add a 7th grade version of making game images with a game starterfile that stops at screenshot.
- does it make sense to start with early math or data science?

**Comment by flannery-denny** [comment]
@schanzer I'd like to revisit the [simple inequalities starter file](https://code.pyret.org/editor#share=1iTfgXFO_ODI8ucmReFxD_1T-RVanXNnc). 
We were hoping to make this lesson one that 6th graders could engage with (because that's where the relevant standards are) but its new iteration definitely requires an understanding of function notation that we don't expect 6th graders to have...

I'm also not into the T and F appearing on the number line nor the more muted versions of the dot colors and would love to know how that change came about. 

Removing the inequalities lesson from the sixth grade pathway for now. Adding it to the agenda for our next meeting.

**Comment by flannery-denny** [comment]
@schanzer @retabak and I met and updated grade level pathways such that they can work with existing lessons. Consolidating all questions and comments into one for you to respond to.

- [ ] we updated the simple datatypes lesson description to be more enticing for 5th grade teachers. please confirm the wording works for you.
- [ ] We've amended #574 to have a specific list of recommendations for how to make new versions of existing lessons so that they could be added to these pathways. Please take a look and convert whichever you think we're ready to prioritize into individual issues.
- [ ] We'd like to add all 3 inequalities lessons to the 6th grade pathway (where they fit in the standards) but I've removed them for now because I'd like to revisit the [simple inequalities starter file](https://code.pyret.org/editor#share=1iTfgXFO_ODI8ucmReFxD_1T-RVanXNnc) and see if we can figure out how to simplify it so that it doesn't require an abstract understanding of function notation that we don't expect 6th graders to have... _(I'm also not into the T and F appearing on the number line nor the more muted versions of the dot colors and would love to know how that change came about.)_ I've added this to the agenda for our next one-on-one.

Once lower level versions of lessons are made, we suggest adding the following to pathways (these suggestions have also been added to `lesson-order.txt` files) :
- **5th grade:** contracts, order of operations
- **6th grade**: contracts, flags, box plots, measures of center, histograms
- **7th grade**: contracts, measures of center, box plots, histograms, making game images

**Comment by retabak** [comment]
@flannery-denny - thanks for summarizing!

**Comment by schanzer** [comment]
@flannery-denny and @retabak new description works for me, and I've added replied to the other issue. 

As for the prereqs - what doesn't belong? They all seem to rely on just Simple Data Types and Contracts. Is it the ds-intro that's the problem?
