### ISSUE TITLE
Can links from solution-pages to other printable-exercises point to solution page versions of them?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1387]
As an example, I'm looking at the materials in `Exploring Quadratic Functions` in the Algebra 2 pathway. `Modeling Fuel Efficiency v Speed` points back to information recorded on  `Exploring the Fuel Efficiency Dataset`.

**Comment by schanzer** [comment]
Ooooh, I love this. YES!

**Comment by ds26gte** [comment]
Do you want `@printable-exercise{pages/something.adoc}` to be read as `@printable-exercise{solution-pages/something.adoc}` inside a solution page, or would it be enough to write `@printable-exercise{something.adoc}` and have it resolve to `pages/something.adoc` in a pages page, and `solution-pages/something.adoc` in a solution page?

The latter needs to be done. The former, your call.

**Comment by flannery-denny** [comment]
@ds26gte We have moved away from having separate `pages` and `solution-pages` folders as authors because it was extremely prone to humans forgetting to keep them in sync. Most pages make use of `@ifsoln`. So the request is for you to do some wizardry that turns the same `.adoc` into a `page` that links to `pages/something` as well as a `solution-page` that links to `solution-pages/something`. 

If that's unclear, let's zoom.

**Comment by ds26gte** [comment]
Yes, I get that. I am just discussing what kind of input format you'd like to specify this: If you can accept writing

`@printable-exercise{something.adoc}`

rather than 

`@printable-exercise{pages/something.adoc}`

I can have it convert to `pages/something.adoc` in a non-solution page and to `solution-pages/something.adoc` in a solution page. That may be enough, and indeed requires less typing on your part.

In this scenario, the three links 
```
1. @printable-exercise{something.adoc}
2. @printable-exercise{pages/something.adoc}
3. @printable-exercise{solution-pages/something.adoc}
```
all behave subtly differently, and you may may need that difference.

1 will become `pages/something.adoc` or `solution-pages/something.adoc` *depending on context*. 2 will *always * point to `pages/something.adoc` and 3 will *always* point to `solution-pages/something.adoc`.  (The fact that a repo lesson directory has no `solution-pages` has no bearing on this.)

If, however, you want to be able to write

`@printable-exercise{pages/something.adoc}`

and have the explicit `pages/` be changed to `solution-pages/` in a solutions page, I can do that too.

**Comment by flannery-denny** [comment]
@ds26gte 
I prefer writing `@printable-exercise{something.adoc}`

@schanzer tends to write `@printable-exercise{pages/something.adoc}`

I'm not sure whether that's 

- a holdover from before you did extra wizardry to make it unnecessary (I suspect this to be the case)
- because he knows of some instance when it's important to include `pages/` that neither you nor I are aware of.

The only thing justification that comes to mind for me is that perhaps `slides.md` files require us to use `pages/`?

Let's wait for him to be out of pd and have time to think about it.

**Comment by schanzer** [comment]
@ds26gte @flannery-denny yeah, this is a holdover habit. I agree with Dorai's proposal! For now, that means we need to remove all instances of `@printable-exercise{pages/XYZ}` and replace with `@printable-exercise{XYZ}` (ditto for opt-printable).

Let's do it.

**Comment by ds26gte** [comment]
The `pages/` needs to be dropped from the `@printable-exercise` argument only in workbook pages, and strangely, the only such page is the one quoted in this issue. I've changed it (in `alg2` branch).

Typically, `@printable-exercise` calls occur in lesson plans, which don't have a solution-mode version. Workbook pages, on the other hand, have two versions, non-solution and solution, and it makes sense to massage the `@printable-exercise` link there so that it shows up differently in the two versions.
