### ISSUE TITLE
Connect Filtering and Building to Animals Dataset? To their own Dataset?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1405]
@schanzer In trying to clean up the last synthesize section on Filtering and Building I wanted to ask a question like
- what columns might you want to add to your dataset?
- what filters might be interesting to apply to your dataset?

It sent me back to the lesson plan to look for a spot where they're already doing this and I'm not seeing it. Is this intentional?
Am I missing something? Or do you think it would make sense to add this kind of thinking in.

If so, I'm wondering if there's a good reason why we wouldn't want them to engage with a Design Recipe or Data Cycle?

The Composing Table Operations lesson that follows includes Design Recipe: is-dog/is-female and is-old/name-has-s. These seem like they're intended to be review rather than introducing something new.

In the Grouped Samples starter file in the lesson thereafter we give them the following:
```
# is-old :: (r :: Row) -> Boolean
# consumes a row and asks if age > 10
fun is-old(r): r["age"] > 10 end

# is-young :: (r :: Row) -> Boolean
# consumes a row and asks if age < 5
fun is-young(r): r["age"] < 5 end

# is-dog :: (r :: Row) -> Boolean
# consumes a row and asks if the species is "dog"
fun is-dog(r): r["species"] == "dog" end

# is-cat :: (r :: Row) -> Boolean
# consumes a row and asks if the species is "cat"
fun is-cat(r): r["species"] == "cat" end

# is-female :: (r :: Row) -> Boolean
# consumes a row and asks if the sex is "female"
fun is-female(r): r["sex"] == "female" end

# is-fixed :: (r :: Row) -> Boolean
# consumes a row and looks up the value in the fixed column
fun is-fixed(r): r["fixed"] end

# name-has-s :: (r :: Row) -> Boolean
# consumes a row and asks if the name contains "s"
fun name-has-s(r): string-contains(r["name"], "s") end
```
It seems that at the very least we should be providing design recipes for the other functions in this list as additional practice before they turn up in the grouped samples starter file, but I'd propose offering them at the end of the filtering and building lesson.

Thoughts?

**Comment by schanzer** [comment]
@flannery-denny 

1. We cover some of the "what filters might you want?" in the grouped-samples lesson, but both of these questions are already addressed in the data cycle _in the context of a specific question_. If someone says "Are weights distributed differently for cats v. dogs?", the data cycle asks them to write down which rows they need. They will inevitably lead them realize they need "rows for dogs" and "rows for cats"...which directs them to write filters. Ditto for "what columns do you need?", which makes them realize they might need a column that doesn't exist.

2. You're exactly right that this lesson uses DRs as review at the beginning. 

3. The starter files has those functions defined so that students will have already thought about them by the time they open the file. If you don't like this idea, then I suggest modifying the DR practices to be different-from, but _obnoxiously-similar to_ those functions in the starter file. If they're not going to be identical problems, they should at least be isomorphic.

**Comment by flannery-denny** [comment]
add opt-printable DR pages to Filtering and Building

# is-young :: (r :: Row) -> Boolean
# consumes a row and asks if age < 5
fun is-young(r): r["age"] < 5 end

# is-cat :: (r :: Row) -> Boolean
# consumes a row and asks if the species is "cat"
fun is-cat(r): r["species"] == "cat" end

# is-fixed :: (r :: Row) -> Boolean
# consumes a row and looks up the value in the fixed column
fun is-fixed(r): r["fixed"] end

# is-male :: (r :: Row) -> Boolean
# consumes a row and asks if the sex is "male"
fun is-male(r): r["sex"] == "male" end

**Comment by schanzer** [comment]
@flannery-denny definitely happy with these. Thanks!
