### ISSUE TITLE
audit alignment to social justice standards

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1424]
Right now, our standards alignment indicates that Computing Needs All Voices is literally our ONLY lesson that meets any of the social justice standards, and I know that is simply not true. We should update these alignments!

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/5a9d69c7-6d2d-45ef-936c-78398d1dbdd8)

**Comment by flannery-denny** [comment]
@retabak when I originally did this alignment, I really didn't think that we could claim that any of the other lessons dug into these SJ standards. Please make me a case for another lesson that does one of these standards justice.

**Comment by retabak** [comment]
Okay, I just read these standards very closely (several times), and.... I think you're mostly right, in general our stuff doesn't address these at the same level of depth as in Computing Needs All Voices.

That said, I think there are three lessons where alignment makes sense:
- Flags - SJ1, SJ3
- Ethics, Privacy, and Bias - SJ12, SJ13
- Checking Your Work - SJ13

Maaaaaaybe the Multiplicative Identity lesson could align with SJ5, but I think that one's a stretch.

**Comment by flannery-denny** [comment]
@retabak I went back to [the source](https://www.learningforjustice.org/sites/default/files/2017-06/TT_Social_Justice_Standards_0.pdf) of these standards and read their grade level outcomes.

- I've added `flags` to `sj1` and `sj3`  although I think it's a bit of a stretch that we're achieving their grade level outcomes.
-- _ID.6-8.1 I know and like who I am and can comfortably talk about my family and myself and describe our various group identities._ 
-- _ID.6-8.3 I know that overlapping identities combine to make me who I am and that none of my group identities on their own fully defines me or any other person._  
-- _ID.9-12.1 I have a positive view of myself, including an awareness of and comfort with my membership in multiple groups in society._
-- _ID.9-12.3 I know that all my group identities and the intersection of those identities create unique aspects of who I am and that this is true for other people too._
- I totally agree that we address `sj13` in `ethics, privacy and bias` and `checking your work` and discovered that it was already there.
- I thought `sj12` might be a stretch based on these outcome, but it was already there so I left it
-- _JU.6-8.12 I can recognize and describe unfairness and injustice in many forms including attitudes, speech, behaviors, practices and laws._  
-- _JU.9-12.12 I can recognize, describe and distinguish unfairness and injustice at different levels of society. __

**Now I'm confused as to where you discovered that there were no other aligning lesson and there's a bug because I am seeing all of these alignments listed and the only ones I've added are flags. How did you land on the idea that our alignment was only to computing needs all voices?**

```
{
  "SJ.1": {
    "description": "Students will develop positive social identities based on their membership in multiple groups in society",
    "lessons": [
      "computing-needs-all-voices",
      "flags"
    ]
  },
  "SJ.2": {
    "description": "Students will develop language and historical and cultural knowledge that affirm and accurately describe their membership in multiple identity groups",
    "lessons": [
      "bar-and-pie-charts",
      "computing-needs-all-voices"
    ]
  },
  "SJ.3": {
    "description": "Students will recognize that people’s multiple identities interact and create unique and complex individuals",
    "lessons": [
      "flags"
    ]
  },
  "SJ.4": {
    "description": "Students will express pride, confidence and healthy self-esteem without denying the value and dignity of other people.",
    "lessons": [
      "bar-and-pie-charts",
      "computing-needs-all-voices"
    ]
  },
  "SJ.5": {
    "description": "Students will recognize traits of the dominant culture, their home culture and other cultures and understand how they negotiate their own identity in multiple spaces.",
    "lessons": []
  },
  "SJ.6": {
    "description": "Students will express comfort with people who are both similar to and different from them and engage respectfully with all people.",
    "lessons": []
  },
  "SJ.7": {
    "description": "Students will develop language and knowledge to accurately and respectfully describe how people (including themselves) are both similar to and different from each other and others in their identity groups.",
    "lessons": [
      "project-research-paper",
      "project-exploration-paper",
      "bar-and-pie-charts",
      "computing-needs-all-voices"
    ]
  },
  "SJ.8": {
    "description": "Students will respectfully express curiosity about the history and lived experiences of others and will exchange ideas and beliefs in an open-minded way",
    "lessons": [
      "computing-needs-all-voices"
    ]
  },
  "SJ.9": {
    "description": "Students will respond to diversity by building empathy, respect, understanding and connection.",
    "lessons": []
  },
  "SJ.10": {
    "description": "Students will examine diversity in social, cultural, political and historical contexts rather than in ways that are superficial or oversimplified.",
    "lessons": [
      "computing-needs-all-voices"
    ]
  },
  "SJ.11": {
    "description": "Students will recognize stereotypes and relate to people as individuals rather than representatives of groups.",
    "lessons": []
  },
  "SJ.12": {
    "description": "Students will recognize unfairness on the individual level (e.g., biased speech) and injustice at the institutional or systemic level (e.g., discrimination).",
    "lessons": [
      "project-research-paper",
      "ethics-privacy-and-bias",
      "checking-your-work"
    ]
  },
  "SJ.13": {
    "description": "Students will analyze the harmful impact of bias and injustice on the world, historically and today",
    "lessons": [
      "project-research-paper",
      "project-exploration-paper",
      "probability-inference",
      "ethics-privacy-and-bias",
      "checking-your-work"
    ]
  },
  "SJ.14": {
    "description": "Students will recognize that power and privilege influence relationships on interpersonal, intergroup and institutional levels and consider how they have been affected by those dynamics.",
    "lessons": [
      "project-research-paper",
      "project-exploration-paper",
      "data-collection",
      "checking-your-work"
    ]
  },
  "SJ.15": {
    "description": "Students will identify figures, groups, events and a variety of strategies and philosophies relevant to the history of social justice around the world.",
    "lessons": [
      "checking-your-work"
    ]
  },
  "SJ.16": {
    "description": "Students will express empathy when people are excluded or mistreated because of their identities and concern when they themselves experience bias.",
    "lessons": []
  },
  "SJ.17": {
    "description": "Students will recognize their own responsibility to stand up to exclusion, prejudice and injustice.",
    "lessons": []
  },
  "SJ.18": {
    "description": "Students will speak up with courage and respect when they or someone else has been hurt or wronged by bias.",
    "lessons": []
  },
  "SJ.19": {
    "description": "Students will make principled decisions about when and how to take a stand against bias and injustice in their everyday lives and will do so despite negative peer or group pressure.",
    "lessons": []
  },
  "SJ.20": {
    "description": "Students will plan and carry out collective action against bias and injustice in the world and will evaluate what strategies are most effective.",
    "lessons": []
  }
}
```

**Comment by retabak** [comment]
The screenshot I took is from this page: https://www.bootstrapworld.org/materials/fall2023/en-us/Alignments.shtml?pathway=algebra-pyret

I now realize that the DS lessons wouldn't appear here (it's the Algebra pathway), which is why I only saw Computing Needs All Voices. I like the addition of Flags.

Sorry to have you repeat this work! I'm going to close the issue.
