### ISSUE TITLE
on web - @math formatting looks weird in DR directions

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1443]
... and I'm not sure why. I checked out the fragment but wasn't sure what the asciidoc should include.

https://bootstrapworld.org/materials/fall2023/en-us/lessons/functions-dr/pages/dr-geometry-cylinder.html

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/528a1076-4685-47e6-96d0-961d7e5d101d)

**Comment by schanzer** [comment]
@ds26gte looks like a serious regression. We need this fixed asap. :-(

**Comment by ds26gte** [comment]
Am keeping track while doing the (Racket) preproc if a file has `@math` in it, so that the mathjax lib can be loaded in its HTML. However, in this case, the file includes an external adoc (in `fragments`) which has the `@math`, so it doesn't know that mathjax is needed. I can try to beef up the scanning of subfiles (which at the very least implies I should make sure files in `fragments` get preprocessed before the "main" files). Alternatively, I can always load mathjax in all HTMLs if it's not a hog. Is it?

**Comment by schanzer** [comment]
@ds26gte I think loading it up 100% of the time is the way to go.

We use it in _so many pages_, so it's already likely to be in a user's browser cache. And this solves the problem permanently, instead of playing whack-a-mole trying to detect pages that include pages that include pages that include...

**Comment by ds26gte** [comment]
I just pushed a whack-a-mole fix before I saw your comment. Essentially, I make sure I always preprocess deeper files before less-deep files, so the latter, if they include the former, can check their uses-mathjax status and copy it.

I think it's fairly foolproof. If not, we can do brute-force mathjax for every page.

**Comment by schanzer** [comment]
@ds26gte it looks like this resolves all the issues inside `functions-dr`. I've looked at other fragment-using lessons, and it does not appear that any of them include pages that require @math{}. Looks like the fix works!
