### ISSUE TITLE
find a better home for "Making an Infographic"

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1449]
In looking at our projects, I noticed that this project is in "Bar and Pie Charts", which occurs *before* students have chosen their own real world dataset. Kids can't do the project unless they have a real dataset. An infographic about animals is just not gonna cut it.

The best place I can think to put it is in the "Choosing a Dataset" lesson, which seems a little odd, but perhaps it could be a nice review? I'm thinking it could go in the "Exploring Your Dataset" section (at the end of "Investigate"), and would act as a nice motivator for kids to start digging into and thinking about the dataset.

@flannery-denny, this is your project so I'd love your input. Let me know what you think about my suggestion.

**Comment by flannery-denny** [comment]
@retabak this project is not meant to go with a dataset. and does not hinge on choosing your own dataset. Teachers who only teach their students this lesson should be able to have access to this project. 

What needs to change to make the directions work for you?

**Comment by retabak** [comment]
It says, "Make an infographic from one of the bar or pie charts you made in Pyret."

The only bar and pie charts they've made at this point are of the animals dataset. How could this not rely on another dataset?

**Comment by flannery-denny** [comment]
Got it. I used to do this project before I worked for Bootstrap. And must have Bootstrapified it when our materials were ordered differently and more linear. It shouldn't hinge on choosing a dataset. I'll fix it. Thanks.

**Comment by retabak** [comment]
Hey! I'm looking at projects with a *super* critical eye and am still seeing some problems with this one.

If I were a student or a teacher reading these instructions, I would want to know where I'm supposed to find "one data display that intrigues me." I read that and was like, "Okay, where am I supposed to look for these displays?"  I'd also think it would be more at home in 6th or 7th grade unit on ratios.

If kids aren't looking at a dataset and creating their own displays, this is *way* less rigorous... and feels way less like it belongs in a data science course? I get that you want the activity to be accessible, but I don't see how it even fits in the bar and pie chart lesson anymore--save for the fact that the sample projects include some bar charts (though they are more complex than the bar charts kids use in the lesson, as those consume a single attribute).

In my view, the options right now are:
- give the project a new home (it's going to get its own lesson page eventually, anyhow) so that kids can use their chosen dataset
- provide some datasets (or displays - tho that's much less rigorous) for kids to choose from
- provide some links to where kids can find displays / datasets

Let me know if you want to discuss this.

**Comment by flannery-denny** [comment]
@retabak 

- part of your concern will be addressed through the edits to the bar and pie chart lesson I'm working on
- very happy for this to move to  another lesson plan for 2024 once we make things for lower grades.
- once this becomes a lesson page, happy to flesh out gaps that you're seeing.
- if we want to be extra helpful to teachers, we could pick a topic (or several) and generate a page of facts that they could make a pie or bar chart and an infographic from - my sixth grade classes chose their own class focus for the social justice data fair each year - generated questions as a class - and then I gathered the data for the best/ most findable 25 questions from the list so that each kid got one fact to work with - this would require some brainstorming and research! But would make the project much less work for teachers.

Will ping you when the lesson plan updates have been completed so you can decide whether it's good enough for 2023.

**Comment by flannery-denny** [comment]
@retabak please have another look at the infographic project on master (or the commit above) and close if you're satisfied.

**Comment by retabak** [comment]
**Teacher Prep:**

- [ ] Option 3 seems a little odd to me. We are assuming kids know how to build a bar or pie chart in google sheets, which I don't think is a safe assumption. Could we have them just sketch it instead?
- [ ] All other project instruction pages are student-facing, so it's odd that you've included teacher-facing content here. Can we tweak it so that it's student facing, e.g., "Your teacher will decide what sort of data you will be working with... Option 1: You will build bar or pie charts... Option 2: You will...." Name this section something like "Preparing to Create an Infographic" [see my suggestion below that we add a corresponding rubric row]
- [ ] Use "Preparation" instead of "Prep" and "statistics" instead of "stats."
- [ ] Instead of labelling the second section "Student Task", I'd name it something like, "Project Requirements."
- [ ] Under "student task" it says, "your goal is ...." I'd add a brief "overview" section at the top and instead put that sentence there to frame this for kids.

**Rubric:**

- [ ] The first rubric row no longer works, since in some cases teachers are providing ratio statements. I propose something like what I've typed below. (Probably needs some wordsmithing / adjusting.)

Preparatory Work
Wow: The bar chart or ratio statement I submitted to my teacher was a strong foundation for the remaineder of my infographic project. 

Okay: The bar chart or ratio statement I submitted to my teacher needed some revision in order to inspire a meaningful infographic.

Needs Improvement: I failed to submit a bar chart or ratio statement to my teacher or what I submitted was not conducive to creating a high quality infographic.

**Comment by flannery-denny** [comment]
@retabak 

As I understand it, you are about to turn all projects into lessons and I think that a bunch of this will sort itself out then.  Since I don't understand that vision it's hard for me to prep for that.

I added that teacher prep section because, in looking at the page I realized that it was designed for students, but that we didn't have a place for teacher directions (pretty sure that's why you're turning these into lessons).

I do think lots students in lots of school already know how to make pie charts in sheets! And I think it's totally reasonable to say that if the teacher is choosing between 4 options they'll pick that one if it's easy for them and they'll pick a different option if it's not.

My goal was to triage this page so that it was clearer than last year and assume it will get polished in the project -> lesson project. I think we have way bigger fish to fry at the moment of releasing our fall curriculum.

That said, go ahead and make whatever changes you want.
