### ISSUE TITLE
Make READMEs for Algebra 2 datasets that follow the existing guidlines

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1460]
See #1261 

- [x] [State Demographics](https://docs.google.com/spreadsheets/d/14fRmjAiCqGNI5Zr5kGSDjMavln7ILqhSX3N3zGd8CAU/edit#gid=578475144)
- [x] [Covid](https://docs.google.com/spreadsheets/d/1T73KS2IUU1kkG1SY4Ac7EU9Lj-ev1U9vzM_txSYcUhE/edit#gid=1592544923)
- [x] [Countries of the World](https://docs.google.com/spreadsheets/d/10UOkXBrwZlbOyW11mpJygAn3VINQWEfBb8tv3dIHX5A/edit#gid=497189956)
- [x] [Fuel Efficiency](https://docs.google.com/spreadsheets/d/1SLm1hDkVgAYxgh12dTD2Z3GXCUO9PrbwIZdqu9FiCGI/edit#gid=125005168)

**Comment by schanzer** [comment]
@flannery-denny I've updated the following:

[State Demographics](https://docs.google.com/spreadsheets/d/14fRmjAiCqGNI5Zr5kGSDjMavln7ILqhSX3N3zGd8CAU/edit#gid=578475144)
[Covid](https://docs.google.com/spreadsheets/d/1T73KS2IUU1kkG1SY4Ac7EU9Lj-ev1U9vzM_txSYcUhE/edit#gid=1592544923)
[Countries of the World](https://docs.google.com/spreadsheets/d/10UOkXBrwZlbOyW11mpJygAn3VINQWEfBb8tv3dIHX5A/edit#gid=497189956) hasn't changed since you did an update a long time ago, and I see a number of questions there (written by you!). I don't have the answers and I'm guessing you don't either, so I'm not sure how to move ahead.

**Comment by schanzer** [comment]
@flannery-denny did you want to look at the revised READMEs before closing?

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] I think the READMEs for the first two are ready to go and the old models of the READMEs should be deleted. Not doing that in case we haven't made duplicates before creating these READMEs because I think it's worth keeping a historical record of what our datasets used to look like.
- [ ] You and I should discuss what to do about the Countries of the World README notes in red and make a plan. 

As for the fuel-efficiency dataset, 
- [ ] I think it's critical that the information that the dataset is fictional, based on real data is important to communicate at the very start... 
- [ ] and in the lesson plan
- [ ] and in the `lesson-images.json` file for any screenshots made from this dataset
