### ISSUE TITLE
Change lesson plan CSS to use 9pt font size like the workbook pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1498]
- [x] While I'm at it, see if there's a way to have images auto-resize themselves when placed inside a `.FillVerticalSpace` table. This would cut out a TON of brittle rules for images size. For example, almost every single Alg2 page uses this!
- [x] Fix all the things that break
- [x] Switch lesson plan to use 9pt font
- [x] Move lessonsidebar outside of `#content`

-------------------------------------
Flannery's original message:

I'm in `exploring-linear-models`, have pretty good eyes, and I think this contract is bordering on difficult to read
<img width="612" alt="Screen Shot 2023-08-25 at 11 53 44 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/eb9a4ce8-a6b8-4c97-974f-8747f03ce9a1">

They're fine on the workbook page with the same contract
<img width="577" alt="Screen Shot 2023-08-25 at 11 53 32 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ee7d6330-2cbd-481e-8868-5c6d768a35f3">

**Comment by schanzer** [comment]
@flannery-denny that's because I shifted the screen workbook pages over to use the same font-size as the printed ones (and then zoomed in by 1.25x to make them readable on a screen). 

I did _not_ make this change in the lesson plans, which have a roughly 1.25x larger font size. In most cases they wind up looking almost identical, but in this case there's a 4px difference. 

The only way to resolve this will be to move the lesson plans over to the same zoom level and font size, which is a large overhaul that doesn't make sense to make before next summer.

**Comment by schanzer** [comment]
Saving this for posterity, as it does what we want for images inside tables with CSS Grid:
```
td { contain: size; }
td .content {
position: absolute;
width: 100%;
}
td .content .paragraph { height: 90%; }
td table { height: 10%; }
td .content, td .content .paragraph p, .image-figure, img { height: 100%; }

```
