### ISSUE TITLE
add comment to update-danger and update-target re: 2input function

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1535]

**Comment by retabak** [comment]
Okay, this is sort of a different issue, but feels similar in nature....

I got an email from a teacher asking this question: "In the numbers Inside Video Games: it says that there's 2 numbers needed to represent the cat on the frame, but only 1 for the other pieces. I assume the other one is their y coordinate - but wouldn't their x-coordinate change as they move across the screen?"

I think we need to be more explicit about how the clouds and ruby enter the screen at random heights? Or talk about how yes, these game pieces HAVE x and y coordinates, but only the x coordinate changes. (Which feels confusing to say, because in reality, the y-coordinate of those pieces changes to - but that's via randomization, right?) I do not feel like the best person to address this concern, but I think we ought to! @schanzer ? @flannery-denny ?

**Comment by schanzer** [comment]
@retabak I pushed some prose to address this comment. Let me know what you think? (I'm not addressing the main issue, since this is assigned to @flannery-denny )

**Comment by retabak** [comment]
@flannery-denny - I'm happy with this! Much better. I checked it out and thought that it looked great, therefore forgot to reply.
