### ISSUE TITLE
on web and locally, Language Table is doing weird things 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1575]
**In the lessons below *on the web*, there is a link to the Language Table in the lesson table, but when you click on it, nothing happens.**

- [Computing Needs All Voices](https://bootstrapworld.org/materials/fall2023/en-us/lessons/computing-needs-all-voices/index.shtml?pathway=algebra-pyret) - 
- [Intro to Data Science](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/ds-intro/index.shtml?pathway=data-science) 

**We need to remove the language table from lessons where no new language is added and where such language is often totally irrelevant. (i.e., The Data Cycle; Choosing Your Dataset; Ethics, Privacy and Bias... there are probably more!) I don't think the language table should appear at all and I'm not sure why it does?!**

--> Discussed this last item with @schanzer and we're tabling it for discussion during team meeting!

**Comment by schanzer** [comment]
@retabak I'm closing this since we've updated the website to fix the errant `put-image` declaration in an early lesson. Everything is correct, and we're planning to discuss your language table suggestion in tomorrow' meeting. Assuming Flannery is OK with it (I'd be shocked if she's not), we'll open a new issue to implement it.
