### ISSUE TITLE
make book COURSE=XYZ

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1583]

**Comment by ds26gte** [comment]
In this scenario, are you ok with being able to specify just one course for building? So the choice before you would be (a) build all, or (b) build just this course.

**Comment by schanzer** [comment]
@ds26gte  That is definitely all we need.

**Comment by ds26gte** [comment]
OK, I made it a bit more versatile. The make command-line `COURSE=` setting takes a comma-separated list of pathway names.

E.g., 
```
make book COURSE=algebra-pyret
```
builds workbook PDFs for `algebra-pyret` only.

```
make book COURSE=algebra-pyret,data-science
```
builds them for  `algebra-pyret` and `data-science` only.

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Not sure where this stands, but it doesn't seem to have speeded things up. 
After a fresh pull, make clean and make, here's what I'm seeing
<img width="602" alt="Screen Shot 2023-10-19 at 4 19 32 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/5c046d18-ed29-43d9-bbb1-c3f36b34ac5b">

**Comment by schanzer** [comment]
@flannery-denny unfortunately, Dorai said he is not able to get the arguments to work that way.

Please see the title of the issue for an example

**Comment by ds26gte** [comment]
Setting BOOK=something on the make command line is currently equivalent to `make book`, i.e., build PDFs for everything. If you would like `BOOK=xyz` to mean `make book COURSE=xyz`, that's doable. Let me know your preference(s).

**Comment by flannery-denny** [comment]
@ds26gte No need. I just misremembered what I was supposed to type  when I switched over to master to test it after my build broke on fall2024. Since I'd just been working in a busted environment, I was so prepared for the problem to be something other than myself I didn't think to doublecheck the git issue again like I would have if everything had been working up to that point. Sorry for the confusion.
