### ISSUE TITLE
can "PDF of all pages" open in a new browser tab rather than going straight to "downloads"?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1587]
personally, I prefer this (instant gratification, fewer clicks)!

If it is possible, I think it would be better! Maybe @flannery-denny wants to weigh in?

**Comment by flannery-denny** [comment]
I am in full agreement! (although I haven't experienced it downloading)

**Comment by schanzer** [comment]
@retabak @flannery-denny The current setup allows us to directly download a file with a sensible name, which will auto-open immediately for most people (default settings are typically to auto-open a downloaded PDF). What you are proposing does not change the number of clicks at all. 

But if you _really_ want it to open in a new tab first, that's doable. I spent about an hour this morning implementing this exact feature, but due to the security model of the browser there are some unpleasant realities:

A teacher who tries to download the PDF _from that new tab_ will get a filename that looks like a bunch of gobbledeygook - just link printing a file from gmail. If they're used to just hitting "save" and then "return" to save the file, they will be surprised when they can't find the file.

I think the current experience is much better. We could even change the link text to say "download", to make it clear what will happen when it's clicked.

**Comment by retabak** [comment]
I agree that it is better to have a reasonable name rather than having the PDF auto open. Let's leave as is, unless @flannery-denny objects.

@schanzer - thanks for fixing the file names! look great.

**Comment by flannery-denny** [comment]
Sorry. Now that I've actually attempted to use the pages of a lesson plan, I totally disagree!

The most important thing is to make our materials discoverable. 

I turn away from websites all the time that won't let me see something without downloading them, because 
- downloading things from a site I haven't already built trust with feels scary
- I want to know whether I like them before downloading them and cluttering up my machine
- I'm not always on the machine where I want them downloaded or have permission to download things

I would much rather have to name a file myself than not be able to see it without downloading it. And I had to do this with educational materials I used  in my classroom a million times! It's very common (perhaps because @schanzer has discovered that it's very complicated so many websites split the difference by leaving teachers to rename things)

In addition to all the other ways this is problematic, it will totally annoy me in my workflow because the way I realized that this is annoying is that I wanted to see the pages associated with the histograms lesson in order to understand something on my to do for 2024 workbook fixes.

**Comment by retabak** [comment]
okay, I think this is compelling. I vote with @flannery-denny ... unless @schanzer wants to make a case for the other side.

@schanzer - one thing that confused me is your statement that auto-opening will not change the number of clicks? It definitely does for me. What am I not understanding?

**Comment by flannery-denny** [comment]
@schanzer I'm on master. I've pulled, made clean and made book.

When I click on the link for `PDF of all Handouts` from within `file:///Users/flannery/Documents/Bootstrap/curriculum-review/distribution/en-us/lessons/correlations/index.shtml` it just stalls out in compiling mode.

Is that the behavior you would expect?

If the new regime really mean that as an author I can't view the workbook pages from the lesson plan unless I go through the entire lesson and click on individual links, we have to have the titles link to hmtl files and put the link to pdf beside it.

**Comment by flannery-denny** [comment]
Confirming that we definitely need to be able to link to html files. I just tried to file a bug report for another issue and there's no link to share...

**Comment by retabak** [comment]
I'm not sure what you're asking for and suspect we need to discuss in person at curriculum meeting. I don't want to revert the the very positive changes that have happened over the last 2 weeks! Let's make sure we're all on the same page on Tuesday.
