### ISSUE TITLE
@QandA directive should be able to take in a table for Q or A

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1594]
There are two use cases in the order of operations lesson plan on fall2024.
If this is a nightmare request, please lmk.

**Comment by ds26gte** [comment]
No nightmare at all. `@q`/`@a` should have allowed multiline input (which would include tables). Now they do.

There was a `}` misplacement in `order-of-operations/**/index.adoc`, which I've corrected.

Furthermore, when you have `@q`/`@a` containing a table as its first (or only) argument, the intermediate asciidoc has a bullet item followed by a newline. Asciidoctor, in its ∞ wisdom, won't recognize this as a list item, outputting the bullet verbatim. In order to counter this, I've added an `{empty}`, like so:

```
@A{ {empty}
[table stuff]
...
}
```

I could autoinsert this `{empty}` as the first element of _every_ `@q`/`@a` (doesn't hurt even where it isn't necessary), if this happens often enough and you don't want to remember to add it manually.

**Comment by ds26gte** [comment]
Since you're using multiple block elements inside an Q or A item, you will have to use `+` to string them along. In your specific case:
```
@QandA{
@Q{What would the code look like for these circles?
+
[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@show{(coe  '(/ 6 (+ 1 2)))}		| @show{(coe  '(* (- 10 5) 6))}
|===
}

@A{ {empty}
+
[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@show{(code  '(/ 6 (+ 1 2)))}		| @show{(code  '(* (- 10 5) 6))}
|===
}
}
```

**Comment by ds26gte** [comment]
Also: in future, now that @Q and @A respect newlines, don't do 
```
@Q{
first line
...
}
```
as it will output the bullet verbatim. Always have some text immediately after the `{`. If you can't -- e.g., because you're staring a table --, use `{empty}` as a bogus empty text. (Sorry, them's Asciidoctor rulez!)

**Comment by flannery-denny** [comment]
works like a charm. Thanks!
