### ISSUE TITLE
nitpicky issue re: formatting of contracts dictionary page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1619]
On the left browser and the right browser (both chrome), I'm zoomed in to 100%, but everything on the contracts dictionary is way bigger.  (See how the menu on the left takes up so much more vertical space?! When I click "Materials," all of the options are really spaced out, too.) I don't see this problem on any other pages of our site. Here's the problem link: https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret (also a problem in DS pathway)

oooooh, it just occurred to me that perhaps it is this way to make the contracts more readable? Hm, if that's true, it's probably fine and I am probably the only person who will ever notice this.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/50004d66-09c2-4933-81c7-48ec5581bb6f)

**Comment by schanzer** [comment]
@retabak that's because our workbook pages are all scaled by 125% when viewed onscreen, and the contract page ultimately goes into the workbook. We do NOT scale our lessons right now, which is why those pages appear smaller.

[It's on my list to unify the two already](https://github.com/bootstrapworld/curriculum/issues/1498), which will address this when it's complete.
