### ISSUE TITLE
Figure out why 2 page warnings are a moving target

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1624]
I'm working on fall2024 and pretty constantly merging in master.

- Last week I wasn't seeing any warnings for pages from the Order of Operations lesson being too long. 
- At the beginning of this week I was seeing a lot of warnings about pages in this lesson being too long.
- Today I am only seeing one warning about pages from this lesson. But now I'm seeing a bunch of warnings about pages in teacher resources.

I don't like the moving target and it makes me feel like there's a bug.

I also am concerned that the issue I am experiencing on fall2024 exists on master, which I am not working on.
 
Noting that the Order of Operations lesson that was throwing the warnings earlier in the week when I was testing things is quite different on the 2 branches.

**Comment by schanzer** [comment]
@flannery-denny , you and I have been talking about the changes I've made to the PDF build system for the last week. I slacked you about the changes in behavior. 

AFAICT this issue is resolved: we know why the warnings are a moving target. Is there any other issue that you want to report, or is it just that you wanted to know why things have shifted?
