### ISSUE TITLE
No Link to Rubric for Research Paper

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1644]
Teacher contacted me unable to find the Research Paper Rubric.  When going to the [DS Teacher Resources page and the Projects section](https://www.bootstrapworld.org/materials/fall2023/en-us/courses/data-science/resources/index.shtml?pathway=data-science), there is a comment: "You can find the description of this project (and the grading rubric!) at [the Research Paper page](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/project-research-paper/index.shtml)."  When you go to that lesson page, there is no link to a rubric.  The lesson instructs to "Take out your rubric! As we move through the template, ask questions about the rubric descriptors if they are unclear or confusing to you!", but there is no link to that rubric.  Also, the links [PDF of all Handouts and Pages](javascript:downloadLessonPDFs(false)) and [Additional Printable Pages for Scaffolding and Practice](javascript:downloadLessonPDFs(true)) just open up a blank pdf file.  I sent her [the rubric I used for my classes ](https://docs.google.com/document/d/1PtknZ459v6UuBPfcnAS5ZDOmYyPSW7Y8LvnEg43QCBo/edit?usp=drive_link)for now, but is there a Bootstrap rubric created that should be linked here?

**Comment by flannery-denny** [comment]
Thanks for reporting @joystraub ! I love seeing you making git issues!

**Comment by retabak** [comment]
@joystraub - yay for the git issue!

Eek! I'm attaching the rubric PDFs (it's a two-pager) so that you can share it with her. 

[Rubric_ Research Project.pdf](https://github.com/bootstrapworld/curriculum/files/13382694/Rubric_.Research.Project.pdf)
[Rubric_ Research Project (2).pdf](https://github.com/bootstrapworld/curriculum/files/13382699/Rubric_.Research.Project.2.pdf)

@schanzer - the version on the web does not match what's on master. Apologies if this is my fault (I assume it is)! Can you make it so that they match???

**Comment by schanzer** [comment]
@retabak sure thing. Just let me know what needs to be updated. Is it the TR page?

**Comment by retabak** [comment]
no, it's the actual project-research-paper page.

Every link that points to that research paper page is going to an outdated version.

**Comment by schanzer** [comment]
done! @joystraub close if you're happy

**Comment by joystraub** [comment]
Beautiful!!!

**Comment by joystraub** [comment]
I sent the links to the teacher.  This all looks great now!!
