### ISSUE TITLE
Come up with styling for @strategy used inside of overview sections

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1685]
The use case is for asides like the one below, which we have agreed would be best treated semantically, but not using `@teacher{}`
<img width="847" alt="Screen Shot 2023-12-05 at 8 25 11 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/aa09507c-78f4-4ff3-91de-0ce6def2c5d4">

**Comment by schanzer** [comment]
@flannery-denny I've pushed a proposal (with a change in this lesson) for you to check out. Let me know what you think?

**Comment by flannery-denny** [comment]
@schanzer I think this styling proposal is confusing. The content of that box is an aside, but it's the same color as the lesson instructions, which are the most important directions for teachers to say out loud.

I know that you are concerned about recycling the dotted shading from `@teacher`, but, at least with that styling it is clear to teachers that these are both asides. 

- Unless the line is dotted, I vote no line around the box. 
- Unless the shading is lighter, I vote no shading in the box.

I would suggest evaluation of the styling happen in the `contracts-tables-displays` lesson where all sorts of styling is used in close proximity, including two sections which have overviews that include this.

**Comment by schanzer** [comment]
@flannery-denny thanks, those are helpful suggestions! They actually led to a number of changes in the way I think about this, which have me coming around closer to your point of view. I've re-instated `@teacher`, and made a smaller modification to the visual styling. Let me know what you think?

**Comment by flannery-denny** [comment]
Works for me :)

**Comment by schanzer** [comment]
Writing notes for posterity:

We have multiple kinds of "asides to the teacher" formatting

1. `@strategy` boxes for "big" asides to the teacher
2. `@teacher` boxes for "small" asides to the teacher

But we _also_ have "Overview" sections in the lesson, which are - by definition - asides to the teacher. So what happens if we want to have an aside _within_ the Overview section?

I initially objected to the use of `@teacher` within an Overview, because it felt like semantic redundancy: putting "teacher" inside "teacher" section! However, I've come around to the fact that `@teacher` represents an "teacher _aside_", in which case there's no redundancy: It's a "teacher _aside_" within a "teacher" section. And that's fine.

The only change is that the _visual appearance_ of `@teacher` changes slightly when viewed within an Overview section. This issue large preserves to the appearance of `@teacher` when used used this, but tweaks it to make it meaningfully distinct from `@teacher` notes that appear in the lesson text.
