### ISSUE TITLE
When an adoc file calls an expression that is not defined in that file we should get an error or a warning

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1735]
The contracts lesson plan included this code `@show{(coe exp1)}`, but was missing `@do{
(define exp1 '(text 150 "Diego" "yellow"))`.

Instead of throwing an error, it just pulled a definition of `exp1` from another file.

**Comment by schanzer** [comment]
@flannery-denny whoa, great catch! To go for the gold...do you have any idea what other file it was pulling `exp1` from?

**Comment by flannery-denny** [comment]
@schanzer I think `contracts-tables-displays/index.adoc`

**Comment by ds26gte** [comment]
We're saving time by calling Racket just once to define the preprocessing procedure and then calling this procedure multiple times in a single namespace (that includes Racket plus the other preproc-related globals) on all the adoc files in one go.  I'm using `@do` to add definitions to this single namespace, so yes it's vulnerable to some definitions -- as in `exp1` above -- sticking around outside their adoc file. 

Creating a namespace for each adoc file that includes just right amount of preproc globals would be costly.

Since the problem only arises if an adoc file misses adding its own definition of `exp1`, I could do a scan of definitions inside every `do` and make sure they are redefined to something identifiably garbage, so you don't get silent misdefinitions. This will still add some time to the build, but not as severely as running the preproc individually on each file.

**Comment by schanzer** [comment]
@ds26gte if the scan is easy to implement, let's give it a shot and see what the performance penalty is. If it's going to take you a ton of time, then hold off until your plate is more empty 😉
