### ISSUE TITLE
2 permutation / combination formatting requests for slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1841]
1. Could we use slightly smaller font - right now every single formula is going to have to be shrunk by hand every time.
<img width="953" alt="Screen Shot 2024-02-09 at 10 47 58 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/36e45e93-d6ec-4a51-b3d8-aed52d725365">

2. Could the formatting of `permute-wo-replace` and `combinations` be consistent? (Note the smaller size that I manually shrunk these to)
<img width="952" alt="Screen Shot 2024-02-09 at 10 47 44 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2ef9337c-e480-4c80-9319-1b3ccdf42c5b">

**Comment by schanzer** [comment]
@flannery-denny unfortunately this is not possible. There are no "fonts" involved here by the time the slides are generated -- they're just images, which are always forced to be the width of the entire slide.

**Comment by flannery-denny** [comment]
@schanzer I guess this issue isn't slide specific, but it still requires attention that is above my paygrade.

The asciidoc reads:
```

Using our formula for "permutation without replacement" we get 24 duplicates:

@math{\mbox{permute-wo-replace}(4, 4) = \frac{4!}{(4-4)!} = 4! = 24}

Now, we need to divide 'the number of permutations (without replacement) for choosing 4 courses out of six items" by "the number of duplicate permutations in any four-course platter".

@math{combinations(6, 4) = \frac{6!}{(6 - 4)!} \div 4! = 360 \div 24 = 15}
```

As far as I understand, both `permute-wo-replace` and `combinations` are functions. 
If that is true, they should render in the same font.
They render in different fonts in the lesson plan and that difference then passes through to the slides. 

<img width="825" alt="Screen Shot 2024-02-15 at 3 49 41 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/412af16f-859a-454a-bd3c-7d4591f14d61">

Do you understand why `permute-wo-replace` isn't italicized and `combinations` is? Can you figure out how to make the way they render align better?

**Comment by schanzer** [comment]
@flannery-denny great catch! If you look at the `@math{}` directives, you'll notice that we use a latex directive called `\mbox{..}` to format permutations, but _not_ for combinations. That's why the formatting is different, and you're spot-on that we should be consistent.

As for how we _got_ to this place....
Latex treats identifiers with dashes (like permute-wo-replace) as subtraction operations, and leaves extra space around the dash. `\mbox` tells Latex to treat the dashes like hyphens. We needed to use it for permutation-wo-replace, but didn't need to for combinations. But that doesn't change the fact that consistent formatting is good, so thanks for the catch!
