### ISSUE TITLE
@strategy boxes sometimes appearing as images on seemingly random slides

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1856]
In ds-intro on fall2024, two different strategy boxes just appeared as images in a seemingly random, completely unexpected place in my slide deck? They are actually ON the slide, not in the teacher notes; see screenshot below.

I wonder if slide building got confused because these @strategy boxes were *not* in Investigate sections. One was in an Overview section, the other was in a Synthesize section. Other than that, I'm not sure why this happened. A third @strategy box in this very same deck behaved as I expected it to (e.g., the text showed up in the presenter notes).

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/191e4885-a592-4f72-96f1-e881cd9ca5a0)

**Comment by schanzer** [comment]
@ds26gte @retabak the problem here is that `@strategy-box` expands into a an asciidoc _table_, and we just recently added code so that all tables get converted into images. One solution would be to extend `make-slides.lua` to skip over tables with the classname `.strategy-box`. 

But another, semantically-better solution is to just stop using tables in the first place. I've just pushed a commit that does that, and tested it with both ds-intro and linear-regression. @retabak can you try after a clean make and close if you're happy?

**Comment by flannery-denny** [comment]
@schanzer I am still running into the same problem in the correlations lesson after a fresh pull and npm update. 

(I wanted to double check that nothing old was stuck so I made clean, but now make has been failing for slides for a few minutes, which I assume is that recurring google lag issue, so I'm going to bed before I can confirm for sure)

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing what you're seeing. Most likely cause you never deleted the correlations folder in distribution, which means you were still using the `slides.md` file generated by the pre-fix build script. Try deleting the folder (or running make clean), and close if you're happy?

**Comment by schanzer** [comment]
@flannery-denny I'm pretty certain this is a non-issue. Can you try building from a make clean (or at least deleting the correlations lesson folder in `distribution`), and then re-building the slides?

**Comment by retabak** [comment]
Fyi, this issue is resolved for me.

**Comment by schanzer** [comment]
@retabak ok, I'm going to go ahead and close this. Flannery, feel free to re-open if it's still an issue for you.
