### ISSUE TITLE
@optional isn't behaving as expected in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1859]
Even though we don't want optional things on slides, it would be helpful if `@optional` rendered with the word optional so that authors would be clued in to the fact that they need to fix the asciidoc.

On slides, all optional things belong in the presenter notes. Putting them there requires the use of `@opt`

We also have a directive `@optional`, which shouldn't be used on slides, but is useful in preparation sections and workbook pages not related to slides.  In print and online materials it renders as the word _Optional:_ in front of the text that follows itt.

I'm building the coordinates slide deck. And there was an errant`@optional` in the lesson plan on line 73. I would have expected it to render as _Optional:_ in front of the text that followed it, but instead it rendered without the word optional. That made it tough to discover that the wrong directive was being used.

**Comment by schanzer** [comment]
@flannery-denny I couldn't find the lesson where @optional occurred on line 73. Can you give me a hint? 

Also, and more importantly, if we're not supposed to use @optional in lesson plans, it seems like the real bug here is in the _lesson plan_, not the slide. I've updated the build-slide script to dump a warning to the console, so authors know not to use it in lesson plans.

**Comment by flannery-denny** [comment]
@schanzer Are you able to make that warning more specific and allow `@optional` to show up in the materials table? It is supposed to be ok to use it there.
