### ISSUE TITLE
add a warm up to logos project

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1866]
where students replicate simple pre-existing logos

**Comment by retabak** [comment]
@schanzer - checked out the related commit. This is ready to close if it looks OK to you.

**Comment by schanzer** [comment]
@retabak  looking good! I fixed a bunch of small things in my commit, but a few changes still need to happen:

1. The images you are importing in the Logos Warmup are on other people's servers, which means they could disappear at any moment. They should either be added to Bootstrap's gdrive (`Curriculum/~Files for hosted programs - DO NOT DELETE`) or downloaded and added to our repo, then linked from the lesson. 
2. The COE at the bottom of the "Logo Study" page and in the lesson plan is totally messed up. Have you been building and checking these, or just looking at the adoc? I tried to clean up the version on the Logo Study page, but I'm not sure if the end result is what you wanted. If it is, please update the lesson plan to match or change both to some other thing that renders properly.
3. I think the lesson would benefit from a really quick diagram showing the COE for adding three numbers, as a scaffold for overlaying three images.
4. In "Coding Your Logo", the first instruction says "you will compose the functions you selected (above) in order to create your logo". What is the (above) supposed to be about?
5. On the same page, I don't understand question 4: "When you compare the Circles of Evaluation to their logo sketch"
6. On "Create Your Own Logo", you tell kids to "open Pyret". But what if they're in WeScheme?
7. Both "Create Your Own Logo" and "Coding Your Logo", you have instructions for kids to "Save a copy". But what if they're in WeScheme?

Reminder: please use proper indenting/linebreaks for `@teacher`! If the contents of the teacher note don't fit easily on one line of asciidoc, put the contents on their own line. I've gone ahead and fixed these for the lesson plan, but in the future I'll be asking you to do it so you commit it to memory. ;)

**Comment by schanzer** [comment]
@retabak I strongly object to the "messed up" COE as-written in the lesson plan. If my modification on the wbpage works, use that. If you don't like it, we should discuss.

In WeScheme, kids click "Remix"

**Comment by retabak** [comment]
I've made all changes to this, but am avoiding pushing the changes because it would introduce a page-length warning due to this image (below) that I slacked you about, @schanzer :

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/38d72805-74d4-47a5-b899-61c1e3f0c6e1)

**Comment by schanzer** [comment]
@retabak it's kind of hard for me to debug something that's not pushed, but it's likely that the outermost circle isn’t wide enough.

(In the future, I'd do this work on a branch precisely for this reason. Then you can squash and merge a clean PR)

**Comment by retabak** [comment]
I forgot that I intentionally avoided pushing this commit.... and I pushed it. I'm sorry. If you can fix the width of the outermost circle when you have a minute (I know the minutes are hard to come by this week!), I would appreciate it. This particular COE is in logo-study.

**Comment by schanzer** [comment]
@retabak you have the Circle of Evaluation trapped in one column of a table, so it can only get so wide. In order to deal with that, it's wrapping the children across two lines in order to show them all.

If you want to see the whole thing, set it free!

**Comment by retabak** [comment]
okay, I have responded to all feedback and believe that this is ready to close. Take a look if you'd like, @schanzer.

**Comment by schanzer** [comment]
Looks great!
