### ISSUE TITLE
update data cycles to include stems / scaffolding for animals dataset only

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1888]
- remove stems / scaffolding when students analyze their own datasets.
- If animals dataset data cycle is NOT included in the lesson, add it (with stems / scaffolds)
- For animals data cycle, provide Q1 but not Q2
- Revise lesson wording to scaffold data cycle process (as in box plots)
- [x] bar and pie charts - remove 2 data cycles, as this lesson preceds DC lesson
- [x] histograms - added animals DC
- [x] grouped samples - no change needed
- [x] box-plots - added animals DC
- [x] visualizing-the-shape-of-data - added OPTIONAL chosen dataset DC; made chosen dataset optional, as students can simply edit / revise the cycle they did in the histograms lesson. Feels like a waste of paper for them to copy over everything they wrote;  added new scaffolding (from FD, with vocab) to animals DC, asking students to use new vocab. 
- [x] linear regression - reformat DC to match other DCs; add animals dataset data cycle; decided to leave stems / scaffolding in chosen dataset data cycle because (1) it's always been there, (2) this structure is a bit complex. @schanzer, if you want to remove, that's fine with me.
- [x] measures of center - add DC for chosen dataset
- [x] data-cycle - revise using feedback from @flannery-denny 
- [x] scatter-plots
- [x] standard-deviation - this lesson was correct!
- [x] choosing-your-dataset - added data-cycle prereq

Create answer keys for all new animals data cycles:
- [x] histograms
- [x] box-plots
- [x] visualizing shape
- [x] linear regression
- [x] bar-and-pie-charts (getting moved to data-cycle)

**Comment by flannery-denny** [comment]
@retabak 
A while back @schanzer and I had a long discussion about including those data cycles in Bar and Pie charts and there was wording about the fact that the data cycle hadn't been introduced yet. Are you sure you can't live with them there? They got added because it felt very strange that the lesson didn't give students an opportunity to use what they'd learned independently to investigate the animals dataset. 

**If you feel they need to be removed, please add a pretty data cycle alternative that engages students with the animals dataset for that lesson.** 

Furthermore, because it felt so important that students actually got to practice (which the version you have up and running on fall2024 doesn't offer), we also added a link to the food dataset to additional practice section of that lesson, which makes absolutely no sense to do before having them work with the animals dataset.

**Comment by retabak** [comment]
@schanzer and I discussed this yesterday, and agreed that having students data cycle before it is introduced (even with wording explaining "this is a preview") would be more confusing than helpful. Students can learn about bar and pie charts AND the data cycle simultaneously - that's a cognitive overload.

In reviewing the lesson, I actually think there are plenty of opportunities to make bar and pie charts with the animals dataset. There are two separate worksheets where students do exactly this. Do you think another is needed?

Why doesn't it make sense to leave the food dataset? I'm not sure that I follow.

**Comment by flannery-denny** [comment]
@retabak The data cycles that you've removed were the only chance that students had to think about what question they might be able to answer using the displays they are introduced to in the second half of the lesson. Removing them feels antithetical to the structure of data science.

Right now it feels like we're saying. "Hey, here's the coolest display type you've been introduced to so far. But, don't bother to think about how you might want to use it."

I object! Feel free to figure out an alternative way to engage their curiosity.

**Comment by retabak** [comment]
@flannery-denny -

Why do students need to think about how they might want to use bar and pie charts *in the very same lesson* that they learn about bar and pie charts? What if, as a compromise, we add these two data cycle pages to the last section of the data cycle lesson (which immediately follows bar & pie charts)? They make way more sense there to me.  In looking at that lesson, I'm seeing we actually have a data cycle called "Analyzing with Displays" which only includes `count` - which I wouldn't quite consider a display. So, there is a gap that we could fill. (And, we could rename that `count` page to more accurately reflect what is happening there, too.)

**Comment by flannery-denny** [comment]
@retabak I would be fine with that proposal if all users were expected to engage with our full pathway. But the whole point of putting bar and pie charts in front of the data cycle is so that it's accessible to folks who won't do the data cycle lesson! 

It is the very nature of our mix and match model that makes me think it is critical that students are _always_ asked to think about how they would use a display _in the very same lesson_ where that display is taught in depth!  

I vote:

1. Move the data cycles as you propose
2. In this lesson:
-  For each kind of display, direct students to build one of their own choosing from the Animals Dataset
- Add synthesize questions to both sections that get students thinking about what displays they would be curious to make

**Comment by flannery-denny** [comment]
@retabak I am happy to make optional scaffolding for the displays that they build that doesn't look like the data cycle.

**Comment by retabak** [comment]
sounds good to me! 

I'm assuming that the data cycles in "The Data Cycle" lesson should be optional, then?

**Comment by retabak** [comment]
@flannery-denny @schanzer - I'm going to move the two data cycles from the bar & pie charts lesson to the last section of the data cycle lesson. My instinct is that we make the first one required and the second one optional. Does that feel right to you? 

FWIW, bar & pie charts *is* listed as a prereq to data cycle .... although given the current lesson structure and worksheets, it honestly doesn't need to be a prereq! If we add these 2 other worksheets, it would in fact need to be a prereq.

**Comment by retabak** [comment]
@schanzer - we won't remove a dependency unless I make *both* worksheets optional!

**Comment by schanzer** [comment]
@retabak good call. Then keep the dependency, and keep one DC worksheet required.
