### ISSUE TITLE
Slide/Lesson table indices can go out of sync

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1890]
One example of this error can be found in `contracts`:

```
Unable to generate slides: [Error: ENOENT: no such file or directory, open '/Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts/images/TABLE2.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts/images/TABLE2.png'
}
```

The issue is that we rely on table indices being identical between slides and lessons, such that the _nth_ table in one is also the _nth_ table in the other. Unfortunately, this is not a safe assumption thanks to `@ifslide` and `@ifnotslide`, which can contain tables that increment the table counter in one but not the other.

We need a more robust way of referring to tables, or a way to keep these indices in sync

**Comment by schanzer** [comment]
@ds26gte your commit _almost_ gets us there! I think your processing of the table directive isn't quite right -- here's what that hiddenBlock div looks like when it's not so hidden

<img width="891" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/c9198f37-13dc-42b5-a450-71aef8cf59fe">

The table element doesn't show up, because some string processing is off. If you can get the table rendering (behind `display:none` of course!), I can get the screenshots working properly

**Comment by ds26gte** [comment]
I've corrected preproc.rkt's processing of `@ifslide` to respect newlines, and it now generates the `<table>` inside a hidden `<div>`, but your JS file still isn't generating the `TABLE2.png`.  Please check after pulling

**Comment by schanzer** [comment]
Checked - success! Nice teamwork, @ds26gte . *fistbump*
