### ISSUE TITLE
@n from within @ifslide is rendering as @n on slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1892]
Here's some code from the definining-table-functions lesson plan.

I'm going to think about another way of formatting this, so it might not still be there when you try to build. But, either way, I think it should be addressed such that @n renders as a number in slides.

```
@ifslide{

*Round 1:*
You should have a page with a Word Problem.
@n Write the Contract and Purpose Statement.
@n Fold your paper to hide the Word Problem.

@teacher{
Choose which set of word problems you are going to start with and give each student within each group a different word problem.

* Set 1: @handout{is-dog.adoc, is-dog}, @handout{days.adoc, days}, @handout{is-young.adoc, is-young}
* Set 2: @opt-printable-exercise{is-old.adoc, is-old}, @opt-printable-exercise{kilos.adoc, kilos}, @opt-printable-exercise{is-cat.adoc, is-cat}

}
}
```

**Comment by schanzer** [comment]
I really think that @n should not be used in lesson plans. It's such a narrow use case, compared to using it in our workbook pages, and as we can see from this issue, it's added complexity.

Is there really a compelling use case for this, that's substantially better than just writing the numbers by hand?

**Comment by ds26gte** [comment]
I can add it for slides, but it brings up a point. `@n` starts from 1 for each .adoc file (unless `@nfrom` is used to intervene). However for slides, it should probably start from 1 _for each slide_.

In the lesson plans where it's currently used, it doesn't make much difference, because `@n` seems to be used entirely in the space of what would constitute one slide (i.e., there is only one contiguous sequence of `@n`s).
