### ISSUE TITLE
Something very strange just happened in my slide build - part of the lesson plan just showed up as an image...

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1921]
This is from order of operations. Just flagging it because it's so bizarre. Assuming it will resolve itself but haven't had a chance to test.

<img width="1202" alt="Screen Shot 2024-02-28 at 2 18 29 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6f32ea3b-1f42-4063-9557-a259856e349a">

**Comment by retabak** [comment]
This happened to me once today... but then I built again and it was fine.

**Comment by schanzer** [comment]
@flannery-denny amd @retabak , would you mind sharing links to these slides? I just tried building order of operations and I'm not able to reproduce the issue

**Comment by flannery-denny** [comment]
@schanzer https://docs.google.com/presentation/d/1mTlmWUbMDUqoC-1UqDqAR2Dgy_UEy-Rv1z5L3VMhUS8/edit#slide=id.0bb5de10-d675-11ee-8471-11167115370b

**Comment by schanzer** [comment]
Thanks, @flannery-denny !

I'm not certain of the cause here, but I _suspect_ that the browser is falling behind the screenshotting tool. I've pushed a commit that waits a full 2 seconds before taking screenshots, which should resolve the issue if I'm right. And if this keeps happening to you, we can at least rule out this as the cause.

**Comment by flannery-denny** [comment]
Sounds good.
