### ISSUE TITLE
Function Notation slide deck is swallowing `gt`

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1923]
https://docs.google.com/presentation/d/1DDyM0EFteISSSZoAny-D1FlD2Pfpz--oTRaiOZgabz4/edit#slide=id.53e88396-d6ac-11ee-b507-532104b3adfc

We would expect to see `gt` here on slide 2

<img width="374" alt="Screen Shot 2024-02-28 at 8 56 03 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/eb117b60-d143-43b7-bc7b-a646483a93ee">

We would expect to see `gt` here on slide 7

<img width="255" alt="Screen Shot 2024-02-28 at 8 56 12 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6715ffd6-f923-4a1c-827f-e12d39713fb2">

**Also seeing Danger and Target swallowed on slide 2 of Player Animation**
https://docs.google.com/presentation/d/1FuneOwLsI2IA4Yjy36O_pNUVXB2LSCtRui1GUNIXMXc/edit#slide=id.99fc81e0-d6ae-11ee-b2f6-dd22b2a05803

**And Slide 4 of Problem Decomposition**
https://docs.google.com/presentation/d/1-MdMbC4UgF_JEYNSXx7yp8hbtCOQLFePXd4Z_VfWtV8/edit#slide=id.f0dbbc13-d6ae-11ee-8b19-cd5becb5f357

**Comment by schanzer** [comment]
@flannery-denny yep -- the new syntax highlighting code was the culprit!

The highlighter has an "auto" mode, which looks at the code and tries to guess which programming language it is. It turns out that if it can't come up with a guess, it just drops the code entirely! I've pushed a fix that defaults to Pyret in this instance, which resolves the issue.
