### ISSUE TITLE
Research / talk to teachers to understand how they use Bootstrap and how we can improve

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1954]
Here is a link to the [Teacher Research Brainstorm google doc](https://docs.google.com/document/d/1LZ9JX9-6aL2Ay8OFoxYfdBN8c_FaLTzeF0jfALxmAHw/edit?usp=sharing) that came out of our August 7 meeting

Here is [the google sheet where we are brainstorming a list of "diehard" Bootstrap adopters](https://docs.google.com/spreadsheets/d/1ArA68XPZ37NCDKEnnjrbWXDsKKFQrmGc8sF9VRVtqwc/edit?usp=sharing) from which to select about 20 for our preliminary round of interviews this fall, which will ideally represent a diverse pool from various states who old a range of positions in "the bootstrap ecosystem at their school"

---- prior issue description is here
- [x]  Make a Plan (Summer), distribute to Kathi and JoJo and Emmanuel
- JoJo wants to know:
-- Who is actually using our curriculum?
-- And what is motivating them to do that?
-- Are there other things they’d like to see us offer?
-- What barriers did they face?
-- Tell me more? Why is that?
- Draft an email (our emails get about a 30% click rate and have an email list that reaches about 2400 people.)
-- offer them a gift card for participation or the opportunity to be entered into a raffle
-- invite them to sign up for a 30-minute slot on calendly (how can we accommodate for the fact that teachers might be available 10:13 - 10:53 which puts them out of commission for both a 10-10:30 slot and a 10:30-11 slot?)
-- let them know that we will be using firefly to record sessions 
-- When someone signs up for an interview slot, send them a link to the google form we are currently asking all workshop attendees to complete (let's review it and make sure we don't want to modify it for this audience)
- Draft a google form we can complete during interviews. 
-- It should include questions about curriculum in the works.
-- Perhaps we could test run our interview guide on a list of people that Rachel, Joy and Emmanuel know are actually implementing?
- QUESTIONS TO RESOLVE: 
-- What is the budget for compensating participants?
-- How much time do we actually want to allocate to this this fall - what's our target number of interviews? (If half of the people who open the email sign up for an interview we'd be at 200 hours)
-- Do we want to interview everyone or collect different kinds of information from different kinds of people?
- [x] Execute (Fall)
- [ ] Present Findings and Recommendations (Fall)
- [ ] Update:
- PD
- Algebra Materials
- DS Materials
- Coaching
- Discourse

**Comment by JoJoBahnam** [comment]
Thank you so much for taking the time to have the conversation and to put this plan together! Let's feed this into our conversation with Kathi + Joy (August TBD).

**Comment by schanzer** [comment]
@flannery-denny and @retabak reminder that what you come up with here needs to be ready to present at our August meeting

**Comment by schanzer** [comment]
@flannery-denny and @retabak nevermind - JoJo says you've already drafted a plan!

**Comment by flannery-denny** [comment]
reopening this because we haven't interviewed any teachers yet ;)
@retabak @joystraub @kfisler @JoJoBahnam and I met today and decided to create two brainstorming documents: 
- [research framing brainstorm google doc](https://docs.google.com/document/d/1LZ9JX9-6aL2Ay8OFoxYfdBN8c_FaLTzeF0jfALxmAHw/edit?usp=sharing) 
- [candidate brainstorm sheet](https://docs.google.com/spreadsheets/d/1ArA68XPZ37NCDKEnnjrbWXDsKKFQrmGc8sF9VRVtqwc/edit?usp=sharing) from which to select about 20 people representing a diverse pool from various states who hold a range of positions in "the bootstrap ecosystem at their school" for a preliminary round of interviews this fall

@schanzer we are counting on you to propose a number of potential teachers for us to interview.
- Please add any columns to the sheet that seem relevant and useful!
- Ideally, by the time you've finished, we will have as much info about these candidates as you do that would be relevant in helping us to decide which people to work with

**Comment by schanzer** [comment]
@flannery-denny The columns look good to me. I took a pass at adding folks - let me know if you want me to add more?

**Comment by flannery-denny** [comment]
@Schanzer @retabak looks like our list only includes type 2 and 4 and there are many states unrepresented. 

If there are people who we think would talk to us  from other geographies or we would consider to be
type 1 [They were sent by admin (school or district) ] or type 3 [They had prior experience with teaching [TOPIC] a different way and wanted to try something different (in which case we want to know what the issue was] we should add them even if they only have one year of bs teaching experience or are running trainings.

I'd love to also add a column for what we know about their school / math department / student demographic to make sure we have some diversity there.

**Comment by flannery-denny** [comment]
closing because we've made individual issues for the things from the [interview takeaways](https://docs.google.com/document/d/17rK8j2obNk_ASR0_6EvIwcC-_mWwBhtN7gzYfnPSvyg/edit?tab=t.0) that we plan to follow up on including:
([#2191](https://github.com/bootstrapworld/curriculum/issues/2191))
#2196 ]
#2218 
#2219
#2220 
#2230 
#2234 
#2235 
#2236 
#2237
#2238
#2240 
#2241
