### ISSUE TITLE
Lesson Slides for optional Project: Create a Research Project do not reference Paper template- just the exploration slides template

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1955]
The Project: Create a Research Project page linked from the Project: Dataset Exploration page references the option to use the Research Paper Template.  
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/5945f460-e3bc-4701-8a0b-91217924167f)

The lesson slides for that lesson do not include this - it would be nice to have a slide for the optional transfer of their exploration slides to a research paper, with a link to the Research Paper template.  Maybe it is not here, because it is optional and teachers may want to modify it before giving it to students - but could there be an optional slide, like we have for optional materials?

**Comment by retabak** [comment]
hi, @joystraub!

I see that the excerpt you put above ("Optional: For teachers who...") is in the *presenter notes* on the last slide Project: Dataset Exploration's slides... but the URL doesn't work. (It's just a blank space.) Would fixing the URL meet your needs? Or do you want this information actually on a slide? (Because it is teacher-facing, and not student-facing, it ended up in the presenter notes.)

If we add an "Additional Materials" slide, you would want to link to the Research Paper template, yeah? I'm just worried that will confuse teachers who don't do the research paper and have avoided learning about it. (I'm thinking about folks who use the slides without reading the lessons.)

**Comment by flannery-denny** [comment]
@joystraub, fyi - we generally operate with the guiding principle that motivated teachers can and will edit the slide decks. And that optional things should appear in presenter notes for teachers to add into decks if they wish.

@retabak I think putting a link in the Additional Materials section is a great idea! And am struggling to see the potential harm... Either way, the preparation section should ask them to decide whether or not they plan to engage their students with the paper (because that will inform how they facilitate the exploration) and the preparation section could easily include a note to remove the slide from the deck if they won't be using it.

**Comment by joystraub** [comment]
@retabak @flannery-denny I do not see a reference to the Research Paper template in any presenter notes for either of the lesson slide decks for Project: Dataset Exploration or in Project: Create a Research Project.  I have both open - there is no reference to converting slides to a paper nor a template for that paper.
Just a side: This has come up, because this is a topic for training this Thursday.  I was pulling in slides to my training deck to help guide our discussion.  I am very confused by the two slide decks - Project: Create a Research Project seems very similar to Project: Data Exploration - not sure why we have both. I guess I was envisioning one slide deck walking through setting up the Data exploratio slides template for students to fill in.  The other deck for an optional activity of extending those slides to an actual research paper. It is just more on using the exploration template slides.

**Comment by joystraub** [comment]
@flannery-denny Thank you - I condensed the slides for Thursday, so no need to hurry.

**Comment by flannery-denny** [comment]
Glad to hear that @joystraub. With less urgency, I am going to close this issue and make it part of #1616
