### ISSUE TITLE
Errors in Solution Key for The Effect of an Outlier Workbook Page

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1966]
Questions 6 on down on The Effect of an Outlier DS workbook page have errors in the solution key.  
The squared distances are slightly off.  They should be:
10.2, 10.2, 10.2, 10.2, 4.8, 4.8, 1.4, 0.6, 7.8, 7.8, 39.2 (when truncating the hundredths place which is a 4 for each of these)
Then number 7 should be 207.2 (it is currently 340, which is too high even without these small changes in question 6)
Number 8 is then 20.72 (not 34)
Number 9 is ~4.55 (not ~5.83)
Number 10's answer is still valid.

**Comment by flannery-denny** [comment]
@joystraub Now that you're getting to be such a git issue maker, please let us know where you are seeing the issues. 

- Is this in the fall2024 workbook you're reviewing for us?
- Or is this on the web?

As I mentioned in our call, we're always working on multiple versions of our materials and it's helpful to know where to look!

**Comment by joystraub** [comment]
Sorry - this is in the current curriculum on the web.  It was pointed out to me by a teacher who wondered if she was doing something wrong.  I did the math and the current answer key is incorrect as I outlined.

**Comment by flannery-denny** [comment]
Thanks @joystraub.  I made the fixes as you requested, even though they were very close to what was in the file. I don't have bandwidth to think my way into this page right now, but I'm assuming that you meant to write 139.2 not 39.2?  and am hopeful that the rest of your calculations were correct.

@schanzer The numbers Joy is seeing on the web don't match what was on master... and that feels concerning.

**Comment by joystraub** [comment]
@flannery-denny Yes -SO sorry - that was 139.2  I have to be very slow and deliberate when typing numbers into these comments for some reason.  I went over and over that and still missed the 1!!  Sorry.

**Comment by schanzer** [comment]
@flannery-denny I've attached PDFs of the solutions from both `master` (live on the web) and `fall2024`. I'm very likely just cross-eyed right now, but I don't see what's not matching?

[fall2024.pdf](https://github.com/bootstrapworld/curriculum/files/14610102/fall2024.pdf)

[master.pdf](https://github.com/bootstrapworld/curriculum/files/14610103/master.pdf)

**Comment by flannery-denny** [comment]
@schanzer 

1. If you look at my commit on `master` from 3 days ago, you'll see that I made some minor changes in order to get that branch to match what Joy wanted... most of the values in the table were off by 0.1 from her calculations (I haven't recalculated them) 
2. Assuming we want to go with Joy's numbers, we should cherrypick those same changes to fall2024.
3. After a more careful look, I see that the egregious numbers Joy was reporting as "live on the web" are from [fall2023](https://www.bootstrapworld.org/materials/fall2022/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html) and we fixed them in the [spring2024](https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html) release.

My guess is that @joystraub is either trying to support teachers from an outdated printed version or a cached version of the page.

Let's make it a priority to help her know how to double check that she's looking at current versions of things, so she can share updated links with teachers looking for them when possible.

**Comment by flannery-denny** [comment]
@schanzer 

1. If you look at my commit on `master` from 3 days ago, you'll see that I made some minor changes in order to get that branch to match what Joy wanted... most of the values in the table were off by 0.1 from her calculations (I haven't recalculated them) 
2. Assuming we want to go with Joy's numbers, we should cherrypick those same changes to fall2024.
3. After a more careful look, I see that the egregious numbers Joy was reporting as "live on the web" are from [fall2023](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html) and we fixed them in the [spring2024](https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html) release.

I also see that we changed the numbers from 10.2 to 10.1 between [fall2022](https://www.bootstrapworld.org/materials/fall2022/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html) and [fall2023](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/standard-deviation/solution-pages/effect-of-an-outlier.html)

My guess is that @joystraub is either trying to support teachers from an outdated printed version or a cached version of the page.

Let's make it a priority to help her know how to double check that she's looking at current versions of things, so she can share updated links with teachers looking for them when possible.
