### ISSUE TITLE
sexp parser for == needs updating

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2004]
This expression is defined in the asciidoc
`(define e4 '(and (<> 3 2) (== (+ 3 5) 8)))`

Pyret code should look like this
`(3 <> 2) and ((3 + 5) == 8)`

But here's what i'm seeing on the workbook page

`(​3 <> 2​) and ==​(​3 + 5, 8​)`

I will be pushing the page shortly. It's `inequalities3-sam/warmup-compound-ineq`

**Comment by ds26gte** [comment]
#notabug!

The Scheme expression should be written
```
(and (<> 3 2) (= (+ 3 5) 8))
```
I.e., single `=`, not `==`.  The `=` will get converted to `==` once it becomes Pyret.

(Scheme and languages with Lispy syntax use simply `=` for equals, as God intended. Pyret and languages with Algol-like syntax are forced to use `==` for equals because `=` is already used for assignment. Scheme uses `(set! ... ....)` for assignment so there is no syntax clash to avoid.)

If you really want it, I can make `==` translate as though you wrote `=`. Lmk.

**Comment by flannery-denny** [comment]
Danke
