### ISSUE TITLE
reduce vertical space that appears between lessons for @all-exercises

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2032]
You have to do a lot of scrolling to see the whole list.  It's also a big contrast to the table for @lesson-info, which is nice and compact.

Hoping this is possible!

**Comment by schanzer** [comment]
@retabak you and @flannery-denny explicitly told me NOT to do this, because you felt it was important for every lesson's row to be the same height. That meant we had to make every single-line list of starter files take up two lines, to account for the minority of cases where they actually NEEDED that vertical space.

**Comment by retabak** [comment]
You are thinking about @lesson-info, which look sgreat.

The request was for @all-exercises.

:)
