### ISSUE TITLE
@lesson-link inside @teacher needs to be @proglang-sensitive

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2042]
### Time sensitive - #1864 is BLOCKED on this issue.

In the histograms lesson, for example, there are @lesson-links buried inside @teacher:

@teacher{
But how do we talk about or describe that shape, and what does the shape actually tell us?

Our @lesson-link{visualizing-the-shape-of-data} lesson addresses these questions... and our @lesson-link{measures-of-center} lesson explores the effect of the shape of a histogram on the mean (average).
}
Both of these lesson have codap version, but in the codap version of _histograms_, these links point to the Pyret versions!

Present in:

- [x] histograms
- [x] measures-of-center
- [x] linear-regression
- [x] standard-deviation
- [x] scatter-plots
- [x] threats-to-validity
- [x] box-plots

**Comment by ds26gte** [comment]
`filtering-and-building` is indeed not available in codap, so a lesson-link to it from a codap lesson defaults to the pyret version.  I can certainly warn that it is not availabel in pyret, but this could be one of those annoying warnings. I think there are many cases where the referenced lesson is intentionally uni-lingual (default: pyret), but is referred to by lessons of other proglangs.

I remember we used to use `none` (rather than `pyret`) for a lesson that was supposed to be language-agnostic. I think the machinery is still there. Then I could skip the warning if the proglang.txt is empty or contains just `none`, but not otherwise.

**Comment by schanzer** [comment]
@ds26gte followup - actually, I _do_ see some places where this error occurs. In the histograms lesson, for example, there are @lesson-links buried inside @teacher:
```
@teacher{
But how do we talk about or describe that shape, and what does the shape actually tell us?

Our @lesson-link{visualizing-the-shape-of-data} lesson addresses these questions... and our @lesson-link{measures-of-center} lesson explores the effect of the shape of a histogram on the mean (average).
}
```

Both of these lesson have codap version, but in the codap version of `histograms`, these links point to the Pyret versions!

**Comment by ds26gte** [comment]
This error is happening only in the slides, ja?

**Comment by schanzer** [comment]
Ja
