### ISSUE TITLE
Changed ownership of published Pyret files and Desmos activities to teachersuccess@BootstrapWorld.org

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2049]
We have two problems with our desmos and Pyret files:

1. Our desmos files are all saved under an account that REALLY shouldn't have the password shared outside of JoJo and myself. We did this because we needed an account that wasn't linked to any one person, but we probably should have just made a different account for this purpose.
2. Our Pyret files didn't even get this love, so instead they're owned by a combination of all three authors. The problem is that when we click "publish" on a file owned by someone else, we wind up making a new published file instead of updating the old one. The only way to update the old one is to manually open the published file (owned by someone else), make the change, and click "save". None of this would be necessary if all the files were owned by the same account.

We only have 10 licenses for users through our Google Domain, and currently all 10 are in use. Fortunately, there's one address that can be re-used: teachersuccess@BootstrapWorld.org. Eric and Joy only use it as a the "from" field when sending emails, so we can absolutely recycle it for our purposes.

- [x] Change Desmos from admin to teachersuccess
- [x] Emmanuel changes ownership of his files
- [x] Flannery changes ownership of her files
- [x] Flannery changes ownership of all DS Datasets
- [x] Rachel changes ownership of her files

To transfer anything owned by flannery.denny@gmail.com, copies have to be made and links need to be updated in starter-files.js - this needs to wait for the 2025 release.

**Comment by flannery-denny** [comment]
It was a significant amount of work to track down both copies of current starter files since our process hadn't been standardized back when they were generated. 

While it's possible that I missed something, and you can ask if you discover that there's something missing that you think I could transfer ownership of... 

There are a number of files for which I either 
- could not find the OG or published file in my drive
- could only find 2 files that appear to be the published versions or 2 files that appeared to be the OG file

Which is to say, this process has resulted in a huge leap forward, but **there are definitely going to be some growing pains to get from the disorder we started with to a fully functional system** where any author can log in and resolve starter file issues.

**Comment by retabak** [comment]
I am happy to do the transfer of desmos files, once I can log in to desmos and the teachersuccess email. (Neither are available to me at the moment?)

I wanted to ask if y'all are okay with me just adding teachersuccess@bootstrapworld.org as an activity and collection editor. ([See details here.](https://my.amplify.com/help/en/articles/6792367-manage-editors)) Per my understanding, the only difference between the owner and editor is that the owner can delete an activity or collection, while an editor cannot. I think this seems fine? But perhaps I'm not thinking something through completely. 

Alternatively, I can make copies of the lessons and teachersuccess@bootstrapworld.org will be the *owner*, not editor. This would obviously be far more laborious - and could introduce errors - because we would need to change the starter file links. (Adding an editor would not result in a change in the URL.) 

LMK how I should proceed @flannery-denny @schanzer

**Comment by schanzer** [comment]
I'm totally fine with you adding teachersuccess@BSW as an editor. In some ways, I kinda like the idea that you need super duper admin privileges to delete things.

**Comment by flannery-denny** [comment]
Makes sense to me, but, I think we should be consistent. Currently we have a few Desmos files for Algebra 2 that are "owned" by teacher success. Once @schanzer is done working with them this week (and possibly updating them in the process?) we should make copies and store them in the other account. 

The most important reason for this is that people who like our stuff can explore the rest of our collection.

**Comment by retabak** [comment]
I'm not sure I understand why people who like our stuff wouldn't be able to
explore the rest is the collection?

I did think of one other idea...

via the Desmos Facebook group, I've heard of teachers who are switching
schools contacting Desmos to transfer ownership of their files from an old
school email to a new school email. Apparently desmos is willing to help
out in these situations. So. That's an option too?

**Comment by flannery-denny** [comment]
I trust you to sort it out @retabak. But, I think it makes sense for authors to always edit from the same account, and I would expect that to be teacher success.

**Comment by schanzer** [comment]
I think @flannery-denny is right, but in terms of prioritization I think this is less critical than starter files. Only spend time on moving desmos activities if (a) all of your own starter files have already been moved and (b) there aren't other July 1 milestone issues open

**Comment by retabak** [comment]
Okay! I believe that "transfer" of desmos activities is complete. I just added teachersuccess@bsw.org as an editor of each of the collections that admin@bsw.org owns.

If someone wants to check my work or make sure that I didn't forget anything, that would be lovely. It was shockingly easy and quick.

**Comment by schanzer** [comment]
@retabak it looks like the "CODAP Starter Files" folder in Fall 2024 is still owned by you. 

@flannery-denny it looks like the published cheerios starter file is still owned by you.

Otherwise we're good for Fall2024. I don't think we desperately need to change over older files.

**Comment by flannery-denny** [comment]
@retabak close when you're done

**Comment by flannery-denny** [comment]
I am not able to edit the logarithmic models file from the teacher success account. @retabak would love you to bring your Desmos expertise to solving this puzzle. Thanks!

**Comment by flannery-denny** [comment]
nm @retabak. I was able to add `teachersuccess@bootstrapworld.org` as an editor from the admin account :)
