### ISSUE TITLE
Block-level directive: @pd-slide{...}

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2057]
@retabak created a ton of amazing slides that synthesize recordings and reports of things we do in PD. Currently these live in the `lessons/Authoring/` folder, and I need to manually splice them into the lesson slides used in the master PD decks, remembering where they belong.

It would be _amazing_ if these were actually _embedded within the lesson.adocs themselves_, such that I could run `./build-slide --pd lessonXYZ` and get a link to the _PD version_ of that deck, with all the slides in the right place. This would also allow us to tighten the feedback loop between PD and authoring: a facilitator calls and says "I did this _awesome thing!_", and we can just update the asciidoc accordingly. It also lets us do some version control and tracking for institutional PD knowledge, which (until Rachel's heroic efforts) no one has ever actually collected).

(Note that this would also require adding more `slide-id.txt` files, for the PD version of things.)

**Comment by ds26gte** [comment]
Please claarify what is desired.  Are you asking for something like a `pd/` subdirectory in each lesson that contains its own `index.adoc` containing facilitator material) that would be converted into a slide deck (and presumably nothing else)?

**Comment by schanzer** [comment]
@ds26gte I've updated the description - let me know if this is more clear?

**Comment by ds26gte** [comment]
A couple comments on the current implementation: I made `@pd-slide{...}` become comment in HTML and regular slides, but active for PD slides.  Were you expecting `@pd-slide{...}` to introduce a `@slidebreak` surround its content, which is expected to be one slide? This may be tricky, as the process is 
```
index.adoc --> zlides.md --> slides.mkd
```
and I'm keeping the `@pd-slide` in `zlides.md`, translating it differently for non-PD and PD. So, the decision to ignore or not `@pd-slide`'s arg is done by `slides-preproc.rkt`.

(`preproc.rkt` wraps an CSS-based comment around `@pd-slide` content, because we may need its HTMLized content for image- and table-harvesting.)

**Comment by retabak** [comment]
@ds26gte - I just ran `./build-slide -pd ds-intro`, and the student-facing slide-id was updated, but no new PD slide-id appeared. Instead, it looks like it just overwrote the student-facing slide-id file.  Additionally, the `@pd-directive{}` content did not appear; rather, a blank slide was added where a new slide should have appeared.

**Comment by schanzer** [comment]
@ds26gte `./build-slide --pd -f histograms` currently fails to generate slides. It appears that whatever is passed to `md2googleslides` may not be parsing correctly. Possibly a result of passing `@strategy` verbatim?

**Comment by schanzer** [comment]
Confirmed working as of 7/24
