### ISSUE TITLE
Generate other google files from asciidocs

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2064]
This year we successfully asciidocified slide generation. Is it perhaps the first frontier of many?

What makes me ask is that 
- [ ] The Research Paper Template is a google file (make in markdown and turn to google doc by hand)
- [ ] The Dataset Exploration Project is a slide deck (talk to dorai about best way to work with this)
- [ ] Research Paper slides
- Does is make more sense to keep the semantic structure and figure out how to build a slide somewhere else or create a hack of adding the slides to the lesson plan?
- Noting that our other slide decks are viewer only and these slides are templates that we want to require people to make a copy of in order to interact with them.

And by keeping these files outside of our repository they are much harder to maintain.

**Comment by schanzer** [comment]
LOVE this idea, @flannery-denny!

I've tweaked the title and added checkboxes, because this really is a lovely idea. Here's what's standing in our way:

1. The slide deck is obviously lower-hanging fruit, but it's not easy. Our solution to md2googledoc's _terrible_ table conversion was to create our own pipeline that converts all tables as images, then makes slides with those images. This won't work at all for the research paper, so we'll either need to do the paper in raw markdown _or_ have Dorai create bypass mechanism that lets certain tables pass through to asciidoc. 
2. There's a project called pandoc, which converts asciidoc to ODT (which can be manually imported into gdocs). It's a rather large dependency and can't be easily installed via `npm`, so I'm hesitant to add it. Moreover, Google Docs secretly supports native markdown, so I'm tempted to say we just make a raw markdown file for the research paper and put _that_ in our repo. Definitely something to think about once summer is up and running.

**Comment by schanzer** [comment]
@flannery-denny I've been thinking about this today, and the tech lift required to do this is _enormous_. Given that these are only a few documents - and that our goal is to stabilize them to the point where they don't change much - this is likely an unachievable goal. I'd like to at least label this as "not urgent", if not close. What do you think?
