### ISSUE TITLE
build-slide chokes on 4th-level headings

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2095]
We almost never use them outside of some recent changes to Algebra 2, so it's no surprise this hasn't come up before.

In `exploring-linear-models`, the content around 4th level headers just doesn't show up in `zlides.md`.

- [x] These headers should be ignored by slides altogether
- [x] Once done, ES needs to bring them back to the Alg2 lessons.

**Comment by flannery-denny** [comment]
@ds26gte 
- In @schanzer's spec it says "4th-level headers should be ignored by slides all together"
- Your commit it titled "==== sections should become @slidebreaks"

Having read @schanzer's spec I inserted slidebreaks where I needed them in the box-plots lesson. When I built slides I got synthesize templates in the launch section.

I have resolved the issue in the deck I was working on by proscribing the template with each slidebreak, but this is a tricky thing for authors to catch.  please update lua so that `====` are ignored by slides so that authors can decide where to break slides and we end up with slides templates that correspond to the lesson section we're authoring in.

**Comment by schanzer** [comment]
@flannery-denny Dorai says he's tested this and it works the way you wanted. If so, can we close?
