### ISSUE TITLE
slides-preproc doesn't handle @define?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2097]
From `exploring-periodic-models`:

```
@define{COtwo}{@math{\mbox{CO}_2}}

[..snip some irrelevant asciidoc...]
Carbon Dioxide (@COtwo) is the gas inside the bubbles in a can of soda. It's what we breathe out when we exhale. In solid form, it's known as dry ice. It's also known as a "greenhouse gas", because it traps heat. When enough of it is in the atmosphere, it can make the planet warmer and warmer.
```

This works beautifully in the lesson plan, but in the slides we get the literal characters `@COtwo`. I suspect that the @define directive simply hasn't been ported to slides-preproc.

**Comment by ds26gte** [comment]
The `@define` occurs in the part of `index.adoc` that is skipped over when creating the `zlides.md`.  Repeating the definition at a place that is indeed carried over (it need only be done once) is a solution.

Moving it from a `==` location to an `=== Overview` section is not enough, as the latter is also skipped. You may still need two copies of the `@define`, because this ignored sections may use it (as in this case), so you still want its effect for the HTML.

**Comment by schanzer** [comment]
Oh! That makes total sense. Will fix now.
