### ISSUE TITLE
Custom Pathway glossary is showing everything

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2101]

**Comment by retabak** [comment]
I think that actually *all* lesson glossaries are showing everything? I just checked for three different lessons.

https://www.bootstrapworld.org/materials/fall2024/en-us/Glossary.shtml?lesson=simple-data-types
https://www.bootstrapworld.org/materials/fall2024/en-us/Glossary.shtml?lesson=defining-values
https://www.bootstrapworld.org/materials/fall2024/en-us/Glossary.shtml?lesson=histograms

One additional (tiny) related request: Can the lesson table say "Lesson Glossary" (both words capitalized) rather than "Lesson glossary"

**Comment by schanzer** [comment]
@retabak sorry about that! fixed.
