### ISSUE TITLE
Check exploring periodic models unit for correctness

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2130]
Review the [exploring periodic models](https://bootstrapworld.org/materials/fall2024/en-us/lessons/exploring-periodic-models/index.shtml?pathway=algebra-2) unit and make a checklist here of any pages whose solutions need to be fixed. Please add screen shots and links to the pages.

**Comment by schanzer** [comment]
Hi @joystraub - I know we spoke about this a while back, but I never formally assigned you to the issue. Think it's possible to sit down and work through the Periodic unit in the next week or so?

**Comment by joystraub** [comment]
Yes - I will do this the first part of this week.

**Comment by joystraub** [comment]
- [ ] Reasoning About Unit Clocks Workbook page - Question 1 - I was a little confused at what it was asking at first. Perhaps add language that asks "and the length of r is _____?" Question 2 - How would students know to go negative with the values of A & B 6:00 and 9:00 and again for values in question 4? Nothing is ever said about that. Just wondering if that should be explained before they fill in this chart. Question 3 - I was confused about 1:30 for a bit - perhaps noting the clock is showing the short hand position? Questions 7 & 8 - they say x(time) and y(time), but Desmos uses a(time) and b(time), while the lesson uses A(time) and B(time).  There should be consistency.  All of these should be A & B.
- [ ] Lesson Plan section on Radians - would it be possible to add a side section of that paper circle activity where students discover what a radian is?  It is powerful.  It shows that it does not matter what the size of the circle is.  It still takes 2pi radians to get around the circumference. They see it takes just a few more than 6 strings the length of the radius to go around the circle. It made something very abstract a little more concrete.
- [ ] Graphing Periodic Models; Amplitude (a) workbook page - Question 1 - Adjust the sliders to fit.... fit what? I figured it must be to fit the graph made by the blue dots, but it might be clearer to explain that?  Is this the ferris wheel graph?? "Adjust the sliders to fit the data to the given blue ferris wheel graph." (Just a suggestion because it took me a while to figure out what I was doing - it might be the same for others.)
- [ ] Graphing Periodic Models: Frequency (b) workbook page - Question 4 in the answer key says 10 - I believe it should say 10pi. Question 5 - the last answer in the key has "doubles" misspelled.
- [ ] Words for Describing Periodic Functions workbook page - In the answer key for Period it says "this will always be 2pi." Should this say - "it will always be 2pi/b"??  It will not always be 2pi when b is not 1.
- [ ] Lesson Plan where it talks about the periodic function words, it shows Period = 2pi all divided by frequency,

**Comment by joystraub** [comment]
My fat fingers accidentally closed the issue before I was done typing all that in - so I reopened it to finish.  I went through each lesson and workbook page looking at the answer key, as well.  Some boo-boos to fix and some suggestions for you to chew on.

**Comment by schanzer** [comment]
@joystraub thank you for looking into this, and your great feedback! I've addressed most of the issues.

1. I'm not sure I understand your concern about "Graphing Periodic Models; Amplitude (a) workbook page". The sentence you mention literally says "adjust the sliders to fit the data", and the instructions at the top of the page say "modeling the ferris wheel dataset". I've shifted the formatting a bit to make that stand out more, but I'm just not seeing the problem with how the sentence is written.
2. I edited your comment to separate the suggestion from the correctness issue. There's a whole section in the lesson plan where students need to think about how many "radian slices" will fit in a pie. Isn't that the same thing you're suggesting? let's discuss on slack or in a call.

**Comment by joystraub** [comment]
1. Maybe I was just slow or tired - but it took me a while to understand the blue dots on the Desmos were modeling the Ferris Wheel activity already.  We just had to fit an equation to it. So I was just suggesting that you add something to that affect here for those of us who were trying to figure out what we were looking at and were a little slow at understanding it. 🥴I figured it out - but not at first. I thought I had to just start creating an equation from scratch from the data that would take on a form like the one on the graph.  But maybe others will not be as misunderstanding as I was.
2. I went through that section - it is not the same as understanding what a radian is.  When students cut the string the size of a radius and wrap it around the circumference, the physically see it and notice it for circles of different sizes - how it works the same no matter the radius. It is more of the Bootstrap approach of discovery than the approach here of being told there are a little more than 6 pieces. Just a thought.  It is a great enrichment activity to offer teachers. I would never teach radians without it again after using it. It made all the difference.

**Comment by schanzer** [comment]
@joystraub I've added the kinesthetic activity AND revised the instructions on that workbook page. [Let me know what you think?](https://bootstrapworld.org/materials/fall2024/en-us/lessons/exploring-periodic-models/)

If you're happy with these changes, feel free to close the issue!

**Comment by joystraub** [comment]
Looks good!!
