### ISSUE TITLE
Second level bullets from lesson-instruction aren't rendering in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2144]
I'm on the `boxplot` branch in the `box-plots` lesson plan and slides.

Here's the asciidoc:
```
@lesson-instruction{
- Let's see what we can learn by looking at a dataset of the ages from the *Ledet Family Reunion*: +
1, 44, 3, 42, 46, 74, 75, 21, 74, 70, 40, 41, 45
  * Rewrite the data on your paper in order from least to greatest.
  * Record your five-number summary (Minimum, Q1, Median, Q3, Maximum).
  * Then calculate the IQR and Range.
- When you're done, repeat the process with the *Watson Family Gathering* age data: +
70, 68, 69, 72, 65, 75, 65, 78, 70, 72, 71, 70
}
```
Here's how it renders in the lesson plan:
<img width="823" alt="Screenshot 2024-08-12 at 3 02 06 PM" src="https://github.com/user-attachments/assets/e58e4a20-a839-457a-9b14-65a8196392c4">

Here's how it renders in the slides:
<img width="884" alt="Screenshot 2024-08-12 at 3 01 52 PM" src="https://github.com/user-attachments/assets/50c8bf0e-50c5-493e-bd06-e19574ec764d">

Can we make the slides look more like the lesson plan on the back end or do I need to get more creative with my asciidoc content in order to make the hierarchy visible?

**Comment by schanzer** [comment]
@flannery-denny the problem here is that the list of numbers is on its own line, which tells Google Slides that the list is over. As a result, GSlides treats the next set of bullets as a _new list_, ignoring the fact that they're on a separate level.

I'm afraid you will need to move those number to be on the same line as the bolded text that precedes them. Here's what I get from that:

![image](https://github.com/user-attachments/assets/0ff9f838-37d6-44c0-be6f-f761854cef09)

**Comment by flannery-denny** [comment]
@schanzer I propose we implement a longterm fix in which the slides preprocessor detects the use of `+` at the end end of a line in a bulleted list and removes the line break.  Will let you determine the feasibility of that. And will resolve this particular instance with the info that you have shared.

**Comment by schanzer** [comment]
@flannery-denny Dorai has made the change to build-slides, I've restored the `+`, and confirmed that it does not mess up the slides :)
