### ISSUE TITLE
reorganize starter-files.js

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2165]
This work is to be done on a `starter-files` branch.

We need a `starter-files` folder in `shared/langs/en-us`.

In the folder we would like the following files:

- [x] editors
- [x] algebra
- [x] algebra-desmos
- [x] algebra2
- [x] algebra2-desmos
- [x] core
- [x] data-science
- [x] data-science-desmos
- [x] early-math
~-[ ] hour-of-code~
- [x] projects
- [x] reactive

Those files will be formatted like the `starter-files.js` file.

In the end, all of these files will get stitched together to do the same work that the current  `starter-files.js` file is doing.

For example, Algebra will still contain something similar to

> const allStarterFiles = {
>   ...Flags, 
>   ...GameBasics, 
>   ...MoreAlg,
> }
> 

The goal of this issue is to make the file(s) more manageable for authors to interact with.

Once Dorai has set up the files, authors will be responsible for populating them with the appropriate files.

**Comment by flannery-denny** [comment]
@ds26gte I can't remember. Did anything happen with this yet?

**Comment by retabak** [comment]
The json files in starterFiles are incorrectly labeled!
Someone will need to do a lot of copying / pasting to reorganize the files once the are correctly named. (I'm happy to take this on.)

**Comment by flannery-denny** [comment]
@retabak If I understand correctly, you are flagging that the files in the folder are the original groupings rather than the ones named per the spec?  If so, could you please add the files that you are expecting to see so that any new files will be added following the correct logic.

Once that's done, please:
- clear the milestone
- label the issue not urgent
- remove your assignment

Let's save the copy and paste work for the future when we don't have so much on our plates. Or for a moment when someone's brain can't focus on more important things.

**Comment by ds26gte** [comment]
JF everyone's I, the names of the JSON files in the `starterFiles`, `learningObjectives`, and `assessments` directories don't matter to the program. They are for human delectation only. Every JSON file in those directories will be picked up regardless of name.

**Comment by flannery-denny** [comment]
@retabak Closing because it looks like ES has completed the spec. If you had something else in mind, please let us know what you think is missing.
