### ISSUE TITLE
make and populate misconceptions dictionary

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2173]

**Comment by flannery-denny** [comment]
@schanzer would love your thoughts on this draft

**Comment by schanzer** [comment]
@flannery-denny done!

**Comment by flannery-denny** [comment]
@schanzer I've reviewed your comments. 
- In our initial review of misconceptions, before we finish building out an autochecker, I would like the author to 
-- declare whether or not they believe we address the misconception. We definitely already address some!
-- declare whether it is something we could address in an existing lesson or they believe merits a new lesson
- As I understand it from looking at the `glossary-tems.json` file
`[[ ]]` is a more robust form of declaring an array using `{}` in that it can handle both single and multiple entries, which `{}` is not able to do. 
-- @ds26gte Is this true?!
-- I have pushed a commit that splits what I believe to be `[[ ]]` arrays onto multiple lines in hopes that that reads more clearly?
-- If my formatting ideas don't make sense, I am empowering either @ds26gte or @schanzer to please push a fix!

**Comment by schanzer** [comment]
@flannery-denny If a misconception is addressed, I would rather the author have to point to _a specific place in the lesson_ where it's addressed. That's the whole reason we want the dictionary in the first place! Rather than writing `true`, they author should have to say where. Let's have this be a string for now, so the author can write down where they think it's addressed.

`{}` is a dictionary. `[]` is an array. `[{},{},{}...]` is an _array of dictionaries_, and `[[],[],[]...]` is an _array of arrays_. I think you want an array here.
