### ISSUE TITLE
shouldn't we define "validity" in the threats to validity lesson?!

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2181]
The overview for the first section states that "students are introduced to the concept of validity" - and I don't think that's true!

Given our recent work/thinking around objective writing, our failure to define this term made me giggle;  the first definition I encountered was  "whether a test measures what it aims to measure".  (I know that this is not the definition that we are looking for / should use.)

We could of course get into reliability and accuracy when addressing this topic, but that's probably too in-the-weeds for our purposes.

ETA: As I continue to read this lesson in effort to pin down clear objectives, I'm recognizing that:

- We *never* provide a real definition of "confounding variable." 
- We define "selection bias", but it is not in the glossary.
- We provide one example of "bias in the study design," but never define that, either. (Bias in the study design definitely goes beyond using a loaded question, which is the single example we offer.)

**Comment by flannery-denny** [comment]
@schanzer Here's a stab at some of the definitions Rachel is looking to see added to the glossary

**validity:** the degree to which a tool measures what it is supposed to measure and the degree to which conclusions drawn from the data gathered are reasonable and supported by the data
**selection bias:** bias introduced during the process of selecting individuals, groups or data to be analyzed that fails to ensure that the sample obtained will be representative of the population intended to be studied
**confounding variable:** an unstudied variable that influences both the explanatory and response variables, and has the effect of confusing proper interpretation of the relationship between them

I'm not sure that bias in the study design is something we should define since there are so many ways for a study to be poorly design. Two other examples that seem easy for students to make sense of include 

- question-order bias: respondents are primed by previous questions when responding to a later question. That priming could include providing information, points of comparison that influence rating on a scale, or emotional response.
- culture bias: researchers often judge other cultures on the standards of their own culture

**Comment by retabak** [comment]
Thanks for taking a go at this, @flannery-denny !

- validity - I think we could probably delete the first chunk - "the degree to which a tool measures what it is supposed to measure." I think of that definition falling under the umbrella of assessment/ measurement / evaluation, and not so much statistics/ data science as we define them.
- selection bias - the phasing of your definition was really difficult for me to parse; how about "the selection of individuals, groups, or data that do not represent the population under study, leading to inaccurate findings"
- confounding variable - I might prefer using "unaccounted for variable" rather than "unstudied variable"

I like the two additional examples of bias in the study!

**Comment by flannery-denny** [comment]
@retabak I will be curious what @schanzer has to say, but I think it's critical for the definition of validity to include both parts. Selection bias would fall under the first. And using an unrepresentative measure of center would fall under the second.

**Comment by schanzer** [comment]
@retabak I agree with @flannery-denny : we need both parts

**Comment by retabak** [comment]
@flannery-denny - sorry I didn't check the glossary! Totally did not occur to me.
