### ISSUE TITLE
improve linkcheck

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2195]
FD believes `make linkcheck` should automatically `make clean` before it starts.  When an author runs linkcheck they are dotting their is and crossing their ts. But linkcheck is checking a file that isn't necessarily up to date, causing stress and wasting time as a result.

@schanzer please confirm your agreement.

**Comment by schanzer** [comment]
@flannery-denny adding context from our Slack discussion here:

I do NOT agree with this proposal. The task of fixing links often involves small, incremental changes to 1-2 files at a time. It is almost exclusively run prior to deployment, when `make clean` should be used anyway. The fact that this has been the behavior for 3 years and no one has ever noticed suggests that for common cases the behavior is fine.

The only reason this came up just now is that:

1. A large, messy merge was completed
2. Despite this, `make clean` wasn't run (it should have been!)
3. `make linkcheck` was used without the intention of deploying, which is in and of itself uncommon

This situation is highly unusual, and really shouldn't have happened at all. 

This proposal would make `linkcheck` 10x slower for the common case, in order to prevent totally-understandable problems in the uncommon case.

**Comment by flannery-denny** [comment]
@schanzer I don’t have power to veto you on this kind of issue, so if it’s not worth discussing, please just close. That said your opinion feels nonsensical to me and I don’t understand where the major slowdown you fear happens. I have a much slower computer than yours and it takes me very little time to make clean and then make book. I often have to do it many times an hour. Since make linkcheck doesn’t even require books to be made, making clean first should have very little impact on time while ensuring that the list generated is always accurate. You describe your work flow for deployment as beginning with make clean before make linkcheck. Why not combine them?I generally run linkcheck when I do a major merge because I know you will have to deploy and don’t want to cause issues. I hear you that I could and should run make clean, but I don’t do it often enough to have muscle memory so I usually forget to run make clean first having -  just made clean and remade book several times to confirm I don’t have any page overflows- just referred to documentation which I misinterpret to think the full command line is ‘linkcheck’ and already am distracted by the messages I’ve received about its nonexistenceWhen I get a giant list I usually stress out and think something is totally broken in the build system and disrupt everyone else’s work flow. Since your head was in another space when I reached out about the last round of broken links, it did not occur to you to ask whether I had made clean even though the broken links were not from the work I had just merged. I don’t think the time you’re talking about saving is worth the time and energy being wasted.I am fairly confident that you have also forgotten to make clean before running linkcheck and raised questions about broken links that were actually working, but I don’t think it’s worth my time to review the entire curriculum remix history in order to know for sure.FlanneryOn Sep 25, 2024, at 10:47 AM, Emmanuel Schanzer ***@***.***> wrote:﻿
@flannery-denny adding context from our Slack discussion here:
I do NOT agree with this proposal. The task of fixing links often involves small, incremental changes to 1-2 files at a time. It is almost exclusively run prior to deployment, when make clean should be used anyway. The fact that this has been the behavior for 3 years and no one has ever noticed suggests that for common cases the behavior is fine.
The only reason this came up just now is that:

A large, messy merge was completed
Despite this, make clean wasn't run (it should have been!)
make linkcheck was used without the intention of deploying, which is in and of itself uncommon

This situation is highly unusual, and really shouldn't have happened at all.
This proposal would make linkcheck 10x slower for the common case, in order to prevent totally-understandable problems in the uncommon case.
