### ISSUE TITLE
Add dot plots to pyret library

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2205]
Here's what they look like / how we teach about them in CODAP:
[https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/codap-dot-plots-bar-charts-codap/index.shtml?pathway=false]( https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/codap-dot-plots-bar-charts-codap/index.shtml?pathway=false)

Added spec from Emmanuel:

We should add a `dot-plot-series` type, with fields for `labels` and `color`. If the data is categorical, the labels should be processed in the order they are given. If the data is quantitative, the min and max values should define a standard x-axis. For each location on the axis (or each label), the number of matching values should be represented as solid circles of whatever `color` was specified. Resizing the chart window should stretch the axes, but not deform the circles into ellipses.

**Comment by ds26gte** [comment]
I think this is a code.pyret.org issue since that's where this code would go

**Comment by ds26gte** [comment]
I've made a PR for this in

https://github.com/brownplt/code.pyret.org/pull/554

The corresponding CPO issue is https://github.com/brownplt/code.pyret.org/issues/469

Please follow developments there.

**Comment by ds26gte** [comment]
Since we want to generate dot plots for numerical x (in addition to categorical), and since the input type is different (list-of-numbers vs list-of-strings), so we want two separation dot-charts functions?

**Comment by flannery-denny** [comment]
Great question @ds26gte!
My first thought was couldn't we hide that under the hood... but, since we provide students with the contract for the function, and the domains are different, we probably need to reveal that there are two separate functions?

@schanzer @retabak What do you think?

- `dot-plot-num` and `dot-plot-string`?
- `dot-plot-quantitative` and `dot-plot-categorical`?  _(`dot-plot-cat` seems confusing)_
- `dot-plot` and `dot-plot-num`?

**Comment by ds26gte** [comment]
- Could you give an example of how the input data (list) is provided? I take it this isn't like a histogram where an input data point is repeated
- Can I assume that the input data list is ordered?
- Should I infer a bin size based on the range of input, or is it always 1? (In other words, is a numerical dot chart simply a categorical dot chart where the inputs happen to be numbers rather than strings. I guess not, as that could be have been solved with a wrapper that casts a number list into a string list)

**Comment by retabak** [comment]
Okay, I've done some more research, and I think we should *only* have numerical dot plots. While obviously one *could* make a categorical dot plot, I don't think there's any real reason for us to do so. The dot plot is intended as a stepping stone to histograms, and is useful because we can use it to think about center and spread. Also, Illustrative Math says that it is a numerical display. So, that solves one problem!

Regarding your questions, @ds26gte ....

I have a feeling there's something I don't understand about how input data is provided for histograms. In Pyret, the user just provides a column name (but perhaps this is because of @schanzer's teachpack?). That's what I was hoping would happen for the dot plots, too. Suspecting it would be best for @schanzer to weigh in here.

I'm confused about the bin size question, because there are no bin sizes? Here are some dot plots that were made in CODAP, all from the Animals dataset. (I do hope our dot plots will look somewhat similar.)

![image](https://github.com/user-attachments/assets/e5db7716-d139-4727-af73-de33043430db)
![image](https://github.com/user-attachments/assets/a1cfa385-1977-43c3-9e90-2c1c43cf53b7)
![image](https://github.com/user-attachments/assets/4b729a72-e088-4874-97df-25180cdb790a)

**Comment by ds26gte** [comment]
What we call "bar chart" Google actually calls "column chart". So, yes we can easily get what Google calls "bar chart", i.e., where the x axis is vertical

**Comment by ds26gte** [comment]
> Regarding your questions, @ds26gte ....
> 
> I have a feeling there's something I don't understand about how input data is provided for histograms. In Pyret, the user just provides a column name (but perhaps this is because of @schanzer's teachpack?). That's what I was hoping would happen for the dot plots, too. Suspecting it would be best for @schanzer to weigh in here.
> 
> I'm confused about the bin size question, because there are no bin sizes? Here are some dot plots that were made in CODAP, all from the Animals dataset. (I do hope our dot plots will look somewhat similar.)
> 

Pyret's histogram takes a list of numbers, in no order, and generally with repetitions.  It then charts from the lowest to highest number, with the corresponding y lengths proportional to the number of that x's occurrences.  Furthermore, it bins the x's into some convenient size, so each bin's y length is proportional to the sum of the occurrences of all the x's within that bin

**Comment by ds26gte** [comment]
I've added `num-dot-chart` to the PR https://github.com/brownplt/code.pyret.org/pull/554.

FYI: orthogonal to this, I've noticed that adding the method `.horizontal(true)` doesn't quite work -- it replaces the bar with an ugly single ellipse rather than replacing it with an appropriate number of small circles. I will need to change my SVG mungeing to adapt correctly to horizontal bar charts. 😦

**Comment by schanzer** [comment]
@retabak [here's a demo of the dot plot implementation](https://pyret-horizon.herokuapp.com/editor#share=1N1ct-vJBCzL8m16ifyPSME3lFuZwerXm)

FYI - the colors are customizable, but I'm not sure if the dots are. @ds26gte can weigh in on it. Please leave your feedback here!

**Comment by retabak** [comment]
Hi, @ds26gte ! This is getting closer! The dots look beautiful :)

I'm observing some other issues, however. 

The motivation for teaching about dot plots to use them as a stepping stone to box plots and histograms,. This means that students need to be able to students need to be able to see gaps on dot plots + we need a consistent interval size on the x-axis.

Right now, the dot plot and histogram for weeks do *not* have the same shape (see below). They need to!

![image](https://github.com/user-attachments/assets/3ff887fb-4b37-4bde-a4a1-5114c8f6452f)

![image](https://github.com/user-attachments/assets/2f1c3d43-7ae1-45cf-8bf7-8b912da0e269)

Then, one more image: There is definitely something weird happening in this dot plot for pounds. The y-axis needs to use whole numbers, as it shows count. (The x-axis is not allowing students to see shape, also.)

@schanzer - if you have anything to add or if I'm explaining poorly, please chime in!

**Comment by flannery-denny** [comment]
@retabak looks like @ds26gte has made some improvements based on your feedback. Please test it out. Thanks!

**Comment by retabak** [comment]
Hi, Dorai! Just checked out the newest version and am still seeing some problems. Here's the dot plot for weeks: 

![image](https://github.com/user-attachments/assets/24db4279-1d1c-430e-af28-70a773e6c29b)

  - As Emmanuel pointed out, the first value on the x-axis is -2. There are not any animals that are adopted in -2 weeks.
  - The horizontal position of the dots is not what I would expect. For instance: in the dataset, there are 4 animals that are adopted in 4 weeks, but the dot plot displays that 15 animals are adopted in 4 weeks.  
  - The vertical position of the dots is also not what I would expect. In the dot plot above, it look sas though 0.5 animals and 1.5 animals were adopted in -2 weeks. I would expect the dots to be positioned at a height of 1 and 2, not 0.5 and 1.5.

Let me know if any of this is unclear! And, in case it's helpful, here's a histogram with a bin-width of one (which reflects how the dot plot *ought* to look. Notice that the tallest bar goes only up to 6, but on the dot plot, there are 15 dots stacked over the same x-value.

**Comment by ds26gte** [comment]
Could you give me the list of x's and list of y's for the sample numeric dot chart that you're using? It's probably an exercise you're using that's already in the curriculum, in which case if it's easy for me to extract just the relevant data, you can just point to the place and I'll do the needful

**Comment by retabak** [comment]
Yep! Here's the link to the CODAP starter file: https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FF68tyYBcf1ri9yLFpVcO%2Ffile.json

Let me know if you need more direction on building the dot plot there.  (There is some instruction in [this lesson](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/codap-dot-plots-bar-charts-codap/index.shtml?pathway=data-science-codap).)

**Comment by schanzer** [comment]
@ds26gte I took for granted that you'd expose the `.x-axis` and `.y-axis` methods for dot charts. But I just tried setting axis labels and I'm getting this error.
![image](https://github.com/user-attachments/assets/9465f719-2070-45bd-b629-1642128268ac)

Can you expose those methods on the ChartWindow?

**Comment by schanzer** [comment]
@retabak axis labels were actually working all along! This was my fault. Closing!!!🎉
