### ISSUE TITLE
Change count to frequency in lesson plans and workbook pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2293]

**Comment by schanzer** [comment]
@retabak @flannery-denny right now this EXCLUSIVELY happens in histograms. Confirm?

**Comment by retabak** [comment]
Yeah, I think so - unless someone else can think of a reason why not. (I did poke around in the literature and was able to find plenty of statistics education articles that discuss frequency on bar charts. Couldn't find any discussion of pie charts, probably because no one is studying pie chart instruction.)
