### ISSUE TITLE
Possible bug in parsing of directives which contain two-colons

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2313]
At first I thought it was just this instance in the Tables, Rows and Visualizations lesson in the `contracts-and-lookups` branch.

> adoc: `Fill in the blanks with the code you'd write: @fitbruby{8em}{@ifsoln{count}}{function-name} (@fitbruby{18em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{14em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String})`
<img width="985" alt="Screenshot 2024-12-11 at 2 20 05 PM" src="https://github.com/user-attachments/assets/03992f58-e194-4f90-8ac2-b75345d51781" />

But now I'm seeing this in the Lookups lesson

> adoc : `@A{@show{(contract 'row-n '(Table, Number) "Row")}}`

<img width="377" alt="Screenshot 2024-12-11 at 2 17 52 PM" src="https://github.com/user-attachments/assets/3c15c0e4-da74-4146-896e-78afca772408" />

**Comment by schanzer** [comment]
@flannery-denny in your lookups example, you shouldn't have a comma (that means "unquote" in Racket!)

**Comment by schanzer** [comment]
@flannery-denny the issue is all about `{two-colons}`. 

In asciidoc, `::` means something _semantic_. We want it to be _syntactic_ (literally showing two colons!) Fortunately, asiidoc offers a way out of this: `{two-colons}`.

Unfortunately, on this page, all of this is happening inside a directive (`@fitbruby`), and the directive is parsed by Racket. Racket isn't sure what to do with it, so it strips the curly-braces and sends asciidoc the literal word `two-colons`. 

SHORT TERM FIX: we can actually use `::` here!
LONG TERM FIX: @ds26gte will need to update the directive parser to pass `{two-colons}` through without stripping the braces

**Comment by ds26gte** [comment]
EVEN LONGER TERM FIX: Correct the two syntactically erroneous occurrences of `@fitb{}` without a second argument. I've assumed the second argument is `{}` and pushed.

**Comment by flannery-denny** [comment]
fyi @schanzer - I didn't write the asciidoc that generated either of these issues. I just caught their output issues in my review.
