### ISSUE TITLE
Dedicated lesson for debugging

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#247]
- [x] Explicitly point students to Bug Hunting exercise
- [x] Have students look at buggy design recipes

**Comment by flannery-denny** [comment]
@schanzer 

**Higher order feedback:**

Overarchingly, the idea that there are three different kinds of errors and the explanation of the difference between them is clear.

The bug hunting starter file is very satisfying to complete, but doesn't lend itself well to discussion about the error messages because by the time you're asking the reflection questions the errors have already been resolved and there's no record of process. I see it more as a summative exercise rather than something that goes as the lead up to a conversation. Making a workbook page similar to contract errors would engage students with the editor but leave them with a record of the expression with the error and the error message.

In syntax errors you offer a matching exercise - this could be completed with or without computer access.
In contract errors the workbook page is fill in the blank, requiring computer access.
Is this distinction intentional?
Perhaps there should be one of each for each section?

**Zoomed in feedback**
- why say "missing parens" instead of "missing parentheses"?
- I'm not sure what this sentence in the launch of contract errors is trying to say "With no syntax errors, the computer and read our code and try to run it.
- I am struggling to fix the formatting so that the lesson point that belongs on the line after the second bullet doesn't end up on the line with the bullet as it currently appears.
![Screen Shot 2022-03-11 at 11 12 39 PM](https://user-images.githubusercontent.com/66691020/158005205-b309c0ce-1987-4bec-ab34-462f979a0c53.png)
- The Contract Error launch with the three examples feels rough. There isn't much here to jog their memories and they don't have hands on keys. It would be more gentle if they were given the code on a page that they could look at and consider, respond to in writing in prep for conversation, and elect to type into the editor for support. Even as someone who works in pyret regularly, I can tell that the use of quotes is inconsistent, but I don't have a context off the top of my head for why anyone would be typing  `"true" or false` in the editor, nor do I know what the error message would be.

**Comment by schanzer** [comment]
@flannery-denny Thanks for this! I've fixed most of the issues. ("Parens" is short for "parentheses", and used often by programmers. I forgot it's not commonly used elsewhere!)

I don't think a matching exercise makes sense for Contract Errors. We would need to use the exact same text for every entry on the right ("broken contract!"), OR it would have to have specific text like the solutions we have here ("string-length expects a string!"). But that text mentions the functions by name, so matching is just a matter of seeing which functions are named in which errors -- no thinking required. Is there another kind of matching activity that you have in mind?

Added a WB page to accompany bug-hunting, and also broadened the bug-hunting starter file to include some contract errors.

**Comment by flannery-denny** [comment]
@schanzer The issue is that it's hard to identify a contract error if you don't know the contract... If we are sure that all students will have contracts for all of these operations / functions, the directions could refer them to consult their contracts page. Alternatively, we could provide contracts for each of these examples on the worksheet itself (which might be more straight forward).

Alternatively, here are drafts of matching options for each of your examples
1 + "Maya"  _the operator requires input types to match_
(​3 > 0​) and (​1 + 2​)  _Boolean and number are used in place of 2 Booleans_
"true" or "false"  -> _strings are used in place of Booleans_
string-length​(​52​) -> _the function is looking for a string and none is given_
rectangle​(​"solid", "blue", 6, 7​) -> _arguments are used in the wrong order_
circle​(​20, "red"​) -> _some arguments are missing_
star​(​20, 50, "solid", "red"​) -> _too many arguments are given_


**Question:** We don't list operators on our contracts page in pyret because they're not functions. If they don't have contracts, how can the error be a contract error?

**Missing workbook page:** The lesson directs students to refer to a page called `fix-the-code.adoc` that doesn't exist.

**Comment by schanzer** [comment]
@flannery-denny thanks - I really like your not-too-specific-but-not-too-vague contract error prose! I've pushed those updates to the page. Also fixed the link to `fix-the-code`, which I renamed `what-kind-of-error`.

I think it's reasonable to assume every student will have access to the contracts pages - that's very much a core requirement of any pathway.

**Answer**: all mathematical functions have contracts, and all operators are mathematical functions. The term "operator" has nothing to do with math per se -- it's just a special word to describe a handful of functions that go _between_ their inputs, instead of in front. And a rose, by any other name...

**Comment by flannery-denny** [comment]
Then why don't we include the operators in the pyret contracts?

**Comment by schanzer** [comment]
@flannery-denny Not sure if you saw the comment above. OK to close?

**Comment by flannery-denny** [comment]
@schanzer 
- I would suggest adding some guidance for teachers in the synthesize sections on what kinds of answers you might expect.
- The contract error page build is totally messed up on my machine. If it looks good on your end and the solutions work, it's ok to close.
