### ISSUE TITLE
Request for bigger workbook font in data science workbook

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#284]
We were looking at page 8 and I asked if there was a space between either and true. Fixed!

But they immediately said that they wished the font were larger.  "And not just because I'm old, but because I work with students with disabilities and sometimes the font being just a little big bigger makes a huge difference."

**Comment by schanzer** [comment]
DEFINITELY. Changing the font size has to be done carefully, because it can mess up the formatting of other things (like design recipe pages, tables whose columns are now too narrow for the larger text, etc). 

I can work on this later tonight, but I'll need your help eyeballing the workbook to make sure it still looks ok!

**Comment by schanzer** [comment]
Font size has been increased.
