### ISSUE TITLE
Questions re: code for mathematical expressions to be translated to circle of evaluations

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#318]
Students struggle to remember that multiplication comes before addition. None of the problems in the currently available circle of evaluations materials support students in thinking this through because they include mathematically unnecessary parentheses in the expressions. 

I haven't gotten rid of the parentheses because it looks to me like the coding that turns these expressions into circles and printed code is the root of the problem... that the computer needs the parentheses for the things it's going to do to generate the solutions...

Is there a way around this? The materials would be much richer if we could fix it. And it's why I made my own materials for my students to make circles and code from when I was in the classroom...

**Comment by schanzer** [comment]
We use the `sexp->coe`, `sexp->math` and `sexp->code` functions to make our lives easier, since we can generate all three representations from the same racket expression.

But we don't _have_ to use them! For example, you could always just write `@math{6 + 4 * 9}` to generate a math expression without the parentheses. I'm all for adding some exercises that are written this way!

**Comment by flannery-denny** [comment]
Cool. I’ll work on that. 
I also want to add some more styles of problems that include division. Might need help w coding. Should know by Monday afternoon.


> On Aug 1, 2020, at 7:22 PM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
Assigned #318 to @flannery-denny.
