### ISSUE TITLE
Google Import cleanup issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#358]
**Design Recipes**
- [x] Section headings need to be formatted as such (single-cell tables with the class `.recipe_title`)
- [x] .recipe_directions need to be italicized
- [x] Invisible M's for design recipe need to be underscores (most likely 2 underscores for each letter)

**Other pages**
- [x] Document-wide font settings are needed
- [x] Vertical space needs to be preserved. Maybe some kind of `@vspace{Xex}` -> X repeated `<p/>`s?

**Comment by ds26gte** [comment]
1: I think we're relying M is supposed to be a font-agnostic way of getting an exact space width. Maybe I can turn the M to underscore just for the Google-import file?

2: I assume `@vspace` and some other abutting vertical spacer are not additive because of the way margins are combined? Do you have an example file that I can use to investigate?

**Comment by schanzer** [comment]
1: underscore is exactly what I was thinking of. :) 
2: [See this page](https://www.bootstrapworld.org/materials/fall2020/en-us/courses/algebra-wescheme/lessons/alg-function-composition/pages/composing-image-functions.html).
