### ISSUE TITLE
Probability lessons (branch off of random sampling in DS?)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#396]
For Oklahoma (see #354)

- [x] WeScheme-ify starter files
- [x] make slides

**Comment by schanzer** [comment]
From Joy Straub - combinations and permutations are important. Goal: given a word problem, students can (1) identify possible outcomes and (2) give the probability on a scale of 0-1.0

**Comment by schanzer** [comment]
@flannery-denny the lesson is now ready for review -- I haven't made slides OR worked in the starter file yet. For now I need feedback on the text of the lesson, the examples used, and the associated pages. 

There's a strong possibility this is going to need to be broken up into two lessons. What do you think?

**Comment by flannery-denny** [comment]
@schanzer Context is really strong. And the storyline is narrated compellingly. Nice work. It's a lot for one day!
- [ ] permutation worksheet: remove extra "can" from #5 
- [ ] combinations page: in #4 change 7 to seven because it looks like there's a decimal point
- [ ] the pizza looks delicious. Did you make it?! And there's no pizza on your menu...
- [ ] Thinking about the permutation tree diagram. It could be better... maybe it gets clearer with other colors? Not sure.  Maybe each column gets its own or all of the second picks are in a different color than the first?  Maybe under Lasagna it says.. L-C, L-R, L-Z, L-V, L-S?
- [ ] fix spelling of Lasagna under permutations chart.
- [ ] change \mul to \times
- [ ] Permutation with Replacement and Permutation without Replacement titles seem strangely small
- [ ] In permutation without replacement you are inconsistent about how many choices there are in both your words and your diagrams
- [ ] In combinations, I definitely want to see a visual (tree diagram) of combinations that lets me see why we're dividing by 4.

**Comment by schanzer** [comment]
@flannery-denny I addressed all these issues, save for the last. A diagram may not be the best way to make the point. Let me know if the re-wording is helpful, and if not I'll put in a diagram and try to come up with text to explain it.

**Comment by flannery-denny** [comment]
@schanzer 

- [ ] Wondering if you want to leave veal off the menu, because it's the poster child of animal cruelty in the meat production industry and plenty of people have a visceral response that might be an unnecessary emotion to bring into thinking about the math.
- [ ] Wondering if you wanted "have students discuss" line 96 inside the lesson instruction box.
- [ ] I think that it's distracting that these two lines are so big on the page:

> permute-w-replace(items,choose)=chooseitems
> permute-no-replace(items,choose)=items!(items−choose)!

- [ ]  (line 235) definitely needs an explanation of why zero factorial equals 1.
> We already know how to do this! This is the same question as "how many permutations are there for the same four courses?" So let's use our formula for permutation without replacement: @math{\frac{4!}{(4-4)!} = 4! = 24}

- [ ] I made some changes to text to try to clarify language and offer a proposal for how to be more explicit about what the diagrams are showing us

**Comment by schanzer** [comment]
Notes from our zoom call:
- [ ]  Remove reliance on factorial
- [ ] Have students write out the lists by hand, based on the trees
- [ ] add _optional_ starter file, with a screenshot in the lesson plan referencing it

**Comment by flannery-denny** [comment]
The Lopez family loves to go camping. So, each year Grandma buys Savannah and Rosa new gear.
This year they’re getting camping mugs. They are available in 6 colors. If she ships one to Savannah and one to Rosa, how many different possibilities are there to what she mails out?
Grandma wonders if maybe the mugs should be different colors so that the girls can tell them apart. If she doesn’t repeat colors, how many options does Grandma have to decide between.
Grandma decides to go to the store so she can see the mugs in person. When she leaves the camping store, she has two camping mugs in her bag. How many possibilities are there for what she has in her bag? (edited) 
10:36
an option for a smaller scenario?

**Comment by schanzer** [comment]
From conversation with Flannery:
- [ ] take yellow circles out of tree diagram images
- [ ] in tree-diagram worksheet, use flannery's suggestions instead of luigi

**Comment by flannery-denny** [comment]
@schanzer 

*Starter File*
The most confusing thing about the starter file is when you ask it to print lists for combinations with one choice. I don't really see the point to looking at those anyway, so I cut them out of the starter file directions.I also split number 4 and 5 differently than you did because I think it will be less confusing.

- [ ] You have a lot of things in this starter file. I wonder how you are planning to support teachers with it. Seems like there could be a worksheet to go with it where students had to record the code they're generating for their calculations and then teachers would get a solutions page...
- [ ] I also recommend changing permute-with-replace to permute-w-replacement ... (this seems like a moment where seeing the full word will support vocabulary development?)

*Tree DIagram page*
- [ ] updating the tree diagram worksheet is critical to the lesson.

*Permutations page*
- [ ] wondering if the permutations page should ask for the code they'd write to get the answer? or how they would solve the problem. the work seems more important than the numerical answer.
- [ ] there's room for at least one more problem on the permutations page. How about providing an example? (in part to help you think about what you want kids to write down)

**Comment by schanzer** [comment]
@flannery-denny I took a whack at updating the tree-diagram page, and adding a second one. Also updated the starter file, and the images. Let me know what you think?

**Comment by flannery-denny** [comment]
@schanzer 
Looks much better!
I made a couple spacing changes to the starter file.

- [ ] I changed the mug question from 6 colors to 5 colors (and listed them so that they could make the tree diagram).  Please update the image so it has 5 branches.
- [ ] In Tree Diagrams 2 second question I asked them to make an organized list instead of a tree diagram. Work for you?
- [ ] I think the example on the permutation workbook page does wonders. Want to also add one to the combinations page?
