### ISSUE TITLE
Peardeck updates to complete in December

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#400]
- [x] Algebra: Collision - Add Trinidad & Tobago starter file to additional resources

**Comment by schanzer** [comment]
Why wait until December?

**Comment by flannery-denny** [comment]
I can do it now. Thought it had to match the lesson plan.

**Comment by schanzer** [comment]
it does. But you’re changing the lesson, right?

**Comment by flannery-denny** [comment]
I changed the lesson and the peardeck, based on your comment.   As I understand it, peardeck changes are immediate, whereas lesson plan changes will be rolled out in January. So, my thought was to make a git issue to track any small peardeck changes that should be made closer to roll out.

**Comment by schanzer** [comment]
We absolutely cannot make changes to any existing peardeck slides. Even in January.

Anyone who is using a particular version of our materials should feel confident that they are never going to change.

Instead, you should save a copy of the existing peardeck, make your changes there, and replace the link to the old one in the lesson plan with a link to the new one. And since no one has a new link but you, there’s no need to wait to make any changes to the peardeck
