### ISSUE TITLE
January Dataset release

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#431]
- [ ] get ok from shriram on datasheets text
- [x] change sharing permissions for all sheets
- [x] reduce columns for nba stats
- [x] make starter files for Nick's files
- [x] sanitize student docs
- [x] confirm ownership of student fils
- [x] make readme tabs for nick's datasets
- [x] add missing positions to NFL rushing
- [x] trim columns for NYPD Stop & Frisk 
- [x] check that Emmanuel claimed pyret file for NBA

**Comment by shriram** [comment]
We're going to have to table this for a while, I believe. I'm still struggling with the datasheet authors.

**Comment by schanzer** [comment]
@flannery-denny any reason to keep this open? Didn't we already release these datasets, just without the datasheet stuff?

**Comment by flannery-denny** [comment]
@schanzer datasets are released but datasheets have not been. Shriram says we're tabling them for a while. In my mind that doesn't mean the issue is closed, but I don't have strong feelings. Close it if you'd like.

**Comment by schanzer** [comment]
The spirit of this issue was about cleaning and releasing datasets, and we added the datasheet checkbox because we had planned to fold this into the datasheet project.

While that project has been delayed, I think the spirit of this issue is long since complete. Whenever it resumes, it will almost certainly require that some prose be written or revised for every one of our datasets. I say we close.

**Comment by shriram** [comment]
I'd rather not close the datasheet work. It's not off my radar. I just have
much higher priorities right now (like securing funding for next year).

**Comment by schanzer** [comment]
Don't worry, there's _already_  a datasheet-related issue (#470) open. And again, this issue isn't really about "datasheet work".
