### ISSUE TITLE
Google Slides

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#45]
Lessons need updated Google Slides

**Comment by edcamposjr22** [comment]
@schanzer @BootstrapJen There are several comments about the slides so I wanted to address them here. I believe I mentioned before that I wanted to create the Slides as the very last thing because they are built off of the lesson plans and if the lesson plans change and i've already built the slides, that will be a bunch of tedious changes in different places. 

I should be done with all the issues by tomorrow afternoon and if the lessons seemed finalized by then, I'll start the Slides then(Thursday evening/night) and they should be done by Friday morning.

As far as the images used in the Slides, I pay for the premium subscription for Flaticon and their policy for using their images without attribution. I have purchased the rights to these icons through the subscription. That being said, I'll probably put something in the Presenter notes that describes just that.

![image](https://user-images.githubusercontent.com/34355200/57820095-2098ae00-7740-11e9-8abe-8025a3abab7a.png)

**Comment by schanzer** [comment]
@edcamposjr22 @BootstrapJen are the slides completely finished at this point? 

As for the icons -- if you stop paying the subscription, can we keep using those images forever?

**Comment by schanzer** [comment]
poke?

**Comment by edcamposjr22** [comment]
They are 95% done. Jen and I are gonna make a final pass at the lessons/slides
tomorrow to double check links/consistency/etc..
Our deadline is Friday to have Remix tied up with a Bow.


edcamposjr@bootstrapworld.orgwww.bootstrapworld.org(559) 303-3463
Sent with Mixmax  





On Tue, Jul 16, 2019 4:51 PM, Emmanuel Schanzer notifications@github.com  wrote:
poke?
