### ISSUE TITLE
original dataset

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#463]
Right now there is NO reference to the ORIGINAL dataset. We absolutely need that: this datasheet is useless or worse right now. We need a stylized way to refer to that (but parameterized, because each one points to a different place). We could do this in the "Who created the dataset": the answer should take two parameters, the name of the creator and the original dataset (URL) from which it is derived. Frankly, we also need to look up the licenses of each of those datasets.

I'm open to other ideas.

@flannery-denny Please weigh in. I don't know if I'm missing something, but I'm not sure how a person would get from the datasheet to the original. Maybe the idea is we direct them to the data *file*, which then refers them to the original?

**Comment by shriram** [comment]
@flannery-denny Do you object to my having a link to the original dataset in the datasheet?

**Comment by flannery-denny** [comment]
No

Flannery 

On Apr 19, 2021, at 7:36 AM, Shriram Krishnamurthi ***@***.***> wrote:

﻿
@flannery-denny Do you object to my having a link to the original dataset in the datasheet?

**Comment by flannery-denny** [comment]
All of the datasets made without datasheets have links to the original datasets in the README tab. 

I think I remember one of the datasheet questions was written such that students linked to their original dataset sources... but I haven’t looked at them since they came in in January.

Flannery 

On Apr 19, 2021, at 7:36 AM, Shriram Krishnamurthi ***@***.***> wrote:

﻿
@flannery-denny Do you object to my having a link to the original dataset in the datasheet?

**Comment by schanzer** [comment]
@flannery-denny and I spoke, and this looks like a good project for Nick Bousquet!

(Make sure there's a link to the website with the source - which is contained in the `/datasheets` folder)

**Comment by schanzer** [comment]
@flannery-denny says she went ahead and finished this.
