### ISSUE TITLE
what is the file datasheet-for-dataset-admin.adoc?

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#472]
It seems to be getting built, but it doesn't seem to be an actual datasheet. Why is it in the resources file?

**Comment by ds26gte** [comment]
The legit datasheet files -- e.g., datasheet-for-arctic.adoc -- extract tagged information from the admin file. The latter file needs to be around in order to supply these extracts. I'll see about locating it somewhere else, or at the very least avoiding creating HTML/PDF versions of it in the distribution/.

(Once, earlier this month, the datasheet file had inline-expanded all such inclusions, and the admin file didn't need to stick around. But of course, as you then noted, it wasn't possible to have modifiable contact in the extracted prose.)

**Comment by shriram** [comment]
@ds26gte Did this get moved elsewhere?

**Comment by ds26gte** [comment]
It's in the `datasheets/` subdirectory of the top dir of the repo. 

Use the branch `fall2021-with-datasheets`, not `fall2021`.
