### ISSUE TITLE
again confused about where to edit

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#473]
I am trying to edit datasheets in `bootstrap-curriculum/pathways/__sample/langs/en-us/resources/datasheets`. However, the top of every datasheet says
```
// Do not edit this file! Regenerate instead!
```
While I appreciate the warning, now I'm lost as to where to edit, and terrified about again editing in the wrong place.

[And while we're at it: a warning like that needs to be far more prominent. It is so very easy to completely lose sight of it in all the other top-matter, especially given that it's above the Datasheet paper boilerplate. Please make this *hard to miss*. The point of this is to actually alert and help the user, not just CYA.]

**Comment by ds26gte** [comment]
I added that comment because the file is the sanitized version of the student-filled file, and I did not expect it to be edited.  The idea was any edits of answers would be done before sanitization.

Since you are now editing that file and expect to be doing so, the comment should likely go.

An option is to keep the student files around unsanitized, and do the sanitization step as part of the build process.

**Comment by shriram** [comment]
I'm just editing where I was told! Am I editing in the wrong place (again)? If so, where should I be editing?

**Comment by ds26gte** [comment]
You're editing the right files. That comment is no longer valid.

**Comment by flannery-denny** [comment]
@shriram Can we close this issue?
