### ISSUE TITLE
Misc. directive bugs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#483]
- [ ] Rebuilding a pathway (non-forced) still shows `WARNING: No narrative in pathway algebra-pyret; creating one`
- [x] in piecewise-functions, the contract and purpose at the top of the page is rending as a run-on `<tt>` tag, instead of being syntax highlighted and properly line-broken
- [x] In `inequalities1-simple/pages/boolean-functions.adoc`, `(?ANS "someString")` is being rendered as `_____ _____ _____`). There should only be one blank, not three!
- [x] in `piecewise-functions/pages/restaurant-intro.adoc`, we get build errors for `(code '(...function definition involving cond...)`. 
- [x] In `inequalities2-compound/pages/boolean-coe-to-code.adoc`, it looks like we're not getting the CSS from the old `twoColumnLayout`. I don't mind rewriting this in asciidoc tables, but I want to confirm whether or not this is _supposed_ to work.

@ds26gte you already Rewrote `solving-word-problems/**/create-contracts-examples.adoc `to use code for its examples, so they render correctly for both Pyret and WeScheme.

- [x] the student version of the page should include a comment character before the blank for the fn name
- [x] the 5 questions do not fit on the pdf.

**Comment by ds26gte** [comment]
For the `(ANS? "someString")` subissue above, I'm getting a much more serious bug in that entire content including and after the suggested ANS is dropped. I don't know if this browser-specific.  I mitigated it somewhat by inserting a `<code>` within the `<tt class="pyret">`, and a minor bug remains where the very first occurrence of a code text in the page is not syntax-highlighted.  However, at least no content is lost. (The PDF in any case doesn't seem to lose content.)

About the multiple underscores, there should be only one underscore, however its length may vary between three choices depending on the length of the suggested answer.  Right now the heuristic is: use class `.studentAnswerShort` if the answer is less than 3 chars long, `.studentAnswerMedium` if it's 3 to 9 chars long, and `.studentAnswerLong` otherwise. We can either change this heuristic, or change the CSS for these classes. Requires viewing a bunch of pages to get the right value. In any case, having space-separated underscores is wrong. Either there's a browser-specific error or (very) old code is being used.

**Comment by ds26gte** [comment]
Re `#` missing for Pyret contract where `;` is correctly used for WeScheme:

The source was originally written using `code` with a string argument, and the string argument is rendered directly. It so happens the string was written with WeScheme in mind. I rewrote it to use the `contract` procedure, and it should now get correctly translated to both Pyret and WeScheme depending on `proglang`.

**Comment by schanzer** [comment]
@ds26gte confirming that the original `(ANS? "someString")` issue seems to be resolved, so whatever you did to fix the other bug seems to have fixed it on my machine as well.

**Comment by schanzer** [comment]
@flannery-denny confirming that Dorai has gotten all 5 questions to fit on one page in `solving-word-problems/**/create-contracts-examples.adoc`

**Comment by schanzer** [comment]
Closing this and opening a new, running issue for Dorai
