### ISSUE TITLE
Link colors suck

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#499]
@flannery-denny I am WIDE open for suggestions. I hate the yellow link color as well.

**Comment by flannery-denny** [comment]
The blue links generally look much better. For some reason they are different colors of blue depending on which part of the website you are on. I don't care a whole lot about that, but think it's worth noting because maybe we should?

- [ ] The blue link on the purple rectangle on the landing page is impossible to read. 
Possible solutions:
- This individual link could be a different color than the others. Maybe white?
- The box could be grey instead of purple like in the lesson plans
- We could pick another link color that works for all instances of the links.

- [ ] The color that the blue link turns once you click on it is almost exactly the same as the rest of the text on the workshops page (not critical, but worth noting).

**Comment by schanzer** [comment]
@flannery-denny Addressed both of these. Close if it looks good to you?
