### ISSUE TITLE
Teacher-Resources and Discourse access forms should not be exact duplicates

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#522]

**Comment by schanzer** [comment]
@flannery-denny Kathi ruled out dropping questions, which means we need to maintain both of these forms separately. OK to close?

**Comment by flannery-denny** [comment]
@schanzer add a note that acknowledges that we're research driven and the different forms both need to be completed.

**Comment by schanzer** [comment]
@flannery-denny Kathi IS comfortable if the survey is the same for both - so instead of making one survey shorter we could just use the longer of the two to count for both.

If nothing else, it cuts the number of forms teachers fill out by half. The downside is that for teachers who _only_ want the teacher resources, they have 3 extra questions to fill out and they'll also get a discourse invitation they may not want or need.

This feels like a worthwhile change to me. What do you think?

**Comment by flannery-denny** [comment]
@schanzer definitely!

**Comment by schanzer** [comment]
Done!
