### ISSUE TITLE
website bug

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#560]
The "Hour of Code" links [here](https://bootstrapworld.org/materials/latest/en-us/courses/hour-of-code/) still do not work.

@flannery-denny posted this in issue #555, which was closed last week.

**Comment by schanzer** [comment]
I _thought_ I fixed this in 947904ae4cada44ce487cf2e3542e1878b9abed7, which is why I closed the issue. Turns out this is a mac/unix thing. The fix that I applied worked correctly on _my_ machine, but on Brown's webserver it fails for a different reason. I've just pushed 6f6b8457748021595d160d421536f88956de2acb, which I can confirm fixes the issue on Brown's website (checked on both Chrome and Safari)
