### ISSUE TITLE
add a second sampling and inference page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#562]
In the new page, ask students to define three different sample sizes to compare.

**Comment by flannery-denny** [comment]
@schanzer I've pushed a draft of this file.

- [ ] @fitbits look good on the web version and are in total disarray on the pdf. Any tricks I should know for this? If not, I'll fix it so that the pdf version looks good.
- [ ] once we decide on the name for the starter file, update language around that in this file.

**Comment by flannery-denny** [comment]
For next year, let's shift the sampling and inference page away from species so as not to steal any thunder from the predictions from samples page.

**Comment by schanzer** [comment]
@flannery-denny the PDF looks good to me. Can you rebuild and send me a screenshot of what looks off to you? Here's what I see. 
![image](https://user-images.githubusercontent.com/77126/132095011-200cd6f3-6b3a-4a52-83bd-1020cfc22ff5.png)

See the other Git issue for the filename.

**Comment by flannery-denny** [comment]
My pdf looks exactly the same. The fill in the blank lines go all the way to the right edge in web form and are all over the place on this pdf. The discrepancy is huge. Wondering if there’s something that can be adjusted in puppeteer to make them build more similarly.

Flannery

**Comment by schanzer** [comment]
@flannery-denny Oh, you just mean the length of the lines? This doesn't seem as jarring to me as you described. It actually took me a few seconds to see the difference!

I spent all day trying to rip out more of the CSS layers that we'd added over the years to deal with wkhtmltopdf's various bugs and limitations. My goal is to use as much of the same CSS as possible between screen and PDF, so there won't be as many differences between them overall. Unfortunately, this is slow going -- because every little change needs to be checked against every PDF page. I'm working on a separate branch, but you can [track the progress here](https://github.com/bootstrapworld/curriculum/commit/40bb7f9ed2cdb6cf8299816cf48d9cb351a4d266). See this screenshot of the PDF!

![image](https://user-images.githubusercontent.com/77126/132152377-bffede6d-51d2-4ab9-990e-bb8cad156560.png)

The downside of all this, unfortunately, is that a LOT of pages are going to break. Many/most have been written with wkhtmltopdf's broken design in mind. What I'm seeing right now is that MANY pages are 2-3 inches too long, and need to be trimmed. I'm pretty sure I can get half of that back in other ways, but for several pages it's going to mean real surgery.

**Comment by flannery-denny** [comment]
@schanzer feel free to make a git checklist of pages you'd like me to turn my attention to
