### ISSUE TITLE
Additional function composition page for data science focused on filters?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#571]
Just found a note I'd made about building this page. Thinking it might 
- reinforce filtering as function composition
- hit on more than one way
- emphasize that order matters

useful?

**Comment by schanzer** [comment]
Function composition is an algebra learning goal, but less so a DS goal. Chaining Methods actually _deliberately avoids_ the idea of function composition, by using a syntax that reads left-to-right instead of inside-out:

**Take T, do G and then do F:**
Composition: `f(g(t))`
Methods: `t.g().f()`

I think that bridging back to composition here would take a LOT of teacher-work, and lacks the learning outcome to justify it.
