### ISSUE TITLE
Investigate selling workbooks on Amazon

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#578]
OK teachers apparently use some kind of web portal to order their workbooks, which cannot make orders through Lulu. Apparently they CAN do it through Amazon, and Lulu seems to have a way to list books on Amazon. Need to see if this is something we can make happen.

**Comment by flannery-denny** [comment]
@schanzer This reminds me that a friend of mine in Louisiana just started working for an organization focused on coastal restoration. They had lots of materials available for free on their website, but she proponented also making them available for free on Teachers pay Teachers because lots of teachers in Louisiana regularly visit the site who wouldn't necessarily go looking in other places. [This is what their stuff looks like there](https://www.teacherspayteachers.com/Browse/Search:coastal%20protection%20and%20restoration%20authority).  No idea whether or not it's a good idea for us. Just putting it out there as something to think about.
