### ISSUE TITLE
Content Review of 5 CODAPified Lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#592]
Looking for feedback on lesson content of CODAP Data Science Pathway!

1. displaying-categorical-data
2. table-methods
3. method-chaining
4. random-samples
5. grouped-samples

I've collected some stray thoughts [here](https://docs.google.com/document/d/1ZVXHZFDE_rlWcM1J4vCiVRfXLQaXRxuNNh8Vvkv-w1g/edit).

**Comment by schanzer** [comment]
### Displaying Categorical Data

### Table Methods
* "Open the Animals Dataset in CODAP" - You need instructions walking them through it, ideally starting with a link they can click. It looks like CODAP already has a notion of a shared link, so you could make a CODAP starter file that already has this set up
* "Click the graph icon from the menu in the upper left." is that really a menu? I'd call it a toolbar, but either way it would be useful to have a screenshot here.
* Add note re: add-blockers, which break at least the random scatterplot (and probably others)
* The WB pages here that use pie-charts sort of come out of left field. Either remove them, or add a small section teaching pie charts so students have context
* Would it make more sense to have students do the wb pages _after_ playing with CODAP?
* "Explore other data displays in CODAP" - I don't see a lot of options when I click the ruler:
![image](https://user-images.githubusercontent.com/77126/132864928-cf414726-9eab-4d95-8487-2b1d7a718159.png)
* The wb pages don't really seem to fit what CODAP can do (unless I'm using CODAP wrong?)

### Table Methods
* "Does sorting animals-table produce a new table, or change the existing one? How do you know?" I assume the answer here is "no", to set us up for why we use Transformers in the next section. If this is accurate, we need a third question that justifies why CODAP's default behavior has limitations.
* In the sorting transformer, students see the Contract UI above the formula expression. But you don't explain what it's for, and then later on you refer back to it using Domain and Range. You need a section in here that explains what contracts are.
* I've been purposefully using the same browser window for CODAP and reading the lesson plan, which forces me to _leave the lesson_ to work in CODAP. Students won't have the lesson plan in front of them either! It took me _six tries_ to correctly filter the table. You should add some explicit instruction, reminding students to use quotation marks are type `TRUE` in all caps. It might also be valuable to encourage them to try NOT doing those things, and see what happens.
* There's a stray reference in there to the `.build-column` method. :)
* You suggest adding a `cute` column for puppies and kittens, which explicitly requires the use of `and`. I think that's a fine idea! But you may need to tell kids what `and` is all about (and maybe `or`, while you're at it!). This could also be part of the lesson text for Pyret as well.

### Method Chaining
* "we can combine boolean tests on a single function" -- don't you mean Transformer? ;-)
* Transformers are sometimes capitalized and sometimes not. We should be consistent (check other lessons, too!)
* Your example has students convert pounds to kilos, but I wouldn't assume they know how to do that. You'll need to tell them (or are you holding off on the DR, to resurrect the worksheet?)

### Random Samples
* Wow, the sampler plugin is cool! Definitely need some screenshots here
* The ability to do multiple samples is a nice feature. Low-priority, but I wonder if there's some lesson content (wb pages?) that could be added here to take advantage of that?

### Grouped Samples
* In the asciidoc, you should just have the first investigate use bar charts for both Pyret and CODAP, rather than pie-charts for one and bars for the other.

**Comment by retabak** [comment]
I've revised the "Displaying Categorical Data" lesson. @schanzer - do you want to take another look before @flannery-denny does?  Some responses to your questions/ comments below.

**Displaying Categorical Data**
- "Open the Animals Dataset in CODAP" - You need instructions walking them through it 
>I've added a hyperlink. If more instructions are needed, let me know.
- "Click the graph icon from the menu in the upper left." is that really a menu? I'd call it a toolbar, 
>I changed wording and added a screenshot (which is awkwardly positioned; not sure how to fix that)._
- Add note re: add-blockers, which break at least the random scatterplot (and probably others) -
>Done.
- Would it make more sense to have students do the wb pages after playing with CODAP? - 
>Yes! Changed the order.
- "Explore other data displays in CODAP" - I don't see a lot of options when I click the ruler: - 
>I added some additional teacher instructions (in "Launch") to address this. Options appear depending on which attributes have been selected (or not) for the X and Y axis._
- The wb pages don't really seem to fit what CODAP can do (unless I'm using CODAP wrong?) - 
>I _think_ they do - except for worksheets that include pie charts. I've deleted some pie-chart focused worksheets from the CODAPified lesson. There's a worksheet or two with just one pie chart, which I left for the time being_

**Table Methods**
I ALSO started looking at "Table Methods," but wanted to run some questions by you, first. (Haven't yet made any revisions to this lesson.)
- "Does sorting animals-table produce a new table, or change the existing one? How do you know?" I assume the answer here is "no", to set us up for why we use Transformers in the next section. If this is accurate, we need a third question that justifies why CODAP's default behavior has limitations. 
> CODAP's default behavior is to change the table, not to create a new one. So, you're thinking the third question should be something like, "Can you think of a situation where CODAP's default behavior - to alter the table each time we sort it - would inhibit more sophisticated data analysis?" That feels weak; I bet you've got something better!
- In the sorting transformer, students see the Contract UI above the formula expression. But you don't explain what it's for, and then later on you refer back to it using Domain and Range. You need a section in here that explains what contracts are. 
>When working on this, I recognized that contracts appear out of the blue, but opted to leave it for now because I was thinking that contracts may need to be introduced alongside the design recipe. I'm still not sure where / when that will happen, or what it will entail. If you think I can just add a little section about contracts to this lesson and that will suffice - then I'm happy to do exactly that. Let me know.

Will work on remaining 3 lessons asap.

**Comment by schanzer** [comment]
@retabak the changes look good! Thanks for turning them around so quickly. I pushed a small commit (c23041281) which uses asciidoctor "blocks" to wrap .lesson-instruction around multiple things. I'd recommend taking a gander just so you can use it in the future.

As for Table Methods:
- If you don't have a particular wording in mind that feels good, why even ask them if CODAP makes a new table or changes the original one? I wasn't saying you _needed_ a third question, just asking why bother with the first one if we don't do anything with the answer.
- I think Contracts should be introduced as soon as students see them (in this case, well before the DR!). It doesn't need to take up a ton of time, but we should include a screenshot of the Transformers interface with an explanation of what the contract says and how to read it.

**Comment by retabak** [comment]
@schanzer Updated Table Methods lesson! I think I responded to all feedback. 

A few notes:
- I added a blurb about contracts but it's brief. Let me know what you think. ALSO - I couldn't figure out how to get a numbered list _inside_ the strategy box, which is why the numbered list is just super spaced out. Help?
- Re: "You suggest adding a cute column for puppies and kittens, which explicitly requires the use of and. I think that's a fine idea! But you may need to tell kids what and is all about (and maybe or, while you're at it!). This could also be part of the lesson text for Pyret as well."  ------ Didn't add anything in for now because the lesson is already pretty long (also "and" stuff is in the method chaining lesson). Thinking it might make more sense to omit the "cute" example or change it to something simpler. Let me know what you think.

Random question: When I've added images, for some reason my computer is naming them ".PNG" rather than ".png" (like all the other image files we use). Is this a problem? I can go through and fix if needed; have only added 3 or so images at this point. (I think I should probably postpone adding images anyhow, because it's a bit of a pain in the butt; as I ask this question, I am recalling your advice to add them all at the end.)

**Comment by schanzer** [comment]
@retabak 
1. I think this is a fine place to start. Can you use a screenshot for which the range is something other than `any`? This just happens to be the most confusing one of all. Maybe it would be useful to send them on a scavenger hunt as well: "find a transformer whose range is X..."? I pushed a fix for the numbered items, which requires (get this) asciidoc column format `a`, which means "any asciidoc directives could appear inside this column". [Check out the commit](cfffacc42) to see what it looks like.

2. yeah, I'd just remove this

3. It doesn't look like you removed the third question (about codap's behavior). Are you still planning to?

4. Filename capitalization will matter in some cases. Surely there's a way to tell windows to use lowercase extensions? What program do you use for images?

**Comment by flannery-denny** [comment]
@retabak. Ask @schanzer to talk you through how to use directives to signal which part of the lesson is what you expect teachers to say out loud to teachers in lesson plans. 

You are not using those distinctions so the formatting is inconsistent (lots of randomly bolded text) and it's easier to learn now than for us to go fix all of the pages later.

(I don't remember, but I could figure it out by looking at lesson plans I've worked on if he doesn't remember.)

One of us should add that information to the useful asciidoc commands file. Are you down to take that on?

**Comment by flannery-denny** [comment]
@retabak 
Generally speaking, I am seeing a lot of bolding and highlighting of things in your lesson plans that don't follow convention (Not your fault! This is part of the learning curve, but I wish you'd gotten feedback on it sooner...)

Lesson formatting used to be really bananas. We made directives to standardize it across lessons and make it easy to adjust for our entire repository if we were to decide we have better formatting ideas down the road. Directives allow us to flag functions, new vocab words, directions to students, etc.  Nearly all bolding and highlighting in lesson plans should happen through those directives. Some of them are described in the useful asciidoc commands file. Whatever would be useful to you to know about and isn't there should be added.  Holler if you need help making sense of it and you and @schanzer don't discuss it in the other conversation about directives I suggested.  I won't comment about it in the other lessons I'm reading - assume you will generalize this feedback and make use of it in all lesson plan files.

**Comment by flannery-denny** [comment]
_Chaining Methods_

Design Recipe Practice
- [ ] It's a little hard to weigh in on whether this section works, since you're just linking to a worksheet that hasn't been made for CODAP yet so I couldn't test anything out.
- [ ] The optional section talks about how to use `and` and `or` but doesn't actually give instructions for using them. I would suggest offering one or two prompts that would actually have students open CODAP and implement what you're describing.

Chaining
- [ ] "No more than 9 kilograms" is equivalent to "less than or equal to 9 kilograms" alternatively "under 9 kilograms" would be equivalent to "less than 9 kilograms".  Not sure which you'd prefer, but pick one and make the criteria match.
- [ ] This is a mouthful! Any other way you could say it? _Once a transformers is saved, students can abstract over a particular computation that they want to perform on the data (the way functions in Algebra are abstractions over computations in arithmetic)._
- [ ] Do you want to add something about _collections to add to_ to the directions for building the attribute?
- [ ] You talk us through exactly what to do for each step except for "Include only animals that weigh less than 9kg"
- [ ] The default dataset names are pretty cumbersome. If these were my students, I think I'd want to have them rename each of the datasets as a way of keeping track of what they've done. 
- [ ] I like this context, but I wonder if it has too many steps to be the introduction to chaining. Perhaps there's a context that only chains 2 or 3 transformers together that you could have the teacher do with the class as the launch. Another small context that pairs could do independently and then they could work up to this scenario? I think this is particularly important if you don't ask them to rename the datasets.

**Comment by flannery-denny** [comment]
_Grouped Samples_

- [ ] Reading the Launch of this lesson makes me think we need to include an image of the scatterplot that doesn't have the species labeled (for CODAP & PYRET!) after the first sentence and then move to the second sentence and the custom-image scatterplot.
- [ ] I'm not seeing anything here that talks about codap

**Comment by flannery-denny** [comment]
@retabak Is this issue ready to be closed or are you still working on something?

**Comment by retabak** [comment]
@flannery-denny Closing!
