### ISSUE TITLE
The formatting in the method-chaining lesson plan is very buggy - lots of ascii directives are visible.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#595]

**Comment by schanzer** [comment]
@flannery-denny After spending a few minutes scrolling through the lesson plan, I was able to find two closing curly braces that shouldn't be there:
![image](https://user-images.githubusercontent.com/77126/133245242-b3647c9d-7f8e-425a-8dd7-1f2a2d3b1f7a.png)

Are the these the glitches you are talking about? I couldn't find the names of any directives, so I'm probably just not seeing what you are. In the future, can you post specific information that will allow someone else to find and fix things like this?

(@retabak reminder to always build before pushing, and read through the parts you changed to make sure they look ok)

**Comment by retabak** [comment]
Apologies for bugs that are my doing. I think this happened when I was
having issues with building the pathway? Probably should have waited on
pushing, I suppose. I can revisit the lesson and try to fix (unless you
already have?).

**Comment by schanzer** [comment]
Already fixed! :)

**Comment by flannery-denny** [comment]
@schanzer if you'd looked at the web version, nearly the entire page looked like gibberish, which didn't seem to need more explanation. Thanks for fixing it.

**Comment by schanzer** [comment]
Do you mean what's on the website? I haven't touched that in well over a week (probably two). It sounds like whatever you saw disappeared on its own, and that I managed to snag the smaller issues that were in Git. 

Bear in mind that I will assume any bug reports reflect what's currently on Git, so unless you tell me otherwise I have no way of knowing where to look.

**Comment by flannery-denny** [comment]
I was flagging the issue from a file on git. But I'm usually looking at the
html versions rather than the asciidoc versions when I notice that they're
not building correctly.

**Comment by schanzer** [comment]
Yeah, the HTML version I saw only had two extra brackets on it (see the screenshots I shared). Maybe the takeaway here is that for all "hey this doesn't look right" issues, a screenshot is warranted. I know it must have seemed obvious to you when you looked at it, but the page didn't look like gibberish to me. Either it was fixed by some other commit between you filing the issue or there was some fluke when you tried to build, but having the screenshot would have made it a lot easier for me to realize what was going on.
