### ISSUE TITLE
web bug: last updated time stamp is being added in the middle of the webpage...

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#604]
I've never seen this happen before today, but now it's happened more than once...

![Screen Shot 2021-09-24 at 11 53 01 AM](https://user-images.githubusercontent.com/66691020/134723613-17d58b8f-1b19-493c-9b03-8f871db72127.png)
![Screen Shot 2021-09-24 at 12 29 45 PM](https://user-images.githubusercontent.com/66691020/134723624-85cbf4be-fbec-42d3-b955-cc2a8d14f17a.png)

**Comment by schanzer** [comment]
@flannery-denny ah, this is because we're now forcing pages to fit in an actual page boundary! And since there are still some subtle differences between screen and paper (like that save to gdrive button!), we're seeing the difference. 

I'll turn the boundaries on _only_ for printing, when it matters.
