### ISSUE TITLE
Design Recipe pedagogy callout

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#670]
We should talk about the _why_ of the recipe, make deeper connections to math, and talk about how order is less rigid than it may appear.

**Comment by schanzer** [comment]
@flannery-denny and @retabak this is ready for review.

**Comment by retabak** [comment]
@schanzer 

Re: "The Recipe should be considered a collection of tools, and students should know how to use more than one!"

I'm confused by this sentence--as in, I genuinely don't get what we're trying to say. Can you spell it out more clearly for me? Students should know how to use more than one what? One tool? One recipe? Help.

Otherwise, I like this and think it's a nice addition. :)

**Comment by schanzer** [comment]
@retabak good point! Check out the latest version?
