### ISSUE TITLE
Nail down annual timeline for lessons, feedback, and workbook printing

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#679]
**Third week of January**
- [ ] Tag `spring20xy` release
- [ ] Merge master into `fall20xy` branch, 
- [ ] Finalize list of lessons for `fall20xy`

**April 1**
- [ ] Finalize workbook pages for proofreading

**Mid April**
- [ ] Send workbook pages to lulu

**First week of May**
- [ ] Copy-edit printed copies of workbook

**Second week of May**
- [ ] Ship revised `fall20xy` workbooks

**Third week of May**
- [ ] Peardecks and lesson plans ready for review

**June 1**
- [ ] Slide decks and lesson plans ready for PD

**Last week of June**
- [ ] Deploy `fall20xy` materials to website
- [ ] move `latest` alias to `fall20xy`

**Last week of September** 
- [ ] Tag `fall20xy` release
- [ ] Merge master into `spring20xy` branch

**Mid October**
- [ ] Hour of Code is designed and assigned, to be completed by December 1.

**Last week of December** 
- [ ] Deploy `spring20xy` materials to website
- [ ] move `latest` alias to `spring20xy`

**Comment by schanzer** [comment]
@flannery-denny @retabak draft schedule ready for comment, possibly/likely on our call today?

**Comment by flannery-denny** [comment]
@schanzer Thanks for putting this together.

We have trainings scheduled throughout the month of June, so all workbook and peardeck updates should be completed before June 1. 

To my mind, in order to turn edits around, this means that we need printed copies of the workbooks in hand by May 1 so we have to time to read carefully, send back edits, and get copies printed for in-person workshops.

My hunch is that in order for us to proofread on the computer before we send it to Lulu, new lessons and accompanying printed materials need to be completed by April 1. (In my experience we spend a fairly small percentage of our time making new lessons and if we prioritized our time with this deadline in mind, it would be quite achievable... would you agree?)

Additional reality that makes this earlier deadline particularly important is that I produce a music festival every May, the weekend after mother's day (Swamp in the City is scheduled May 12-15 this year), which makes me unavailable to do much Bootstrap work during the second or third week of May. And then there's Memorial Day :)

I'm a little less clear about the fall deadline being end of September.

And am curious to note that next year's spring release will go out a month sooner than this year's.

Also, I love that there's a time on the framework for thinking about new lessons for June's release. I'd love to see a similar time noted for Hour of Code lesson thinking and the Winter release.

**Comment by schanzer** [comment]
@flannery-denny I'm fine moving the workbook pages to the second week of May, and I've added the HOC thinking as november date.

But why do PearDeck updates need to be completed before the start of June? We regularly make small changes and improvements well after we start training, whereas workbooks really need to be finalized to go to print. Lessons are updated similarly.

The September deadline is a deployment deadline, not an authoring one. We inevitably find small fixes that need to be made in the first few weeks of school, so tagging a release before then makes maintenance a lot harder.

**Comment by flannery-denny** [comment]
@schanzer Lmk when you’re available  to talk.

**Comment by schanzer** [comment]
All event added to Team Calendar as recurring reminders
