### ISSUE TITLE
Align lessons with social justice standards

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#682]

**Comment by flannery-denny** [comment]
@retabak @schanzer added SJ standards to the lesson that focuses on who programmers are and the lesson that talks about hermaphrodite animals and humans who identify as transgender / non-binary.  I think we are doing good sj work with both of these lessons and it is also true that the sj standards are not the focus of either of these lessons. If you would like to remove any of them because you think they're overstating the case, please do!

**Comment by schanzer** [comment]
@flannery-denny I think these are reasonable alignments. Keeping this issue open since there are likely other lessons we can align.
