### ISSUE TITLE
Write Project Overviews for Research Paper / Videogame

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#688]
Now that we've built out our materials landing page to be pathway agnostic, we have buttons for projects that allow us to see their prerequisites. These projects also need landing pages that will use a project-directive to gather the description for the buttons and collect them in the project list on the teacher resources pages.

- [x] Research Paper Description #888
- [x] #791
- [x] #782

**Comment by flannery-denny** [comment]
@schanzer The more I think about it, the more I think the page that describes all of the datasets (using the about-data-set fragments) should be linked directly from the choosing your own dataset page, in addition to being linked from the datascience teacher resources page.  I would like to move the folder from resources to the lesson... unless the way that we're going to make the Research Paper Project description be a button folks can click on from the materials page is that it will be its own lesson folder, in which case it might belong there instead. Thoughts?

**Comment by schanzer** [comment]
Totally agree! Done.

**Comment by flannery-denny** [comment]
@schanzer git checkout fall2022 and ./build-pathway algebra.  You'll find the page in the resource section. I am struggling with:
- links (both at the top and in the table - some are visible. some are not. none of them work - look forward to learning how you resolve this
- when I switch from == to === there is no space above the ===. Seems strange and undesirable.
- I've commented out the description at the top, but I think ideally the description would be used like the other files used by the @opt-project-directives where it's not part of the visible page, but it's used as the description on the project button and the teacher resources page.

**Comment by schanzer** [comment]
@flannery-denny 

* the links you added go all the way back to the root of the repo, instead of the root of `distribution/langs/en-us/`. Removing some of the `../`s fixes those links.
* the 3rd level headings (`===`) _can_ have a top margin.  I added a CSS rule for it, so you can adjust as you like.
* hold off on the description - I'll open a separate git issue to have those generated automatically. This will take some elbow grease from Dorai, which I'd like to hold off on until the summer. That OK with you?
