### ISSUE TITLE
Inference improvements to randomness

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#696]
Implement recommendations described here:
[Suggested Revision to Randomness and Sample Size.docx](https://github.com/bootstrapworld/curriculum/files/7678188/Suggested.Revision.to.Randomness.and.Sample.Size.docx)

And here
[Inference in Bootstrap.docx](https://github.com/bootstrapworld/curriculum/files/7678212/Inference.in.Bootstrap.docx)

**Comment by schanzer** [comment]
@flannery-denny this lesson is now ready for review!

**Comment by flannery-denny** [comment]
@schanzer I would suggest changing the coin flip starter file so that the first coin is fair. As someone who's trying to figure out how the starter file works, when the first coin returns the same thing on every "run" it's hard to know whether I am using the file correctly. If the first coin worked more or less how I would expect it to (not returning heads for each of the first 3 flips) I would believe that I was interacting with it correctly.

**Comment by flannery-denny** [comment]
@schanzer I can't fully weigh in on this until you push the missing "fair coins" page and "heads.png" image. Lmk when it's ready.

**Comment by flannery-denny** [comment]
@schanzer 

Specifically:
- [ ] I recommend changing the order of the coins in the starter file so that coin 1 is more fair so that the new user trusts that they are engaging with the starter file correctly.
- [ ] Questions 5-7 on Finding the Trick Coin feel like they come out of nowhere. The questions in the lesson plan feel more open-ended, but these feel like we should be doing some sort of calculation. I looked at the solution page to see if I could find your thread, but you haven't offered a solution. I think that if you want to include these questions the lesson plan needs more scaffolding.
- [ ] I made an executive decision to use **more-animals** as the consistent name for the table in the expanded animals starter file, lesson plan and corresponding wb pages. If you'd prefer another, please replace all references.

More generally, there are a lot of large swaths of text on white background without student interaction in this lesson. Wondering how this lesson plan could better implement the guidelines we discussed today about lesson plan formatting?

**Comment by schanzer** [comment]
@flannery-denny I don't see large swaths on a white background here, but I've made some changes to visually break up the lesson plan anyway. Hopefully this addresses the issue?

**Comment by flannery-denny** [comment]
@schanzer this is a huge improvement. I love the changes you made on fair coins and the table you added in the lesson plan.

It seems like p-value is an option for folks who want to take a deeper dive so I put it in a pedagogy box. If you think it's more central to the lesson (and maybe even if you don't) it deserves a workbook page that actually engages students with it.

In rereading the lesson it seems that the two most important takeaways you want people to get are about the importance of random samples and the importance of sample size. I am pushing some changes in an attempt to make that more evident. I'm not sure I nailed it. 

Something I've been trying to address is that the answers to many of the questions were being given in the lesson plan before the question was being asked... I think this restructuring sort of addresses that. 

Feel free to revert / modify as you see fit.

**Comment by schanzer** [comment]
@flannery-denny I like your changes, and I added a few more of my own. I think this lesson is good to go. Close if you agree?

**Comment by flannery-denny** [comment]
@schanzer Much better. 

- [ ] I'm confused as to how this lesson addresses SJ.10.  I recommend taking another pass at the standards and practices associated with the lesson.

- [ ] can we change the title "How to spot a cheater" - the word cheater makes me nervous every time a read it... and I'm not sure it's really what the lesson is about. Looking for something more directed at a situation than a person. Maybe "How to spot a scam"?
