### ISSUE TITLE
Data Cycle Worksheet

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#760]
- [x] what question are you trying to answer?
- [x] what type of question is this?
- [x] what kind of data do you need?
- [x] write the code - what answer did you get?
- [x] what question does this raise?
- [x] #573 

Lessons to include:
- [x] Displaying categorical data
- [x] Grouped Samples
- [x] Histograms2
- [x] Measures of Center
- [x] Measures of Spread
- [x] Scatter plots
- [x] Linear Regression

Formatting proposals to explore:
- [x] DR-style, with gray bars and checkboxes for easy grading?
- [x] Remove numbers and letters to save horizontal space?
- [x] We NEED a second blank for the question
- [x] Take up a full page?

**Comment by schanzer** [comment]
@flannery-denny first draft complete! Now that I'm thinking more deeply it, I don't think it makes sense to add questions like "does the dataset have this data?" or "is it worth including?". Let me know if you agree/disagree?

It's also clear to me that this sheet has a dependency on #492 .

**Comment by flannery-denny** [comment]
@schanzer curious why you don't think those questions belong?

I'm noticing that you wrote a lesson addressing a lot of interesting and valuable things... and I like the new workbook pages.

I was under the impression that this issue was focused on building a worksheet that would be used as part of the research paper writing process...

While you've introduced the parts of the data cycle, and question types, you don't seem to have made anything yet that engages students with proceeding from one stop of the data cycle to another, scaffolding the research process...

**Comment by schanzer** [comment]
@flannery-denny The worksheet can be found in the choosing your data set lesson. That's not its final home, mind you.

I don't see a way to create the scaffolding without threading it into other lessons. That's the work I'm doing right now. Will let you know when it's ready for feedback. In the meantime, let me know what you think of the data cycle worksheet?

**Comment by flannery-denny** [comment]
@schanzer oooh. I like it. Currently you have it set up so that there are 2 cycles to a page and both of them have the same question filled in. We'll certainly need a version where they're both blank. It may be useful to have one that has the first question filled in? I wonder if we need more room for students to record their thinking in the analysis section... for example, what it the question requires them digging into a subset... where would that get recorded? Maybe they need an extra line for the pyret code in case it takes them two lines of code to make the display?

**Comment by schanzer** [comment]
@flannery-denny those will be blank. I've been experimenting with variations on the template, and needed to see it with some text filled in.

Students will discover if they need a subset in the `consider data` section. If their answer to "what rows"? is anything other than "all of them!", it automatically means they need to `filter`. Likewise, they'll know they need `build-column` if their answer to "which columns?" is something that's not already part of the table.

I've added an extra line for code. Good call!

**Comment by schanzer** [comment]
@flannery-denny the current data cycle template is complete, as far as I can tell. Before I ask Dorai to turn it into a directive, do you want to give it a once over for any final feedback?

**Comment by flannery-denny** [comment]
@schanzer I will look at it and get back to you.

**Comment by flannery-denny** [comment]
@schanzer are all of these the same? where else can I look for one besides in the standard deviation lesson
