### ISSUE TITLE
Add a pedagogy box for Simpson's Paradox

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#763]

**Comment by schanzer** [comment]
@flannery-denny ready for review

**Comment by flannery-denny** [comment]
@schanzer 

1. The age v. height dataset does not actually do what the words in your description of Simpson's Paradox say that they do. 
2. I was expecting this pedagogy box to be added to the custom scatter plot lesson.

**Comment by schanzer** [comment]
@flannery-denny 

1. I've updated the spreadsheet in order to give us a more explicit example of Simpsons's Paradox. I can crank it up further, but we risk losing some of the "realness" of the data if we make it much more contrived.
2. Custom Scatter Plots are not a required lesson to get kids to LR, and Simpson's Paradox doesn't make sense without LR. I'd much rather leave the box where it is.

**Comment by schanzer** [comment]
@flannery-denny the authoring tab is easy to update. I've made some changes that get the heights more in-line with some other resources I've seen. Can you eyeball that sheet, and if it looks good I'll update the SImpsons sheet and the solutions accordingly?

**Comment by flannery-denny** [comment]
@schanzer dataset makes more sense now. please update sheet, make sure you have 4 nb  students out of 100, confirm it works in pyret, and update solutions in age v height. Then close the issue. Thanks!
