### ISSUE TITLE
"More than one way" is too long

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#779]
In function-composition, the "more than one way" worksheet doesn't leave enough room for students to write answers. In the solutions - which print in teen-tiny text - it still needs two pages to print. A real person would need even more room.

Can we cut one of the questions?

I'm not sure how the code on this page ended up the way that it did (it looks like it was written by multiple people since a variety of strategies are being used for incorporating solutions), but the question asked for two solutions. and the page was giving one away and then leaving room for two more. 

The code be cleaner, but I've pushed a fix in the most expedient way such that no solutions are revealed in regular mode and only two solutions are revealed in solutions mode.

- [x] Please use your css magic to create a little space between each of the 4 expressions in the box at the top of the page. It is hard to tell that there are 4 expressions there.

```
beside(rectangle(200, 100, "solid", "black"), square(100, "solid", "black"))
scale-xy(1, 2, square(100, "solid", "black"))
scale(2, rectangle(100, 100, "solid", "black"))
above(
    rectangle(100, 50, "solid", "black"),
    above(
        rectangle(200, 100,  "solid", "black"),
        rectangle(100, 50, "solid", "black")))
```

- [ ] Also, I'm not sure that I agree that this expression needs to be on so many lines.

```
(above
    (rectangle 100 50 "solid" "black")
    (above
        (rectangle 200 100 "solid" "black")
        (rectangle 100 50 "solid" "black")))
```

would you be ok with something like this instead?

```
(above(rectangle 100 50 "solid" "black")
    (above(rectangle 200 100 "solid" "black")
       (rectangle 100 50 "solid" "black")))
```

- [x] Do you want to keep the bullets?
- [ ] Is there a better way to space out the blank lines?

**Comment by flannery-denny** [comment]
@schanzer 

I'm not sure how the code on this page ended up the way that it did (it looks like it was written by multiple people since a variety of strategies are being used for incorporating solutions), but the question asked for two solutions. and the page was giving one away and then leaving room for two more. 

The code be cleaner, but I've pushed a fix in the most expedient way such that no solutions are revealed in regular mode and only two solutions are revealed in solutions mode.

- [ ] Please use your css magic to create a little space between each of the 4 expressions in the box at the top of the page. It is hard to tell that there are 4 expressions there.

```
beside(rectangle(200, 100, "solid", "black"), square(100, "solid", "black"))
scale-xy(1, 2, square(100, "solid", "black"))
scale(2, rectangle(100, 100, "solid", "black"))
above(
    rectangle(100, 50, "solid", "black"),
    above(
        rectangle(200, 100,  "solid", "black"),
        rectangle(100, 50, "solid", "black")))
```

- [ ] Also, I'm not sure that I agree that this expression needs to be on so many lines.

```
(above
    (rectangle 100 50 "solid" "black")
    (above
        (rectangle 200 100 "solid" "black")
        (rectangle 100 50 "solid" "black")))
```

would you be ok with something like this instead?

```
(above(rectangle 100 50 "solid" "black")
    (above(rectangle 200 100 "solid" "black")
       (rectangle 100 50 "solid" "black")))
```

- [ ] Do you want to keep the bullets?
- [ ] Is there a better way to space out the blank lines?

**Comment by schanzer** [comment]
@flannery-denny take a look and see what you think. I'd really like to avoid changing the indentation rules as you suggest, so if you can live with this I think we can safely close the issue.
