### ISSUE TITLE
review linearity 1, linearity 2, function-definition & make sure they don't duplicate each other

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#789]
**Linearity**
- [ ] It looks like you added linear functions back into the `linearity` lesson. If it's going to exist here, I think we need to do a better job of explaining why `f(y)=3` is not a function. Perhaps that involves adding the text that we cut from another lesson that showed the vertical line test. 
- [ ] This lesson plan is covering a lot with very few examples and I'm concerned that we are hiding the patterns we are hoping for students to see by jumping around so much. I would like to recommend that we reorganize the lesson plan as follows:

> - simple straight lines
> - linear, nonlinear or bust 
> - a separate section focused on vertical and horizontal lines and the concept of functions.

- [x] There are a lot of visuals in this lesson plan that we're asking students to notice & wonder about for which I think it would be helpful for them to be able to examine them at their own pace / write on them, etc. I propose we move those tables / graphs to workbook pages.

**Linearity2**
- [x] Wow! @schanzer This lesson had changed a lot since the last time I looked at it. I found a bunch of mistakes and pushed changes I expect you'll want to review.
- [x] I think we should add images into the lesson plan of a positive slope, negative slope, and zero slope when we describe what they look like.
- [x] I think we should add images of y-intercepts into the lesson plan when we describe what they look like.

**Other than the changes noted here for improving these lessons, I don't think we need to do any major overhaul. I'm not seeing much overlap between linearity and defining functions.**

**Comment by flannery-denny** [comment]
@schanzer lmk if the framing above works for you and I'll tackle it.

**Comment by schanzer** [comment]
@flannery-denny the edits and framing above look terrific. Excited to see your next round of revisions!

**Comment by flannery-denny** [comment]
@schanzer The more I think about this lesson, the more I think we need a separate lesson on identifying functions and why they're important. I just don't believe that we (or our teachers) can do a good job of both in one class period and I definitely never attempted to both (or either) in a single class period when I was in the classroom. 

I'm confident that I pushed back on using the word function without explaining it well in the version that went out in the world in the fall and the only way that I can make sense of what I'm seeing here is that Oklahoma pushed for us to teach functions and the word got added back into the the linearity lesson. 

I still object. But I like the idea of doing a comprehensive job of introducing functions as a separate lesson. And, if they're asking for it, all the more reason to prioritize it.

Perhaps we should discuss? Do you have time on Thursday or Friday?

Proposed what is a function lesson talking points:

- [ ] graph / vertical line test
- [ ] continuous v. discrete
- [ ] undefined slope
- [ ] directions for a computer / related error messages we see in pyret / preview piecewise
- lunch special - discount on soup between 11 & 2
- [ ] f(x) notation

**Comment by schanzer** [comment]
@flannery-denny this is a _very_ intriguing idea. I worry about adding yet another lesson to our already-full plate, but if it's the right thing to do I'm onboard. As of now, we have the following list of six function lessons:

✅ Three Representations of Functions (contracts, examples, definition) 
✅ Solving Word Problems (design recipe)
✅ Restating the Problem (lots of DR practice -- including linear, positive/negative slope, etc)
✅ Linearity (graphs and tables)
✅ Linearity (definitions, slope and y-intercept)
❓What is a function

I think we need to nail down a more coherent sequence for all of these as a starting point, and then figure out what needs to change about all of them. Here's the sequence I would propose:

**1. Functions as Machines** - this builds directly on the defining values lesson, introducing a very narrow function concept to start. We cover gt, bc, etc as labor-saving devices, emphasizing the progression from `gt50 = triangle(50, "solid", "green")` to `gt(50) is triangle(50, "solid", "green")`. It's fairly rote and programming-focused to start, but there's tons of engaging problems and it drives home two critical foundations: _functions are useful,_   and the concept of _function machines_. This makes it easy to cover Pyret errors too, which are also fairly rote and should be gotten out of the way quickly.

**2. Functions as Domain&Range, Examples, and Definitions** - this broadens the function concept, leveraging the existing "3 representations" lesson to get students thinking about functions in flexible ways. This lesson also introduces/formalizes function notation, since a definition is just another representation of functions.

**3. Properties of Functions** - this is where I'd slot your proposed lesson, with some modifications. I think the vertical line test is great here, and builds on the domain&range discussion in the preceding lesson. Continuous v. Discrete is also great here. Function notation is already covered elsewhere, as are Pyret errors. This lesson could lean harder on _graphing functions_ - a known gap for us, and a natural companion to discrete v. continuous properties.

**4. Functions can be Linear** - This one is basically our existing linearity lesson, layering on straight-line relationships as another property a function can have. It also spirals back on multiple representations, and gives us a nice opportunity to test their understanding about things like the vertical line test, continuity, etc.

**5. Properties of Linear Functions** - This is basically linearity2, which could use a lot of improvement from the ideas you're proposing. The main thing here is that we can't introduce slope before we introduce the idea of straight-line relationships, and slope is _better understood_ when you have the anchors of continuity and graphing. 

This leaves "solving word problems" and "restating the problem" as floating lessons. They could be introduced almost anywhere - even after the second lesson in the sequence. And numbers 3-5, being math specific, can be skipped by teachers who are focused more on the programming side of things.

Thursday is a _tough_ day for me, but I'm flexible on Friday between 9:30-1pm ET, or 2:30-3:30pm ET. What works best for you?

**Comment by flannery-denny** [comment]
@schanzer I think I've finally processed your proposal.

As I understand it, you are asking for me to split Defining Functions into two lessons?
When I look at your reasoning on git, it makes sense. But when I look at the lesson, introducing examples and definitions is the lead up to the function definition, so it's hard to understand how to introduce gt without that. 

- [ ] Are you proposing that we act out gt in one lesson and define it in another?

I am willing to take that on if it's important to you, but it's not obvious to me what we stand to gain from that. I already rewrote Defining Functions once in the last year and we thought pretty hard about it. I feel like there's something you're taking into consideration that I am not. 

For now I'm going to tackle the Properties of Functions lesson that I understand clearly in my brain. Lmk when's good to circle back and talk about why you want to split the other lesson in two.
