### ISSUE TITLE
Connect project description to at least one SJ identity or diversity standard

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#791]
@schanzer I knew how to do this when we thought about the project infrastructure like a lesson, but how do we add standards for a project that isn't a lesson?

**Comment by flannery-denny** [comment]
@schanzer The place we usually look for standards alignment is in the
shared files lessons-and-standards and lessons-and-practices. If we were
doing a stemworks audit of our materials, I would want whatever solution we
come up with to register. And, supposedly, teachers can search for a
standard on the materials landing page. So, I was imagining that the
connection would be more than hardcoded for maintainability.

If you would prefer that it be hardcoded onto the page, lmk what format you
think makes sense for that. I don't have any models that I can copy since
everything related to this everywhere else is autogenerated.

**Comment by schanzer** [comment]
That's really helpful, thanks. If it was _purely_ about documentation/alignment, I'd say add it to `shared/langs/en-us/practices/lessons-and-practices.rkt`. Dorai's script happily ignores lessons it doesn't recognize, so we could easily cram it in here.

However, if you want the projects to be searchable by standard, that tips the scales in favor of another (better) implementation. Right now project info is spread out in a few places:

- Descriptions are hardcoded into the various adoc files, but then also _duplicated_ in our landing page 🤮.
- Standards don't exist
- Associated lessons are reverse-engineered by my code in the landing page🤮, and currently allow for only a single lesson. This works for most of our projects, but not for the game or the research paper.
- Associated rubrics are passed to the @opt-project directive along with the project page.

Here is what I propose instead:
- Dorai adds `shared/langs/en-us/projects/projects.rkt`, containing a dictionary for all the projects, including their associated lessons, standards and descriptions. 
- Project descriptions move from the project files into the dictionary
- `@opt-project` and `@project` now refer simply to the name of the project in the dictionary, and generate the same links they do now. But instead of relying on author input to get both of them right, they just look up the right links in the dictionary.
- When building, every project in the dictionary is checked to see if it has any standards, textbook alignments, or practices defined. If not, this generates a warning (this helps keep us honest by forcing us to confront the alignments for these projects).
- When building, projects are added to the dependency graph automatically like the rest of the lessons. This makes the landing page less error-prone as well.

This could be a chunk of Dorai's time, so the question I want to pose is "is it worth it?" If so, I'll close this issue and open a new one for Dorai. If not, I'll just add some alignments to the standards file so that it's documented for _us_.

**Comment by schanzer** [comment]
Relevant to #751

**Comment by schanzer** [comment]
@flannery-denny just a reminder that I'm waiting for feedback on the alignment

**Comment by schanzer** [comment]
Definitely not urgent, but I just wanted to make sure I didn't fall off your radar

**Comment by flannery-denny** [comment]
@schanzer I'm not sure whether the exploration and research papers are always collaborative. If not, let's remove P2. Otherwise, I'm ok to close.

**Comment by schanzer** [comment]
@flannery-denny All of our DS materials assume these projects are collaborative, and make explicit references to 
"partners" or "groups".

**Comment by flannery-denny** [comment]
I’m not sure. I mostly think about standards to help other people check boxes for buy in. I think it’s worth discussing with Rachel in our mtg next week.

Flannery
