### ISSUE TITLE
Vertical Line Test Lesson ready for Feedback

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#818]
- [x] Undecided as to whether the rectangle conversation and the photocopier conversation are both serving us. Curious what you think. 
- [x] I think I like the interactive peardeck here. you?

Other than the initial launch I think this lesson is good to go.  But, I am, of course ready to overhaul it to make it better :)

**Comment by schanzer** [comment]
@flannery-denny 

**Meta Point**

- [ ] _"SWBAT Generate points for a graph from a rule."_ -- why "rule" and not "function"? You use "function" and "rule" differently throughout the lesson. Sometimes a function "uses a rule" or "has a rule", but sometimes the function _is_ the rule. If you can explain what the difference between a function and a rule is, I would do so explicitly and make sure you're using the terms consistently throughout.
- [ ] I also wonder if it's worth just calling out explicitly that these are all about _relationships_. Kids know a lot about relationships! I earn $10 per hour at work, which describes a relationship between time and money. A car moves at 55mph (time and distance). Gasoline is $4/gallon (money and gallons). **Functions are a way of describing a certain kind of relationship.** But what kind, exactly? That's what we're going to find out....

**Each Set of Inputs has One Output**

- [ ] Agreed that the rectangle activity doesn't seem to be pulling its weight. (I don't see a photocopier referenced here?)
- [ ] _"Just as we can give the rectangle function inputs and it will produce an image, we can make graphs of functions by feeding inputs (x-values) into a rule that produces outputs (y-values)."_ This wording is problematic for many reasons. Recommend the following change: _Just as we can give the rectangle function inputs and it will produce an image, we can give a math function inputs and it will produce an output._
- [ ] _"We can repeat the process with an infinite number of x-values to produce a line or a curve or any other shape of function."_ "shape of function" implies that kids know what shapes are valid. Most likely they'll interpret this to mean "any other shape" period -- which is not true. I'd also like to avoid welding "x-value" to the concept of input. Recommend the following change:  _"We can repeat the process with an infinite number of inputs, plotting the outputs as a line or curve on a graph."_
- [ ] I _love_ the interactive function activity. WOW what a nice use of PearDeck, too!
- [ ] Maybe we could add a "synthesize" question: "Are there are curves or lines that a function could **not** make? Why or why not?" This would set them up nicely for the following section.

**Vertical Line Test**

- [ ] I feel like this section should be called "Identifying Functions in Graphs", in keeping with the next section. The VLT is just a visual way of identifying on a graph, right?
- [ ] _"We can write rules that take in an x-value and produce a y-value. Different x-values can yield the same y-value. But each x-value can only be associated with one y-value."_ -- no need to reference x and y here. Let's not weld them to the concept of function!
- [ ] I think this section would benefit from a pedagogy box that talks about terminology, or at least a sentence or two in the lesson that explains that students have seen _all kinds of functions_, and that a special `Number->Number` subset of them can be graphed in 2 dimensions. When we do this, it's customary (a convention!) to view the Domain along the x-axis and the Range along the y-axis. That might help anchor teachers' understanding, too. The VLT is just a special trick that only works for those functions, but's a nice and concrete way of explaining the idea of "same inputs, same output".
- [ ] _"If there is any vertical line that can be drawn that would intersect more than one point on the graph, the graph is not a function."_ Recommend changing to: _"If there is any vertical line that can be drawn that would intersect more than one point on the graph, it means the same input can have more than one output and the relationship is not a function."_
- [ ] Identifying Functions from Graphs - The captions you've written for these graphs are incredible. This worksheet is an exemplar of what all of our stuff should strive for.
- [ ] How Tables Fail the Vertical Line Test -- I love the idea here, but I think there needs to be some explanation at the top of the page: "Each of the three graphs below is also represented by a Table." Or this prose could be prepended to question 1. It took me a minute to realize what the tables were about, since they weren't mentioned until question 4.

**Identifying Functions From Tables**

- [ ] Can we not use x-value and y-value all the time here? We're not even graphing on a coordinate plane, so those names make even less sense here. How about we show them a few tables with x/y, a few with input/output, and a few with real-world names like dollars/gallons, hours/miles, etc? All we need to do is tell them that the input column is on the left, and the output is on the right.
- [ ] _"If an x-value appears more than once in the table and has a different y-value **each time**, we know it can’t be a function."_ -- I know this is nit-picky, but we should be as clear as possible. If it appears three times, and two of those times it has the same value...it's still not a function. I would simplify this to "if an input value has more than one output value in the same table, we know it can't be a function.

**Comment by flannery-denny** [comment]
@schanzer. Thanks for the feedback. Much of this feels like changes that it would have been simpler to make and commit. In the future, please feel free to make edits in the asciidocs, push them and let me know that you've pushed some suggested edits for me to review.  

One of your comments suggested cutting the opening with the rectangles and another suggested editing it. We can discuss on Tuesday whether you thought some part of it was worth keeping.  Meanwhile, I will think on whether I have other ideas about how to open the lesson. For now, I've cut the whole section below (which did talk about photocopiers).

Also, you requested previously that I rename this lesson Vertical Line Test. Feels like perhaps we're moving toward it having another name...

> Select a volunteer to come to the board and draw a rectangle. While they're on their way, have the rest of your students draw a rectangle in their notebook.

>[.lesson-instruction]

> - Thank you! How did you know to draw just what I was looking for? _All rectangles have 4 sides and 4 right angles._
> - Did all of you draw rectangles with 4 sides and 4 right angles? _Yes_
> - Do all of your rectangles look just like this one? _No!_
> - Why Not? _Didn't specify ratio, size, color, fill, etc._
> - *We can also make rectangles in the programming environment, but @ifproglang{pyret}{Pyret} @ifproglang{wescheme}{WeScheme} couldn't have made this rectangle with my instructions. Why not?* _Machines need to be given the specific set of inputs that they are programmed to expect and use those inputs to make exactly what they've been programmed to make. The Domain for `rectangle` is Number, Number, String, String and if we don't give `rectangle` the arguments to satisfy its Domain we get an error message, not a `rectangle`!_
> - In the real world it is also usually useful to be able to specify exactly which rectangle I'm expecting. If I print copies for you, I expect them to be 8.5 x 11, like all of the other pages in your notebooks and folders. If someone loads giant paper in the tray, my copies will neither look good, nor will they fit in your notebooks. Similarly, when the business manager tries to print a bunch of addresses on envelopes on her printer, the job will get messed up if someone puts paper in the envelope drawer.

**Comment by flannery-denny** [comment]
@retabak @schanzer Do either of you know whether teachers who haven't paid for peardeck can still use interactive features [like this deck](https://docs.google.com/presentation/d/1IW5uMg491e33Av_XdGSivsAy28S9QSVivEYonpjTeF8/edit#slide=id.g7504f47e87_0_9) if we create them? 

Wondering whether this deck might only work for some teachers... and whether perhaps desmos has a comparable capability? I feel like I've maybe seen desmos activities with kids I've worked with where they can enter their response and see everyone's response on the next slide...

**Comment by schanzer** [comment]
@flannery-denny You're in the clear. PearDeck premium is only needed to _make_ slides that use the advanced features. Teachers who haven't paid for it can still _use_ slides with those features.
