### ISSUE TITLE
Std Deviation

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#829]
- [x] Integrate Data Cycle
- [x] Cat-Age worksheet
- [x] Cat-Age-Outlier worksheet

**Comment by schanzer** [comment]
@flannery-denny this lesson is ready for review!

**Comment by flannery-denny** [comment]
@schanzer which branch is this on?

**Comment by schanzer** [comment]
Anything starting with `fall2022` (I'm keeping  both in sync)

**Comment by schanzer** [comment]
@flannery-denny thanks for this! I totally agree that the Launch is too long. It also goes down into some subtle discussion, which is inappropriate for an introductory lesson. I've pushed a change that cuts out some of this text, and also starts the cat-age worksheet during the launch section to give students some grounding. 

Unfortunately we can't use lists in Pyret. We could ask them to compute the mean from a list on paper, but (a) they'll have already done this in measures of center, (b) of all the measures of center, mean is the one students generally know best already and (c) they still have to compute the mean in the workbook page - just not form a list.

Making question2 on the worksheet into a table is a great idea, but it makes life harder in question 6. We want students to list all the numbers, not group them.

I like the idea of using the Data Cycle with the animals dataset first as well.

I'll fix the data-cycle font-size in a separate commit, tagging the relevant git issue.

**Comment by flannery-denny** [comment]
@schanzer The lesson looks much better! 

- [ ] Noting that the image used on the computing standard deviation workbook page has a huge amount of white space at the bottom. Haven't printed to pdf to see how close you are to the bottom of the page, but on the web version the space at the top stands out to me.

- [ ] The effect of an outlier page could use the same reformatting that computing standard deviation got. Table for count. Star instead of arrow to be consistent.
- [ ] I suggest having the datacycle page for the animals dataset have 2 data cycles. With the first having a question that you want the whole class to discuss and the second being for students to generate their own question. Was going to check that there is enough data in the dataset for this, but... 
- [ ] There is no link to the animals dataset in the lesson plan.

**Comment by schanzer** [comment]
@flannery-denny great notes. Thanks!

I've implemented all of your changes, save for your recommendation to remove the writing portion of the data cycle and add a second one. Instead, I've given students a very concrete question to investigate, with instructions to write their findings as a response to the question. 

I think we're going to be doing this with a lot of data cycles throughout the pathway, giving students lots of practice answering a single question and writing about it -- I believe this provides the support that the research paper demands.

**Comment by schanzer** [comment]
@flannery-denny resol
