### ISSUE TITLE
CODAP review 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#839]
Notes: 
- None of the lessons have correct / updated slides.
- Glossary needs to be updated for CODAP (remove all mention of functions)
- Lesson notes need to be updated. Have not touched those since before maternity leave. 
- Checkboxes (below) to add lesson notes are for ME!
- Need to update Animals Table for CODAP so that attributes are one word / hyphenated / lowercase (i.e. age-in-years); TRUE / FALSE maybe need to be lowercase also?

**ds-intro**
- Everything is virtually the same!
- Removed "Meet Pyret" section.
- [x] Check lesson notes.

**codap-simple-data-types**
- There's no interactions window, so students experiment by creating a "test" column; very curious if we think this works as a way to introduce data types and let students play around / experiment.
- Grabbed "Applying Functions" chunk from the Pyret Contracts lesson, and added it to the end of this lesson. Have renamed this chunk "Applying Expressions." Not sure how we feel about the language change but it is consistent with the wording used in the Transformers UI. (CODAP, however, uses "function" terminology [here](https://codap.concord.org/help/functions).) I felt like this chunk fit into this lesson pretty nicely - curious what you think!
- [x] Check lesson notes.

**codap-displaying-categorical-data**
- [x] Need to revise worksheet answer keys to be platform neutral (include hand-drawn pics of data displays rather than displays generated by Pyret)
- [x] Check lesson notes.

**codap-transformers-1**
- Need to add lots of Transformer UI screenshots (not added yet because UI is not finalized)
- This lesson now includes a soft intro to Purpose Statement and Contract without introducing the design recipe yet [sort doesn't require design recipe use, anyhow!); how are we feeling about this? 
- The 'investigate' session of Sort Part 2 is pretty massive. Not sure how to trim it, though? I think all this stuff belongs in the same section.
- [x] Check lesson notes.

**codap-transformers-2**
- This lesson is on the three transformers that use the DR.
- [x] Need to revise function cards so that they do NOT include function names (brief sentence descriptors instead), because transformers do not invite students to name expressions.
- What do you think about `has-glasses`? (Screenshot below.) I think formatting looks kind of funny, not sure how to change.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/87144723/162438172-146ed167-3313-45c9-8d8e-0a46e9af19d8.png">

- [x] Check lesson notes.

**Comment by schanzer** [comment]
@retabak there's a lot more to say, but this is the part I've been able to wrap my head around so far. Will add more tomorrow.

**PATHWAY**

- [ ] When I build the pathway (`./build-pathway -f --proglang codap data-science-codap`), the pathway page says "Data Science (in CODAP)". Shouldn't it just say "Data Science?"

**Intro to CODAP & Displaying Categorical Data**

- [ ] How about we just title it "displaying categorical data with CODAP?"
- [ ] "Rather, the goal is to have them develop some loose familiarity." with what? This sentence feels unfinished, and open to an unflattering interpretation

**Simple Data Types**

- [ ] I don't see this lesson linked from the pathway?

**Transformers**

- [ ] "Explain to students that the Sort Transformer consumes: (1) a dataset; (2) a formula; (3) the type that the formula evaluates to; and (4) a sort direction (ascending or descending)." -- it does? I thought a transformer just consumes a table? I feel like maybe you're using contract vocabulary for something that isn't actually a contract
- [ ] "Students may be more familiar with filters that actually change the table." I'm not sure that students would be familiar with this. Maybe just say "students might expect the Transformer to _change_ the table."
- [ ] I feel like this lesson could really use some workbook pages to scaffold it. There's a _lot_ of on-computer activity and verbal instructions, and it could use some balance with written instructions and a product that teachers can assess and kids can refer back to

**Method Chaining**

- [ ] This references the Design Recipe, but it hasn't been introduced before.
- [ ] Both Design Recipe WB pages have the same title, which makes it confusing when the instructions say "Define the Transformers and formula expressions on [Design Recipe](https://github.com/bootstrapworld/lessons/method-chaining-codap/pages/design-recipe-1.html) and [The Design Recipe](https://github.com/bootstrapworld/lessons/method-chaining-codap/pages/design-recipe-2.html)."
- [ ] "Transformers can be chained, resulting in...." -- I think you mean _chained together_?
- [ ] I see that you have a worksheet that asks students to translate the chained transformer order into function notation -- how important is that notation to the pathway as a whole?

**Comment by retabak** [comment]
@schanzer these 5 lessons are ready for another look by you! So many new workbook pages!

**Comment by retabak** [comment]
*Method Chaining* is also ready to review now! @schanzer

**Comment by schanzer** [comment]
@retabak 

**Meta-notes**

- I think there's some confusion about when to use `[.lesson-instruction]`. Those blocks are _instructions for students to carry out_, and NOT places to teach new concepts or information
- When it comes to workbook pages, we're using `@fitb{}{}` instead of `@span{.blankline}{}`
- Instructions on WB pages that have no answer generally don't not need numbers. I'm not 100% rigid about this, and I'm open to pushback....but in general we've stuck to that approach for most of our pages thus far.

**Simple Data Types**

- [ ] Some of your WB pages are zero. It looks like you didn't add them to the workbook-pages list. Was this intentional?
- [ ] Made some small wording and wbpage changes. Feel free to check this off if you're ok with them, or once you've changed them to something you feel good about

**Displaying Categorical Data**

- [ ] In "Exploring other Displays", the launch could be a lot more fleshed out. You could talk about the fact that making a display in CODAP requires clicking buttons and selecting from menus...but which menus? You could even give students a 3m challenge to figure it out on their own, to demonstrate the number of settings they need to consider. THEN you introduce the three questions (not inside a lesson-instruction, but as part of the actual lesson), before sending them off to practice with the WB page. Right now, the important part (the three questions) is buried as "part 1" of the instructions, and given no justification.
- [x] I really like the wb pages you created for this!
- [ ] Made some small wording and wbpage changes. Feel free to check this off if you're ok with them, or once you've changed them to something you feel good about

**Introduction to Transformers: Sort**

- [ ] The name of this lessons should be aligned with the one that follows. Why is this lesson called "intro to transformers: X", but the next one is just "Y and Z"? Aren't they ALL introductions to transformers? Or is this lesson serving as an intro _and_ showing kids how to do X? 
- [x] I LOVE the way you've demoed the importance of preserving table state! Really nice.
- [ ] Maybe we can title these sections something more concrete than "sorting 1" and "sorting 2". I worry that teachers will miss the significance of the difference, and will think "ok, Bootstrap just wants me to know there are two ways. I'll pick the easier one."
- [ ] Made some small wording and wbpage changes. Feel free to check this off if you're ok with them, or once you've changed them to something you feel good about

**Filter, Transform, Build**

- [ ] Made some small wording and wbpage changes. Feel free to check this off if you're ok with them, or once you've changed them to something you feel good about.

**Comment by retabak** [comment]
@flannery-denny The first five codap lessons (of eight) are ready for you to review! They are on fall2022. To build, I use: `./build-pathway -F --proglang codap data-science-codap` 

Lingering things for me to do that you can ignore for now....
- [ ]  I have not gone through and changed workbook pages from `@span{.blankline}{}` to `@fitb{}{}` 
- [ ] I need to check workbook answers to make sure they are correct and complete. 
- [ ] Slides are not yet updated.

**Comment by flannery-denny** [comment]
DS INTRO - WIP
- [ ] The opening questions should be referred to and linked to from within the text of the lesson plan (which will auto-include them in the materials section).

**Comment by flannery-denny** [comment]
SIMPLE DATATYPES
- [ ] It took me a long time to figure out how to add a column in order to follow the directions. You have to click on the animals dataset table before the + sign appears. I'm getting to set this one aside until you resolves all of your NEED SCREENSHOTS so that I can view the lesson plan with still relatively fresh eyes.

**Comment by retabak** [comment]
So, the Brown undergrads have a few different versions of the Transformers plugin that have yet to be merged and go live on the CODAP site. 

So, for codap-transformers-1, you'll want to use [this link](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://idyllic-cat-9dfb8b.netlify.app/)

For codap-transformers-2, [this](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://statuesque-souffle-9d7a34.netlify.app/) is the link to use.

The link in the lesson plan is outdated, but it goes to the (currently) public-facing version of the Transformers plugin.

I can't seem to save the animals dataset to these non-published versions of CODAP.... so you'll need to import the spreadsheet. (Hamburger menu -> import -> URL.) Sorry that's a pain!

Here's the screenshot for codap-transformers-1:
<img width="178" alt="Screenshot 2022-04-29 210727" src="https://user-images.githubusercontent.com/87144723/166084600-62b576d3-bee4-4e9c-a50d-8817d5fb829c.png">

I think that's the only missing screenshot!

If any of this is too confusing, let me know. There's a lot going on.

**Comment by schanzer** [comment]
@retabak did you mean for this to go here in the transformers repo, and not in a curriculum issue?

**Comment by retabak** [comment]
@schanzer : Yep - definitely! Gonna delete it over there. Thanks.

@flannery-denny : 
So, the Brown undergrads have a few different versions of the Transformers plugin that have yet to be merged and go live on the CODAP site. 

So, for codap-transformers-1, you'll want to use [this link](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://idyllic-cat-9dfb8b.netlify.app/)

For codap-transformers-2, [this](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://statuesque-souffle-9d7a34.netlify.app/) is the link to use.

The link in the lesson plan is outdated, but it goes to the (currently) public-facing version of the Transformers plugin.

I can't seem to save the animals dataset to these non-published versions of CODAP.... so you'll need to import the spreadsheet. (Hamburger menu -> import -> URL.) Sorry that's a pain!

Here's the screenshot for codap-transformers-1:
<img width="178" alt="Screenshot 2022-04-29 210727" src="https://user-images.githubusercontent.com/87144723/166084600-62b576d3-bee4-4e9c-a50d-8817d5fb829c.png">

I think that's the only missing screenshot!

If any of this is too confusing, let me know. There's a lot going on.

**Comment by retabak** [comment]
So, the Brown undergrads have a few different versions of the Transformers plugin that have yet to be merged and go live on the CODAP site. 

So, for codap-transformers-1, you'll want to use [this link](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://idyllic-cat-9dfb8b.netlify.app/)

For codap-transformers-2, [this](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://statuesque-souffle-9d7a34.netlify.app/) is the link to use.

The link in the lesson plan is outdated, but it goes to the (currently) public-facing version of the Transformers plugin.

I can't seem to save the animals dataset to these non-published versions of CODAP.... so you'll need to import the spreadsheet. (Hamburger menu -> import -> URL.) Sorry that's a pain!

Here's the screenshot for codap-transformers-1:
<img width="178" alt="Screenshot 2022-04-29 210727" src="https://user-images.githubusercontent.com/87144723/166084600-62b576d3-bee4-4e9c-a50d-8817d5fb829c.png">

I think that's the only missing screenshot!

If any of this is too confusing, let me know. There's a lot going on.
