### ISSUE TITLE
Slide Infrastructure "punch list"

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#872]
We have several elements that we need to figure out how to process for Google Slides. This issue tracks each of them, and how they'll be handled

- [x] `@vocab{}` - should resolve to bold/italic text
- [x] `@printable-exercise` and `@opt-printable-exercise` - converted into a website URL, with the current season and year - and should show the title of the page!
- [x] if a table has no header, please use the text DELETE THIS ROW
- [x] `@link{}`, `@online-exercise` and `@opt-online-exercise` - converted into a straightforward link
- [x] `@show{(code ....)}` -- gets converted to straight text, and formatted using a serif font like Courier
- [x] `@math{...}` -- MathJax is converted to markdown text. This works well, with two limitations: (1) sqrt symbols don't show, and will instead render as `sqrt(....)`, and (2) fractions are not supported, and will instead render as `(numerator/denominator)`
- [x] `@smath{...}` -- same as above
- [x] Tables - md2gslides chokes on introductory text. I've added directive `@table{N}` for now to introduce a bogus header -- since our tables don't usually have headers -- where N is the number of columns in the table.
- [x] Text - bold, italics, underlined, etc is all done via markdown
- [x] Images - uploaded automatically. TWO CAVEATS: (1) there's a limit to how many images can be uploaded in one go, and (2) the size and position of the images is not yet controlled

`@show{(coe ...)}` -- **Workaround:** Converting @show{(coe ...)} to showing the Scheme expression for now, as it kinda looks like a linear squashdown of a CoE. (Having images for COE's generated programmatically is possible, but this will take a monumental effort)

**Comment by ds26gte** [comment]
The link directives don't really need to be processed for proglang, because build-slides operates inside the distribution directory where the proglangs have already been resolved when the lesson directory name is calculated

**Comment by flannery-denny** [comment]
@ds26gte you've made a lot of progress since yesterday! And thanks for adding the html link in the distribution folder!
When I build-slides I get [this deck](https://docs.google.com/presentation/d/1-XtKf4jQkgIhk_6ibnL5Lw2yC4BKkeh6q2TkI5V3ae8/edit#slide=id.d86fc952-c6f3-11ec-93fa-332e5ebaf566)

- [ ] slide 3 the image lands on top of the text. confirming we can't fix this in md and should plan to fix it by hand in the end?
- [ ] On slide 5 I notice there are two different fonts for the numbers. Curious about that.
- [ ] Slide 9 is missing the link to the workbook page. Do you know why?
- [ ] Slide 10 is missing at least one of the links for the list. Do you know why?
- [ ] Slide 12- The table is building with an empty header row. Do you know how to fix that?
- [ ] Slide 16 - missing links
- [ ] slide 17 - missing links
- [ ] slide 19 - the table and the text land on top of each other. is this something we can address in md or something we'll end up fixing by hand?
- [ ] slide 21 - missing lots of links

**Comment by flannery-denny** [comment]
@ds26gte The tables are building as expected. The links are not.

The names you have chosen to pull for the slides are not intelligible to teachers or students.
![Screen Shot 2022-04-28 at 1 53 28 PM](https://user-images.githubusercontent.com/66691020/165825961-8c275f30-0e77-42cd-8112-c1830f58123d.png)

Here's what the same link looks like in the lesson plan 
![Screen Shot 2022-04-28 at 1 54 02 PM](https://user-images.githubusercontent.com/66691020/165826117-58466ba6-a467-4375-b670-f4f832438d9d.png)

**Comment by flannery-denny** [comment]
@schanzer Turns out @ds26gte is no longer working on slides in `__sample` and we have to look at the `order-of-operations` lesson to see how things are working now... once the links are being built from within a pathway they get the correct names.

**Comment by ds26gte** [comment]
(That extended example slide.md file was originally written by Flannery for `order-of-operations` and its links only make sense in that milieu. My own example slide.md was much shorter and worked in `__sample-lesson`.)

**Comment by schanzer** [comment]
@flannery-denny It appears that Dorai has completed all the infrastructure issues we listed. OK to close?

**Comment by flannery-denny** [comment]
A huge improvement over last year's process!
