### ISSUE TITLE
Add an optional "teaching dataset 2"

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#889]
It's nice when everyone is on the same dataset (animals). It's nice when everyone has a chance to practice what they've learned (their own). 

These two options have a tension, since the second undercuts the value of the first. @flannery-denny has an excellent idea: let's make a _second teaching dataset_. This would give kids more practice, but also give the teacher the piece of mind that they're all on the same dataset.

**This would be strictly optional**, so it doesn't block WB printing.

------------------

Added from #888 👍 
Change description of Choosing your dataset, Once we have a second teaching dataset
Current Description Students select a real world dataset to investigate for the remainder of the course. we could add… If your class is planning to write the capstone research paper, this is the lesson when…

**Comment by flannery-denny** [comment]
@schanzer Two proposals for a second teaching dataset. Are either more appealing to you? Suggestions?

**Environmental Impact of Food** [beginning with this dataset](https://ourworldindata.org/environmental-impacts-of-food)

It includes 37 food items

Quantitative Columns could be 
- carbon emissions per kilogram of food
- emissions per 100g of protein
- land use per kilogram of food
- land use per 100g protein
- fresh water withdrawal per kg of food
- water pollution per kg of food

Categorical Columns could be
- food source: animal/plant
_I'd have to think on other possible categorical columns_

_______________________

Or a dataset with about 200 rows of countries

Quantitative Columns:
From this source: [https://ourworldindata.org/food-supply](https://ourworldindata.org/food-supply)

- GDP Per Capita
- Daily Kcalories per capita
- Animal protein consumption per day
- plant protein consumption per day
- % of people that are undernourished

From [this source](https://ourworldindata.org/obesity):
- % overweight or obese

From [this source:](https://ourworldindata.org/explorers/co2?tab=table&facet=none&country=CHN~USA~IND~GBR~OWID_WRL&Gas=CO%E2%82%82&Accounting=Production-based&Fuel=Total&Count=Per+capita)
- 2020 C02 emissions per capita

From [this source](https://data.worldbank.org/indicator/EN.POP.DNST)
- Population density per capita

Categorical Columns:
From this source: [https://datahub.io/sagargg/world-religion-projections](https://datahub.io/sagargg/world-religion-projections)
- Region
- Hemisphere
- Majority Religion

**Comment by schanzer** [comment]
@flannery-denny I quite like the second dataset, but to be a good stand-in for the Animals Dataset we need a few other qualities:

- columns that exhibit different shapes of data
- columns with enough skew to make mean and median meaningfully different
- scatter plots that exhibit correlations
- obvious grouped samples
- grouped samples where a correlation becomes stronger per-sample than for the whole population
- possible threats to validity
- interesting outliers

I _think_ the second dataset likely has it, but you'll want to confirm before proceeding

**Comment by flannery-denny** [comment]
@schanzer I _think_ [this](https://code.pyret.org/editor#share=1XkTWBTssYznSgB8PZ6ky7Cvc6ea-BdBU&v=5f98106) starter file meets your requirements. Please have a look and let me know if there's something missing that I should focus on.

**Comment by schanzer** [comment]
@flannery-denny awesome to see this taking shape!

- it looks like the `gdp` is missing the data for cuba. I see that it's not available at all for 2017 - can we just remove the row and explain why? Ditto for North Korea, Taiwan, etc?
- does "continent" add a lot to the dataset? I wonder if it's even needed
- recommend another name for `gdp`, since it's not actually showing GDP. Maybe `gdp-pc`?
- Can we rename `calories` to `cal-produced`? I feel like it's going to be a persistent source of confusion for kids, and the teacher will have to remind them over and over that it's NOT calories consumed
- 'vegetal' is not a term I've seen before. Can we just do `veg-p`? And maybe `meat-p` to match? They both have the benefit of bring shorter, too
- man it would be cool to get a boolean column showing whether they import a majority of their food
- I could also imagine a useful column being the % of the country's land that is used for food production, or % of country's labor force that works in farming

**Comment by flannery-denny** [comment]
@schanzer I've updated the [google sheet](https://docs.google.com/spreadsheets/d/1DYVHT7SSjnoDp4MQ80Z1qZSqFdEIlR8Gd20eMx9f1JA/edit?usp=sharing)

- It now includes % land used for agriculture 
- 2 boolean columns which countries produce more food than they import & which countries produce more grain than they import

I am not able to build plots with the[ pyret file](https://code.pyret.org/editor#share=1XkTWBTssYznSgB8PZ6ky7Cvc6ea-BdBU&v=164e917) and am getting errors that claim I'm providing a contract violation for things I've checked the contract on.
![Screen Shot 2022-08-22 at 12 06 35 PM](https://user-images.githubusercontent.com/66691020/185978933-0e0d4062-078a-4ff7-916b-aa551bd7110e.png)
![Screen Shot 2022-08-22 at 12 06 04 PM](https://user-images.githubusercontent.com/66691020/185978953-d45a3c05-4bf8-402c-aa64-13581bfa7e52.png)
![Screen Shot 2022-08-22 at 12 17 42 PM](https://user-images.githubusercontent.com/66691020/185980943-ca8614c7-01b2-465f-96d3-c26714e0c455.png)

I am hopeful that it's something simple I missed in the google sheet setup that we can fix together or perhaps that when I looked for an updated context I picked the wrong one. I know that the one I had saved as a template was outdated. (Further evidence that it would be helpful if the pyret team made it so that Bootstrap DS was a context in the drop down menu)
 
As for your questions re: column titles

- daily per capita caloric supply - this is not the calories produced - it is the calories available per person, and the UN's best estimate of calories consumed (although admittedly likely a little high because it doesn't account for waste)
- animal-p = Animal Protein (g/capita/day) - this can not be meat protein, because it includes eggs and dairy
- plant-p = Vegetal Protein (g/capita/day) - vegetal means "relating to plants"

I'm honestly not sure whether it's more interesting to disaggregate data by region or continent. They turn up different distributions. But I scaled it back to region.

Wondering if we should add a column for area or land-locked?

**Comment by schanzer** [comment]
@flannery-denny the problem is that these columns need to contain only Numbers, Strings, or Booleans. If you evaluate `food-table`, you'll immediately notice some very strange datatypes!

I think I'd mentioned the problem with blank cells before - those are what's tripping you up here. Moldova, for example, has a blank cell in it.

Your column explanations work for me. Thanks!

I think region is fine for categorical, and I LOVE the idea of a land-locked boolean column! Area I could go either way on -- I think it's fine to release without it, and we can always add it later if we see a need for it.

**Comment by flannery-denny** [comment]
@schanzer I've added a landlocked boolean column.   

I didn't find any strange datatypes. 
I did find some empty cells 
- I would like to ask the pyret team whether it's possible to give a better error message for blank cells. 
- I think I've fixed them all, but please kick the can because it's really hard to notice an empty cell in a table this long, even when I look one column at a time. 

Will work on adding this to lesson plans.

Do you think food-table is the best title?

**Comment by schanzer** [comment]
@flannery-denny are you sure you didn't see any exotic types? No `SOME(...)`s or `NONE`s? You certainly saw the error messages when trying to make displays using those types!

Pyret allows for blank cells, so there's no error message to give. And it looks like you took care of the blank cells, so we're good. In the future, there's no need to go looking in the spreadsheet to find a blank one: just load it into Pyret and print out the resulting table. 

I was thinking `nutrition-table`, but that also feels ripe for typos and spelling errors. I think I'm ok with `food-table`.

**Comment by flannery-denny** [comment]
@schanzer there were definitely no SOME(...)s or NONEs? Unless you changed something, those errors came from empty cells in the columns, that i was building with, which is why I think we can do better with our error messages.

Also, hard to understand why you think it would be easier for me to see an empty cell in pyret than in google sheets... where I had to work in order to fix the problem... curious what special super powers pyret has that I don't already know about :)

**Comment by flannery-denny** [comment]
@schanzer close if you're satisfied.

**Comment by schanzer** [comment]
@flannery-denny almost there! Left a few comments on the last commit.

**Comment by flannery-denny** [comment]
@schanzer close if you're satisfied or edit or lmk what else you want changed.

**Comment by schanzer** [comment]
@flannery-denny this looks awesome. Thank you!!
