### ISSUE TITLE
SA of Rec Prism Lesson needs revision

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#905]
I am making slides for Surface Area of a Rectangular Prism and ended up poking around the starter file. I like the essence of this activity a lot, but the starter file is VERY CONFUSING. I had a hard time understanding what to do. Also, _every time_ a line # is mentioned (in the lesson and in the starter file), the line number is wrong. 

I also couldn't help but wonder if this is supposed to be a self-guided activity (that's how it feels like it was designed, based on the starter file) or if it's something that a class does together, step by step. The instructions in the lesson are much clearer than the instructions in the starter file. Some facilitation notes would be very valuable / helpful. Also a completed "answer key" starter file would be useful for teachers. 

Anyhow, here are many little issues with the instructions in the starter file:
- [ ] Line 4 - "in this code" - what code? It's not obvious that you're referring to line 15. (I think you're referring to line 15?)
- [ ] Lines 6-8 - this code sort of comes out of nowhere. Why are you giving me length, width and height now? What is this? Why do I care?
- [ ] Line 10 - Explain the purpose for typing "prism" into the interactions area.
- [ ] Line 11 - Why click Run before typing "print-imgs(faces)"? Directions here tell me I'll see faces (plural!) - but I only see one face? (I think that's intentional, but it feels like an error / bug.)
- [ ] Line 13 / step 2 - "Looking at the prism" - Woops, that prism is gone if students clicked run (as instructed) in the previous step.
- [ ] Line 13 / step 2 - Refers to Line 22, should say Line 15
- [ ] Line 15 - 17: I think it would be helpful to provide another face or two (i.e. back, left). It does not feel obvious to me what kids are supposed to do here.
- [ ] Line 19 - incorrectly refers to line 20
- [ ] The printed rectangles are tiny! I think these would be extremely challenging to tape together. My scotch tape is WIDER than the 50x180 pixel rectangle. Kids will need to splice a standard piece of tape in half to make this work, I think? 

Can we revamp this lesson so that it has TWO main segments, like the starter file? 

Also, as a teacher, I'm pretty sure I'd have the rectangles file printed before my kids get to the printing step. I suspect classrooms where all kids are connected to a printer are few and far between.  Providing this tip to teachers could be useful.

**Comment by retabak** [comment]
I'm not sure who wrote this lesson originally! I am happy to play with revising it at some point if that would be useful.

**Comment by flannery-denny** [comment]
@retabak I wrote the lesson & spec'd the teachpack @schanzer made. @schanzer has already given feedback on the lesson. Fresh eyes would be valuable.

At the time the lesson was written, we were transitioning from everything being in the lesson plan to more info being in the starter file. In the meantime, we've transitioned to more being in the starter file than we used to have, but making workbook pages to accompany starter files to do some of the heavy lifting.

I'll take another pass and let you know when it's ready for review.

**Comment by retabak** [comment]
A workbook page would probably be a huge help! Happy to give feedback when you're ready.

**Comment by flannery-denny** [comment]
@retabak pushed some changes.  Made the workbook page and modified the starter file rather than addressing your checklist. Does it scratch the itch?

Just read your idea about preprinting the file... hadn't considered that possibility.  I would be more likely to split the lesson over two days so that I could print their files for them at night if I didn't have access to printing during class, but I could also imagine being able to book the computer lab for an activity like this in both of the last 2 schools where I taught.

Feel free to add a pedagogy box offering up your suggestion. And let me know whether you think it's important to remove / rewrite the directions about changing the prism dimensions from the workbook page in order for people to use your suggestions.

Also do you think teachers need a starter file for this with the solutions? 
Do they need the surface area for the given dimensions to be calculated?

**Comment by flannery-denny** [comment]
@retabak no idea why that starter file didn't save, but hopefully the correct one shows up now.

**Comment by retabak** [comment]
@flannery-denny - Updated the lesson as discussed. Take a look.

I think that the Pyret starter file still needs some minor adjustments! I've proposed them [here](https://docs.google.com/document/d/1cuOJaBaV3HYIBBdtYK0HYGdCvMyhCyGsUo5EnQN_EN8/edit?usp=sharing); each suggestion is in bold font and has a comment attached.

**Comment by flannery-denny** [comment]
@retabak
For the same reason that we can’t put part2 of the code ahead of part1. We can’t use printimgs until we’ve defined the faces so we’ll have to remove those directions from line 27 in the lesson plan and in the starter file. 

I updated the words in your doc to reflect the change if you want to tackle updating the starter file.

Flannery

**Comment by retabak** [comment]
Oh, good catch. I sort of like having them try print-imgs anyhow to see that just one face appears? What if in Part 2, we say, "Type print-imgs(faces). How many rectangles do you see?" and then in Part 3, we have them confirm that all faces appear (as you suggested)?

And yep, I can work on updating the starter file.... although I'm not sure what account to login to Pyret with in order to do so?

**Comment by flannery-denny** [comment]
@retabak If you open it from the google drive you can update the starter file. Doesn’t matter what account you’re logged into as long as you publish.

Flannery

**Comment by retabak** [comment]
Okay - I think this issue is ready to be closed but I'd feel a little better if someone checked over my work! @schanzer ??

**Comment by schanzer** [comment]
@retabak the workbook page tells me to "Complete the faces list, then type `print-imgs(faces)`into the interactions area". I don't think I would know what to do here as a student, though I assume you're searching for "top, bottom, left, right, back, front"? 

How will students know to add commas in Pyret? How will they know not to use the word "and"?

Starting with Part 2 seems really counterintuitive. And question six seems aimed at a learning goal that isn't part of the lesson. I would start with part 1, have them define all the faces, then explicitly tell them how to add those faces in part 2.

Also -- was it intentional that we no longer print the dimensions on the face images?

**Comment by retabak** [comment]
Hm, I can add some teacher notes to the lesson re "top, bottom, left, right, back, and front" as well as a note about no commas and no "and".

Question 6 can definitely be nixed. 

Re: starting with Part 2 -- having students define the faces before they've looked at and listed them feels very confusing to me. Whenever I teach surface area, I have kids just analyze the 3D solid and THEN look at individual faces.

**Comment by flannery-denny** [comment]
@schanzer they should definitely still print with dimensions and did last time I played with it!

Flannery

**Comment by retabak** [comment]
okay. Made some changes to the starter file and worksheet and moved around some sections of the lessons. Take a look @schanzer (or @flannery-denny , if you're up to it)!

**Comment by schanzer** [comment]
@retabak MUCH better. I made two small changes (feel free to review if you want), but they are not significant and I think this is good to close.
