### ISSUE TITLE
Fixes from Printed DS Workbook

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#918]
I'm reading through the workbook and will commit fixes one page at a time to make it easy for other people to see whether I caught what they're seeing. Expect to have committed all of my fixes by the end of today. 

Things for @schanzer to address (WIP):
- [x] Regression on landscape page orientation. Titles should be near the spine.
- [x] What's on your mind page placement feels very random and sometimes disruptive
- [x] What's on your mind pages should have 3 more lines per page.
- [x] p. 47 and p.38 both talk about skew. The best explanation would be a synthesis of the two. Where do you think the notes belong?
- [x] I'm also not sure on the order of 53 and 54. I would expect making the boxplot by hand to come before the data cycle page? I'm not as sure about this.
- [x] p 56 and p 57 have totally different titles, but are otherwise nearly identical.  Why are the titles so different? Is one of them supposed to be an opt-printable exercise?
- [x] Please add one more @fitb to the data cycle template for the last question... "What new question(s) does this raise?". 
- [x] p. 45 and p.53 are the same. Do we want them both? if so, p. 45 should only be about histograms, because we haven't introduced box plots at that point. Or maybe neither is supposed to be about boxplots and histograms?
- [x] Next time you build the pdf - leave more time - and doublecheck that no pages say "processing math: 100%"
- [x] p73 the fitb on this page are inconsistent lengths. The ones used in the final line of the function definition feel correct.
- [x] p130 & 131 Trust but verify 1 & 2. Line spacing is inconsistent **One use @fitb and one used @span blank line. I made them both use @span blank line, which gives much more space.**
- [x] p.136 & 137 Threats to validity 1 & 2 use two different font sizes and are inconsistent about italics
- [x] The jump from design recipe to form, direction & strength is very abrupt! I would expect notes on page
- [x] We have notes on the design recipe in 2 places - p105 and p93. The ones on p105 come after we first see the design recipe.
- [x] Do we want to rename the Ethics & Privacy Lesson --> Ethics, Privacy & Bias? If so, change it on the lesson plan and in the link to the lesson at the top of _Case Study: Ethics, Privacy, and Bias_.
- [x] The notes for Computing Relationships are quite heady - can we bring them down to earth?

**Comment by schanzer** [comment]
God bless you, @flannery-denny

**Comment by schanzer** [comment]
@flannery-denny 

Added an extra @fitb to Data Cycle template.

pg 38 is about what skew means in the context of histograms (visual). 47 is about what skew means in the context of mean/median (computational). If measures of center were deeply entwined with histograms, I could see having them share a notes page. That's not the case here. I don't think combining them is the right move.

Good catch on 45 and 53. Removed "and box plots" from 45.

Making the boxplot by hand DOES come before the data cycle! The lesson asks students to turn back to page 49 for this exact purpose. After doing it by hand for the Animals Dataset on 49, then use the data cycle on page 53. Page 54 is a throwback to 49, but this time they're doing it with their _own_ dataset.

56 and 57 ask students to do the same work, but 57 is all about showing students the effect of an outlier on standard deviation.  Neither is intended to be optional. Do you think it's less important to show students how outliers impact standard deviation?

Leaving more time doesn't work consistently. In our pre-puppeteer days, we plugged `wkhtmltopdf` into some MathJax event so that it would always print after MathJax was done. I'll hack at it a bit tonight, but this might need Dorai's hand.

**Comment by schanzer** [comment]
Nevermind. Got it.

**Comment by flannery-denny** [comment]
I have fixed all of the things I caught that don't involve me opening up a starter file or talking with Emmanuel. I will deal with the more complicated fixes on Monday.

**Comment by schanzer** [comment]
@flannery-denny made most of the requested changes. As for the 23 lines -- a few algebra lessons have the same number of lines as well, but you didn't flag it when reviewing that workbook. I'd like to keep this consistent, so I assume you'd prefer Algebra has more lines, as well?

**Comment by schanzer** [comment]
@flannery-denny made most of the requested changes. As for the 23 lines -- a few algebra lessons have the same number of lines as well, but you didn't flag it when reviewing that workbook. I'd like to keep this consistent, so I assume you'd prefer Algebra has more lines, as well?

**Comment by flannery-denny** [comment]
I would like them all to be the same and I asked for them to fill the page in algebra as well.

Flannery

**Comment by retabak** [comment]
@flannery-denny @schanzer my bad - spacing issue is resolved. Still not sure if there's a reason for requesting name on one page and name + index on the other? 

Seeing that there are 7 lines on one page and 9 lines on the other. Gonna put 8 lines on each!

**Comment by schanzer** [comment]
@retabak I've pushed fixes for all of the above save one -- taking out those commas feels _really_ wrong. Like if I said "These materials were developed partly through contributions from many people (Flannery, Rachel and Dorai)". 

@flannery-denny I believe this workbook is ready to PRINT AND SHIP tomorrow morning. Last call....

**Comment by flannery-denny** [comment]
@schanzer If you haven’t shipped to print yet, can you doublecheck that the article from the register & the questions about it ended up on the same spread. I think they were in the checking your work or trust but verify lesson. If not, you can add a what’s on your mind page to the end of the lesson that comes before it (or take one out.)
Thanks.

Flannery

**Comment by schanzer** [comment]
@flannery-denny just double-checked in the Lulu preview. I think we're good to go! CLOSING. 

Great work, team!
