### ISSUE TITLE
CODAP transformers placeholder text

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#921]
Hey! The Brown undergrads have requested a list of placeholder/helper text for the various transformers. (See image below; this is an update that I requested.)

![image](https://user-images.githubusercontent.com/87144723/172202295-72aa99ad-3b93-4897-848f-d39702b8e296.png)
 
 I know we definitely want helper text for build, transform, filter, and sort - but was wondering if we want helper text for any of the Transformers that might exist in lessons that have yet to be CODAPified? I think that this *is* something we want (right now, it redundantly says "Transformer Name" both in and above the box - see image below) but am not sure what names we'd propose for some of the Transformers (e.g., "Pivot Wider"). 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/87144723/172204167-fd83b355-ae19-45ff-b85a-8679b27448d5.png">

Any thoughts on this? Here is the helper text I'm proposing so far. Are these consistent with naming conventions used in Pyret?

Build Attribute: build-kilos
Transform Attribute: lbs-to-kg
Filter: filter-is-heavy
Sort: order-by-pounds

**Comment by schanzer** [comment]
@retabak we don't have quite the same conventions in Pyret as we do in CODAP, since the "Transformer" concept exists as separate "function" and "method" concepts. Their separation in Pyret means the same function (e.g. - `is-dog`) can be used both to filter _and_ build.  

I think your naming convention makes a lot of sense. Go for it!

As for things like "Pivot Wider" -- how about the sample name be "pivot-species", which specifies the column on which the table will pivot?
