### ISSUE TITLE
Linear Functions lessons use pyret defintions in wescheme

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#970]
@schanzer nearly all of the workbook pages for this lesson use the word pyret. And most of them have pyret function definitions. You advocated for this. I'm not sure that just translating them into wescheme supports the learning goals.

- [ ] identifying slope and y-intercept in definitions
- [ ] matching graphs to function definitions
- [ ] summarizing graphs with function definitions'
- [ ] matching tables to function definitions
- [ ] summarizing tables with function definitions

**Comment by schanzer** [comment]
Ah, that was back when this lesson was not part of the algebra pathway. And since WeScheme doesn't have the graphing or table library, this is unfixable. 

OK, this is just another argument for formally splitting algebra into `algebra-pyret` and `algebra-wescheme`. I'm going to close this and open a new issue for that.
