### ISSUE TITLE
Expansion of EXAMPLEs does not handle (?ANS) or (?FITB) correctly

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#986]
The following code, taken from `functions-examples-definitions/langs/en-us/pages/match-examples-contracts.adoc`, works beautifully in both Pyret and WeScheme:
```
@show{
(code '(EXAMPLE
       (f "pink" 5) (star 5 "solid" "pink")
       (f "blue" 8) (star 8 "solid" "blue")))
}
```
However, rendering seems to die if this code includes either `(?ANS)` or `(?FITB)`.

**Comment by ds26gte** [comment]
Cleaned it up a bit, but notc that code with `?ANS/?FITB` uses a different home-made renderer rather than codemirror, as the latter doesn't handle the special spans we use for the blanks. We could give up on spans for blanks and use a judicious number of underscores instead, but this would prevent us from styling them, both in their filled and unfilled versions.

In general, codemirror chokes on any spans in the code fragments fed to it.
